/* eslint-disable @typescript-eslint/no-redundant-type-constituents */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/tasks/{id}/tags/{tagId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add tag to task
     * @description Associate a tag with a task.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
          /** @description Tag UUID */
          tagId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Tag added to task successfully */
        201: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task or tag not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    /**
     * Remove tag from task
     * @description Remove a tag association from a task.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
          /** @description Tag UUID */
          tagId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Tag removed from task successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task or tag not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tasks/{id}/dependencies/{dependsOnId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add task dependency
     * @description Add a dependency relationship between two tasks.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
          /** @description Dependency task UUID */
          dependsOnId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dependency added successfully */
        201: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Invalid dependency (e.g., circular dependency) */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    /**
     * Remove task dependency
     * @description Remove a dependency relationship between two tasks.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
          /** @description Dependency task UUID */
          dependsOnId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dependency removed successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task or dependency not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tasks/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List tasks
     * @description Retrieve a list of tasks with optional filtering and pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by project */
          projectId?: string;
          /** @description Filter by status */
          status?: 'pending' | 'in_progress' | 'completed' | 'cancelled';
          /** @description Filter by priority */
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          /** @description Maximum number of tasks to return */
          limit?: number;
          /** @description Number of tasks to skip */
          offset?: number | null;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Tasks retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskListResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a task
     * @description Create a new task.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateTaskRequest'];
        };
      };
      responses: {
        /** @description Task created successfully */
        201: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tasks/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a task
     * @description Retrieve a single task by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Task retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a task
     * @description Delete a task by its ID.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Task deleted successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a task
     * @description Update an existing task. Only provided fields will be updated.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateTaskRequest'];
        };
      };
      responses: {
        /** @description Task updated successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/tasks/{id}/dependencies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get task dependencies
     * @description Retrieve all tasks that this task depends on.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dependencies retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskDependenciesResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}/dependencies/{dependsOnId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add project dependency
     * @description Add a dependency relationship between two projects.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Project UUID */
          id: string;
          /** @description Dependency project UUID */
          dependsOnId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dependency added successfully */
        201: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Invalid dependency (e.g., circular dependency) */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Project not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    /**
     * Remove project dependency
     * @description Remove a dependency relationship between two projects.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Project UUID */
          id: string;
          /** @description Dependency project UUID */
          dependsOnId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dependency removed successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Project or dependency not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List projects
     * @description Retrieve a list of projects with optional filtering and pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by initiative */
          initiativeId?: string;
          /** @description Filter by status */
          status?: 'planning' | 'active' | 'on_hold' | 'completed' | 'cancelled';
          /** @description Maximum number of projects to return */
          limit?: number;
          /** @description Number of projects to skip */
          offset?: number | null;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Projects retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ProjectListResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a project
     * @description Create a new project.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateProjectRequest'];
        };
      };
      responses: {
        /** @description Project created successfully */
        201: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ProjectResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a project
     * @description Retrieve a single project by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Project UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Project retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ProjectResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Project not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a project
     * @description Delete a project by its ID.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Project UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Project deleted successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Project not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a project
     * @description Update an existing project. Only provided fields will be updated.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Project UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateProjectRequest'];
        };
      };
      responses: {
        /** @description Project updated successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ProjectResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Project not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/projects/{id}/dependencies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get project dependencies
     * @description Retrieve all projects that this project depends on.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Project UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dependencies retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ProjectDependenciesResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Project not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/events/{id}/participants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add participant to event
     * @description Add a user as a participant to an event.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Event UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['AddParticipantRequest'];
        };
      };
      responses: {
        /** @description Participant added successfully */
        201: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['EventParticipantResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Event or user not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/events/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List events
     * @description Retrieve a list of events with optional date filtering and pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter events starting on or after this date */
          startDate?: string | null;
          /** @description Filter events starting before this date */
          endDate?: string | null;
          /** @description Maximum number of events to return */
          limit?: number;
          /** @description Number of events to skip */
          offset?: number | null;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Events retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['EventListResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create an event
     * @description Create a new event.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateEventRequest'];
        };
      };
      responses: {
        /** @description Event created successfully */
        201: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['EventResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/events/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get an event
     * @description Retrieve a single event by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Event UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Event retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['EventResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Event not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete an event
     * @description Delete an event by its ID.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Event UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Event deleted successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Event not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update an event
     * @description Update an existing event. Only provided fields will be updated.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Event UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateEventRequest'];
        };
      };
      responses: {
        /** @description Event updated successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['EventResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Event not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/events/{id}/participants/{participantId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove participant from event
     * @description Remove a participant from an event.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Event UUID */
          id: string;
          /** @description Participant record UUID */
          participantId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Participant removed successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Event or participant not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update participant status
     * @description Update the RSVP status of an event participant.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Event UUID */
          id: string;
          /** @description Participant record UUID */
          participantId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateParticipantStatusRequest'];
        };
      };
      responses: {
        /** @description Participant status updated successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['EventParticipantResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Event or participant not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/initiatives/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List initiatives
     * @description Retrieve a list of initiatives with optional filtering and pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by status */
          status?: 'draft' | 'active' | 'completed' | 'archived';
          /** @description Filter by parent initiative */
          parentId?: string;
          /** @description Maximum number of initiatives to return */
          limit?: number;
          /** @description Number of initiatives to skip */
          offset?: number | null;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Initiatives retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['InitiativeListResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create an initiative
     * @description Create a new initiative.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateInitiativeRequest'];
        };
      };
      responses: {
        /** @description Initiative created successfully */
        201: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['InitiativeResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/initiatives/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get an initiative
     * @description Retrieve a single initiative by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Initiative UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Initiative retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['InitiativeResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Initiative not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete an initiative
     * @description Soft-delete an initiative by its ID.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Initiative UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Initiative deleted successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Initiative not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update an initiative
     * @description Update an existing initiative. Only provided fields will be updated.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Initiative UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateInitiativeRequest'];
        };
      };
      responses: {
        /** @description Initiative updated successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['InitiativeResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Initiative not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/time-blocks/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List time blocks
     * @description Retrieve a list of time blocks with optional date filtering and pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter time blocks starting on or after this date */
          startDate?: string | null;
          /** @description Filter time blocks ending before this date */
          endDate?: string | null;
          /** @description Maximum number of time blocks to return */
          limit?: number;
          /** @description Number of time blocks to skip */
          offset?: number | null;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Time blocks retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TimeBlockListResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a time block
     * @description Create a new time block.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateTimeBlockRequest'];
        };
      };
      responses: {
        /** @description Time block created successfully */
        201: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TimeBlockResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/time-blocks/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a time block
     * @description Retrieve a single time block by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Time block UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Time block retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TimeBlockResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Time block not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a time block
     * @description Soft-delete a time block by its ID.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Time block UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Time block deleted successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Time block not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a time block
     * @description Update an existing time block. Only provided fields will be updated.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Time block UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateTimeBlockRequest'];
        };
      };
      responses: {
        /** @description Time block updated successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TimeBlockResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Time block not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/time-blocks/{id}/tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Link task to time block
     * @description Link a task to a time block.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Time block UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['LinkTaskRequest'];
        };
      };
      responses: {
        /** @description Task linked successfully */
        201: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TimeBlockResponse'];
          };
        };
        /** @description Validation error or task already linked */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Time block or task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/time-blocks/{id}/tasks/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Reorder tasks in time block
     * @description Reorder the tasks linked to a time block.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Time block UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ReorderTasksRequest'];
        };
      };
      responses: {
        /** @description Tasks reordered successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TimeBlockResponse'];
          };
        };
        /** @description Validation error (e.g., task IDs do not match) */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Time block not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/time-blocks/{id}/tasks/{taskId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Unlink task from time block
     * @description Remove the link between a task and a time block.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Time block UUID */
          id: string;
          /** @description Task UUID */
          taskId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Task unlinked successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Time block or task link not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UnauthorizedError: {
      /** @enum {string} */
      error: 'Unauthorized';
      /** @default Authentication required */
      message: string;
    };
    NotFoundError: {
      /** @enum {string} */
      error: 'Not found';
      /** @description Resource description */
      message?: string;
    };
    ErrorResponse: {
      /** @description Error type or code */
      error: string;
      /** @description Human-readable error message */
      message?: string;
      /** @description Additional error details */
      details?: Record<string, unknown>;
    };
    /** @description Task response */
    TaskResponse: {
      data: components['schemas']['TaskWithRelations'];
    };
    TaskWithRelations: components['schemas']['Task'] & {
      /** @description Associated project details */
      project?: {
        /**
         * Format: uuid
         * @description Project UUID
         */
        id: string;
        /**
         * @description Project name
         * @example Website Redesign
         */
        name: string;
      } | null;
      /** @description Assigned user details */
      assignee?: {
        /**
         * Format: uuid
         * @description User UUID
         */
        id: string;
        /**
         * @description User display name
         * @example John Doe
         */
        name: string | null;
      } | null;
      creator?: components['schemas']['UserRef'];
      /** @description Associated tags */
      tags?: {
        tag: components['schemas']['TagRef'];
      }[];
    };
    /** @description Creator user details */
    UserRef: {
      /**
       * Format: uuid
       * @description User UUID
       */
      id: string;
      /**
       * @description User display name
       * @example John Doe
       */
      name: string | null;
    };
    TagRef: {
      /**
       * Format: uuid
       * @description Tag UUID
       */
      id: string;
      /**
       * @description Tag name
       * @example Work
       */
      name: string;
      /**
       * @description Tag color hex code
       * @example #3B82F6
       */
      color: string | null;
    };
    Task: {
      /**
       * Format: uuid
       * @description Task UUID
       */
      id: string;
      /**
       * @description Task title
       * @example Review pull request
       */
      title: string;
      /**
       * @description Task description
       * @example Review the authentication changes in PR #123
       */
      description: string | null;
      /**
       * @description Task status
       * @example pending
       * @enum {string}
       */
      status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
      /**
       * @description Task priority level
       * @example medium
       * @enum {string}
       */
      priority: 'low' | 'medium' | 'high' | 'urgent';
      /**
       * Format: date-time
       * @description Task deadline
       * @example 2025-01-15T17:00:00Z
       */
      deadline: string | null;
      /**
       * @description Estimated time to complete in minutes
       * @example 30
       */
      estimatedMinutes: number | null;
      /**
       * Format: uuid
       * @description Associated project UUID
       */
      projectId: string | null;
      /**
       * Format: uuid
       * @description Assigned user UUID
       */
      assigneeId: string | null;
      /**
       * Format: uuid
       * @description Creator user UUID
       */
      creatorId: string;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-09T12:00:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example 2025-01-09T12:00:00Z
       */
      updatedAt: string;
    };
    ValidationError: {
      /** @enum {string} */
      error: 'Validation error';
      details: {
        /** @description Field that failed validation */
        field: string;
        /** @description Validation error message */
        message: string;
      }[];
    };
    CreateTaskRequest: {
      /**
       * @description Task title
       * @example Review pull request
       */
      title: string;
      /**
       * @description Task description
       * @example Review the authentication changes in PR #123
       */
      description?: string;
      /**
       * @description Initial task status
       * @default pending
       * @example pending
       * @enum {string}
       */
      status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
      /**
       * @description Task priority
       * @default medium
       * @example medium
       * @enum {string}
       */
      priority: 'low' | 'medium' | 'high' | 'urgent';
      /**
       * Format: date-time
       * @description Task deadline (ISO 8601)
       * @example 2025-01-15T17:00:00Z
       */
      deadline?: string | null;
      /**
       * @description Estimated time to complete in minutes
       * @example 30
       */
      estimatedMinutes?: number;
      /**
       * Format: uuid
       * @description Associated project UUID
       */
      projectId?: string;
      /**
       * Format: uuid
       * @description Assigned user UUID
       */
      assigneeId?: string;
      /** @description Tag UUIDs to associate with the task */
      tagIds?: string[];
    };
    /** @description Task dependencies response */
    TaskDependenciesResponse: {
      data: components['schemas']['Task'][];
      /** @description Total number of items */
      total?: number;
    };
    /** @description Task list response */
    TaskListResponse: {
      data: components['schemas']['TaskWithRelations'][];
      /** @description Total number of items */
      total?: number;
    };
    UpdateTaskRequest: {
      /**
       * @description Task title
       * @example Review pull request
       */
      title?: string;
      /** @description Task description (null to clear) */
      description?: string | null;
      /**
       * @description Task status
       * @example pending
       * @enum {string}
       */
      status?: 'pending' | 'in_progress' | 'completed' | 'cancelled';
      /**
       * @description Task priority
       * @example medium
       * @enum {string}
       */
      priority?: 'low' | 'medium' | 'high' | 'urgent';
      /**
       * Format: date-time
       * @description Task deadline (ISO 8601, null to clear)
       */
      deadline?: string | null;
      /** @description Estimated time in minutes (null to clear) */
      estimatedMinutes?: number | null;
      /**
       * Format: uuid
       * @description Associated project UUID (null to clear)
       */
      projectId?: string | null;
      /**
       * Format: uuid
       * @description Assigned user UUID (null to clear)
       */
      assigneeId?: string | null;
      /** @description Tag UUIDs (replaces existing tags) */
      tagIds?: string[];
    };
    /** @description Project response */
    ProjectResponse: {
      data: components['schemas']['ProjectWithRelations'];
    };
    ProjectWithRelations: components['schemas']['Project'] & {
      /** @description Parent initiative details */
      initiative?: {
        /**
         * Format: uuid
         * @description Initiative UUID
         */
        id: string;
        /**
         * @description Initiative name
         * @example Q1 Goals
         */
        name: string;
        /**
         * @description Initiative status
         * @example active
         * @enum {string}
         */
        status: 'draft' | 'active' | 'completed' | 'archived';
      } | null;
      owner?: components['schemas']['UserRef'] & unknown;
      /** @description Number of tasks in the project */
      taskCount?: number;
    };
    Project: {
      /**
       * Format: uuid
       * @description Project UUID
       */
      id: string;
      /**
       * @description Project name
       * @example Website Redesign
       */
      name: string;
      /**
       * @description Project description
       * @example Complete redesign of the marketing website
       */
      description: string | null;
      /**
       * @description Project status
       * @example active
       * @enum {string}
       */
      status: 'planning' | 'active' | 'on_hold' | 'completed' | 'cancelled';
      /**
       * Format: date-time
       * @description Project deadline
       * @example 2025-03-01T00:00:00Z
       */
      deadline: string | null;
      /**
       * Format: uuid
       * @description Parent initiative UUID
       */
      initiativeId: string | null;
      /**
       * Format: uuid
       * @description Owner user UUID
       */
      ownerId: string;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-09T12:00:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example 2025-01-09T12:00:00Z
       */
      updatedAt: string;
    };
    CreateProjectRequest: {
      /**
       * @description Project name
       * @example Website Redesign
       */
      name: string;
      /** @description Project description */
      description?: string;
      /**
       * @description Initial project status
       * @default planning
       * @example active
       * @enum {string}
       */
      status: 'planning' | 'active' | 'on_hold' | 'completed' | 'cancelled';
      /**
       * Format: date-time
       * @description Project deadline (ISO 8601)
       * @example 2025-03-01T00:00:00Z
       */
      deadline?: string | null;
      /**
       * Format: uuid
       * @description Parent initiative UUID
       */
      initiativeId?: string;
    };
    /** @description Project dependencies response */
    ProjectDependenciesResponse: {
      data: components['schemas']['ProjectDependency'][];
      /** @description Total number of items */
      total?: number;
    };
    ProjectDependency: {
      /**
       * Format: uuid
       * @description Dependency UUID
       */
      id: string;
      /**
       * Format: uuid
       * @description Project UUID
       */
      projectId: string;
      /**
       * Format: uuid
       * @description Depends on project UUID
       */
      dependsOnProjectId: string;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-09T12:00:00Z
       */
      createdAt: string;
    };
    /** @description Project list response */
    ProjectListResponse: {
      data: components['schemas']['ProjectWithRelations'][];
      /** @description Total number of items */
      total?: number;
    };
    UpdateProjectRequest: {
      /** @description Project name */
      name?: string;
      /** @description Project description (null to clear) */
      description?: string | null;
      /**
       * @description Project status
       * @example active
       * @enum {string}
       */
      status?: 'planning' | 'active' | 'on_hold' | 'completed' | 'cancelled';
      /**
       * Format: date-time
       * @description Project deadline (null to clear)
       */
      deadline?: string | null;
      /**
       * Format: uuid
       * @description Parent initiative UUID (null to clear)
       */
      initiativeId?: string | null;
    };
    /** @description Event participant response */
    EventParticipantResponse: {
      data: components['schemas']['EventParticipantWithUser'];
    };
    EventParticipantWithUser: components['schemas']['EventParticipant'] & {
      user?: components['schemas']['UserRef'] & unknown;
    };
    EventParticipant: {
      /**
       * Format: uuid
       * @description Participant record UUID
       */
      id: string;
      /**
       * Format: uuid
       * @description Event UUID
       */
      eventId: string;
      /**
       * Format: uuid
       * @description User UUID
       */
      userId: string;
      /**
       * @description Event participant RSVP status
       * @example accepted
       * @enum {string}
       */
      status: 'pending' | 'accepted' | 'declined' | 'tentative';
      /**
       * Format: date-time
       * @description When participant was added
       * @example 2025-01-09T12:00:00Z
       */
      createdAt: string;
    };
    AddParticipantRequest: {
      /**
       * Format: uuid
       * @description User UUID to add as participant
       */
      userId: string;
    };
    /** @description Event response */
    EventResponse: {
      data: components['schemas']['EventWithRelations'];
    };
    EventWithRelations: components['schemas']['Event'] & {
      creator?: components['schemas']['UserRef'] & unknown;
      /** @description Event participants with user details */
      participants?: components['schemas']['EventParticipantWithUser'][];
    };
    Event: {
      /**
       * Format: uuid
       * @description Event UUID
       */
      id: string;
      /**
       * @description Event title
       * @example Team Standup
       */
      title: string;
      /**
       * @description Event description
       * @example Daily standup meeting for the engineering team
       */
      description: string | null;
      /**
       * Format: date-time
       * @description Event start time
       * @example 2025-01-10T09:00:00Z
       */
      startTime: string;
      /**
       * Format: date-time
       * @description Event end time
       * @example 2025-01-10T09:30:00Z
       */
      endTime: string | null;
      /**
       * @description Whether this is an all-day event
       * @example false
       */
      isAllDay: boolean;
      /**
       * @description Event location
       * @example Conference Room A
       */
      location: string | null;
      /**
       * @description iCalendar RRULE for recurring events
       * @example FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR
       */
      recurrenceRule: string | null;
      /**
       * Format: uuid
       * @description Event creator user UUID
       */
      creatorId: string;
      /**
       * @description Event source (local or synced from external calendar)
       * @example local
       * @enum {string}
       */
      source: 'local' | 'external';
      /**
       * Format: uuid
       * @description Integration ID if event is from external source
       */
      sourceIntegrationId: string | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-09T12:00:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example 2025-01-09T12:00:00Z
       */
      updatedAt: string;
    };
    CreateEventRequest: {
      /**
       * @description Event title
       * @example Team Standup
       */
      title: string;
      /** @description Event description */
      description?: string;
      /**
       * Format: date-time
       * @description Event start time (ISO 8601)
       * @example 2025-01-10T09:00:00Z
       */
      startTime: string | null;
      /**
       * Format: date-time
       * @description Event end time (ISO 8601)
       * @example 2025-01-10T09:30:00Z
       */
      endTime?: string | null;
      /**
       * @description Whether this is an all-day event
       * @default false
       */
      isAllDay: boolean;
      /** @description Event location */
      location?: string;
      /** @description iCalendar RRULE for recurring events */
      recurrenceRule?: string;
      /** @description User UUIDs to add as participants */
      participantIds?: string[];
    };
    /** @description Event list response */
    EventListResponse: {
      data: components['schemas']['EventWithRelations'][];
      /** @description Total number of items */
      total?: number;
    };
    UpdateEventRequest: {
      /** @description Event title */
      title?: string;
      /** @description Event description (null to clear) */
      description?: string | null;
      /**
       * Format: date-time
       * @description Event start time (ISO 8601)
       */
      startTime?: string | null;
      /**
       * Format: date-time
       * @description Event end time (null to clear)
       */
      endTime?: string | null;
      /** @description Whether this is an all-day event */
      isAllDay?: boolean;
      /** @description Event location (null to clear) */
      location?: string | null;
      /** @description Recurrence rule (null to clear) */
      recurrenceRule?: string | null;
    };
    UpdateParticipantStatusRequest: {
      /**
       * @description New RSVP status
       * @example accepted
       * @enum {string}
       */
      status: 'pending' | 'accepted' | 'declined' | 'tentative';
    };
    /** @description Initiative response */
    InitiativeResponse: {
      data: components['schemas']['InitiativeWithRelations'];
    };
    InitiativeWithRelations: components['schemas']['Initiative'] & {
      /** @description Parent initiative details */
      parent?: {
        /**
         * Format: uuid
         * @description Initiative UUID
         */
        id: string;
        /**
         * @description Initiative name
         * @example Q1 Goals
         */
        name: string;
        /**
         * @description Initiative status
         * @example active
         * @enum {string}
         */
        status: 'draft' | 'active' | 'completed' | 'archived';
      } | null;
      owner?: components['schemas']['UserRef'] & unknown;
      /** @description Child initiative summaries */
      children?: components['schemas']['InitiativeRefDetailed'][];
      /** @description Number of projects in this initiative */
      projectCount?: number;
    };
    InitiativeRefDetailed: {
      /**
       * Format: uuid
       * @description Initiative UUID
       */
      id: string;
      /**
       * @description Initiative name
       * @example Q1 Goals
       */
      name: string;
      /**
       * @description Initiative status
       * @example active
       * @enum {string}
       */
      status: 'draft' | 'active' | 'completed' | 'archived';
    };
    Initiative: {
      /**
       * Format: uuid
       * @description Initiative UUID
       */
      id: string;
      /**
       * @description Initiative name
       * @example Q1 2025 Goals
       */
      name: string;
      /**
       * @description Initiative description
       * @example Key objectives for the first quarter
       */
      description: string | null;
      /**
       * @description Initiative status
       * @example active
       * @enum {string}
       */
      status: 'draft' | 'active' | 'completed' | 'archived';
      /**
       * Format: uuid
       * @description Parent initiative UUID for hierarchical initiatives
       */
      parentId: string | null;
      /**
       * Format: uuid
       * @description Owner user UUID
       */
      ownerId: string;
      /**
       * Format: date-time
       * @description Soft delete timestamp
       * @example 2025-01-09T12:00:00Z
       */
      deletedAt: string | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-09T12:00:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example 2025-01-09T12:00:00Z
       */
      updatedAt: string;
    };
    CreateInitiativeRequest: {
      /**
       * @description Initiative name
       * @example Q1 2025 Goals
       */
      name: string;
      /** @description Initiative description */
      description?: string;
      /**
       * @description Initial initiative status
       * @default draft
       * @example active
       * @enum {string}
       */
      status: 'draft' | 'active' | 'completed' | 'archived';
      /**
       * Format: uuid
       * @description Parent initiative UUID for hierarchical initiatives
       */
      parentId?: string;
    };
    /** @description Initiative list response */
    InitiativeListResponse: {
      data: components['schemas']['InitiativeWithRelations'][];
      /** @description Total number of items */
      total?: number;
    };
    UpdateInitiativeRequest: {
      /** @description Initiative name */
      name?: string;
      /** @description Initiative description (null to clear) */
      description?: string | null;
      /**
       * @description Initiative status
       * @example active
       * @enum {string}
       */
      status?: 'draft' | 'active' | 'completed' | 'archived';
      /**
       * Format: uuid
       * @description Parent initiative UUID (null to clear)
       */
      parentId?: string | null;
    };
    /** @description Time block response */
    TimeBlockResponse: {
      data: components['schemas']['TimeBlockWithTasks'];
    };
    TimeBlockWithTasks: components['schemas']['TimeBlock'] & {
      /** @description Tasks linked to this time block with their positions */
      linkedTasks?: components['schemas']['LinkedTask'][];
    };
    LinkedTask: components['schemas']['Task'] & {
      /**
       * @description Task position within the time block
       * @example 0
       */
      position: number;
    };
    TimeBlock: {
      /**
       * Format: uuid
       * @description Time block UUID
       */
      id: string;
      /**
       * @description Time block label
       * @example Focus Time
       */
      label: string;
      /**
       * @description Time block description
       * @example Deep work session for coding
       */
      description: string | null;
      /**
       * Format: date-time
       * @description Block start time
       * @example 2025-01-10T09:00:00Z
       */
      startTime: string;
      /**
       * Format: date-time
       * @description Block end time
       * @example 2025-01-10T11:00:00Z
       */
      endTime: string;
      /**
       * @description Block color hex code
       * @example #3B82F6
       */
      color: string | null;
      /**
       * @description iCalendar RRULE for recurring time blocks
       * @example FREQ=WEEKLY;BYDAY=MO,WE,FR
       */
      recurrenceRule: string | null;
      /**
       * Format: uuid
       * @description Owner user UUID
       */
      ownerId: string;
      /**
       * Format: date-time
       * @description Soft delete timestamp
       * @example 2025-01-09T12:00:00Z
       */
      deletedAt: string | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-09T12:00:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example 2025-01-09T12:00:00Z
       */
      updatedAt: string;
    };
    CreateTimeBlockRequest: {
      /**
       * @description Time block label
       * @example Focus Time
       */
      label: string;
      /** @description Time block description */
      description?: string;
      /**
       * Format: date-time
       * @description Block start time (ISO 8601)
       * @example 2025-01-10T09:00:00Z
       */
      startTime: string | null;
      /**
       * Format: date-time
       * @description Block end time (ISO 8601)
       * @example 2025-01-10T11:00:00Z
       */
      endTime: string | null;
      /**
       * @description Block color hex code
       * @example #3B82F6
       */
      color?: string;
      /** @description iCalendar RRULE for recurring time blocks */
      recurrenceRule?: string;
      /** @description Task UUIDs to link to this time block */
      taskIds?: string[];
    };
    LinkTaskRequest: {
      /**
       * Format: uuid
       * @description Task UUID to link
       */
      taskId: string;
      /** @description Position in the task list (defaults to end) */
      position?: number;
    };
    /** @description Time block list response */
    TimeBlockListResponse: {
      data: components['schemas']['TimeBlockWithTasks'][];
      /** @description Total number of items */
      total?: number;
    };
    ReorderTasksRequest: {
      /** @description Task UUIDs in desired order */
      taskIds: string[];
    };
    UpdateTimeBlockRequest: {
      /** @description Time block label */
      label?: string;
      /** @description Time block description (null to clear) */
      description?: string | null;
      /**
       * Format: date-time
       * @description Block start time (ISO 8601)
       */
      startTime?: string | null;
      /**
       * Format: date-time
       * @description Block end time (ISO 8601)
       */
      endTime?: string | null;
      /** @description Block color (null to clear) */
      color?: string | null;
      /** @description Recurrence rule (null to clear) */
      recurrenceRule?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
