/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/tasks/{id}/tags/{tagId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add tag to task
     * @description Associate a tag with a task.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
          /** @description Tag UUID */
          tagId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Tag added to task successfully */
        201: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task or tag not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    /**
     * Remove tag from task
     * @description Remove a tag association from a task.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
          /** @description Tag UUID */
          tagId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Tag removed from task successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task or tag not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tasks/{id}/dependencies/{dependsOnId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add task dependency
     * @description Add a dependency relationship between two tasks.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
          /** @description Dependency task UUID */
          dependsOnId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dependency added successfully */
        201: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Invalid dependency (e.g., circular dependency) */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    /**
     * Remove task dependency
     * @description Remove a dependency relationship between two tasks.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
          /** @description Dependency task UUID */
          dependsOnId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dependency removed successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task or dependency not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tasks/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List tasks
     * @description Retrieve a list of tasks with optional filtering and pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by project */
          projectId?: string;
          /** @description Filter by status */
          status?: 'pending' | 'in_progress' | 'completed' | 'cancelled';
          /** @description Filter by priority */
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          /** @description Maximum number of tasks to return */
          limit?: number;
          /** @description Number of tasks to skip */
          offset?: number | null;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Tasks retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskListResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a task
     * @description Create a new task.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateTaskRequest'];
        };
      };
      responses: {
        /** @description Task created successfully */
        201: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tasks/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a task
     * @description Retrieve a single task by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Task retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a task
     * @description Delete a task by its ID.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Task deleted successfully */
        204: {
          headers: Record<string, unknown>;
          content?: never;
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a task
     * @description Update an existing task. Only provided fields will be updated.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateTaskRequest'];
        };
      };
      responses: {
        /** @description Task updated successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/tasks/{id}/dependencies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get task dependencies
     * @description Retrieve all tasks that this task depends on.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task UUID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dependencies retrieved successfully */
        200: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['TaskDependenciesResponse'];
          };
        };
        /** @description Authentication required */
        401: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Task not found */
        404: {
          headers: Record<string, unknown>;
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UnauthorizedError: {
      /** @enum {string} */
      error: 'Unauthorized';
      /** @default Authentication required */
      message: string;
    };
    NotFoundError: {
      /** @enum {string} */
      error: 'Not found';
      /** @description Resource description */
      message?: string;
    };
    ErrorResponse: {
      /** @description Error type or code */
      error: string;
      /** @description Human-readable error message */
      message?: string;
      /** @description Additional error details */
      details?: Record<string, unknown>;
    };
    /** @description Task response */
    TaskResponse: {
      data: components['schemas']['TaskWithRelations'];
    };
    TaskWithRelations: components['schemas']['Task'] & {
      /** @description Associated project details */
      project?: {
        /**
         * Format: uuid
         * @description Project UUID
         */
        id: string;
        /**
         * @description Project name
         * @example Website Redesign
         */
        name: string;
      } | null;
      /** @description Assigned user details */
      assignee?: {
        /**
         * Format: uuid
         * @description User UUID
         */
        id: string;
        /**
         * @description User display name
         * @example John Doe
         */
        name: string | null;
      } | null;
      creator?: components['schemas']['UserRef'];
      /** @description Associated tags */
      tags?: {
        tag: components['schemas']['TagRef'];
      }[];
    };
    /** @description Creator user details */
    UserRef: {
      /**
       * Format: uuid
       * @description User UUID
       */
      id: string;
      /**
       * @description User display name
       * @example John Doe
       */
      name: string | null;
    };
    TagRef: {
      /**
       * Format: uuid
       * @description Tag UUID
       */
      id: string;
      /**
       * @description Tag name
       * @example Work
       */
      name: string;
      /**
       * @description Tag color hex code
       * @example #3B82F6
       */
      color: string | null;
    };
    Task: {
      /**
       * Format: uuid
       * @description Task UUID
       */
      id: string;
      /**
       * @description Task title
       * @example Review pull request
       */
      title: string;
      /**
       * @description Task description
       * @example Review the authentication changes in PR #123
       */
      description: string | null;
      /**
       * @description Task status
       * @example pending
       * @enum {string}
       */
      status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
      /**
       * @description Task priority level
       * @example medium
       * @enum {string}
       */
      priority: 'low' | 'medium' | 'high' | 'urgent';
      /**
       * Format: date-time
       * @description Task deadline
       * @example 2025-01-15T17:00:00Z
       */
      deadline: string | null;
      /**
       * @description Estimated time to complete in minutes
       * @example 30
       */
      estimatedMinutes: number | null;
      /**
       * Format: uuid
       * @description Associated project UUID
       */
      projectId: string | null;
      /**
       * Format: uuid
       * @description Assigned user UUID
       */
      assigneeId: string | null;
      /**
       * Format: uuid
       * @description Creator user UUID
       */
      creatorId: string;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-09T12:00:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example 2025-01-09T12:00:00Z
       */
      updatedAt: string;
    };
    ValidationError: {
      /** @enum {string} */
      error: 'Validation error';
      details: {
        /** @description Field that failed validation */
        field: string;
        /** @description Validation error message */
        message: string;
      }[];
    };
    CreateTaskRequest: {
      /**
       * @description Task title
       * @example Review pull request
       */
      title: string;
      /**
       * @description Task description
       * @example Review the authentication changes in PR #123
       */
      description?: string;
      /**
       * @description Initial task status
       * @default pending
       * @example pending
       * @enum {string}
       */
      status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
      /**
       * @description Task priority
       * @default medium
       * @example medium
       * @enum {string}
       */
      priority: 'low' | 'medium' | 'high' | 'urgent';
      /**
       * Format: date-time
       * @description Task deadline (ISO 8601)
       * @example 2025-01-15T17:00:00Z
       */
      deadline?: string | null;
      /**
       * @description Estimated time to complete in minutes
       * @example 30
       */
      estimatedMinutes?: number;
      /**
       * Format: uuid
       * @description Associated project UUID
       */
      projectId?: string;
      /**
       * Format: uuid
       * @description Assigned user UUID
       */
      assigneeId?: string;
      /** @description Tag UUIDs to associate with the task */
      tagIds?: string[];
    };
    /** @description Task dependencies response */
    TaskDependenciesResponse: {
      data: components['schemas']['Task'][];
      /** @description Total number of items */
      total?: number;
    };
    /** @description Task list response */
    TaskListResponse: {
      data: components['schemas']['TaskWithRelations'][];
      /** @description Total number of items */
      total?: number;
    };
    UpdateTaskRequest: {
      /**
       * @description Task title
       * @example Review pull request
       */
      title?: string;
      /** @description Task description (null to clear) */
      description?: string | null;
      /**
       * @description Task status
       * @example pending
       * @enum {string}
       */
      status?: 'pending' | 'in_progress' | 'completed' | 'cancelled';
      /**
       * @description Task priority
       * @example medium
       * @enum {string}
       */
      priority?: 'low' | 'medium' | 'high' | 'urgent';
      /**
       * Format: date-time
       * @description Task deadline (ISO 8601, null to clear)
       */
      deadline?: string | null;
      /** @description Estimated time in minutes (null to clear) */
      estimatedMinutes?: number | null;
      /**
       * Format: uuid
       * @description Associated project UUID (null to clear)
       */
      projectId?: string | null;
      /**
       * Format: uuid
       * @description Assigned user UUID (null to clear)
       */
      assigneeId?: string | null;
      /** @description Tag UUIDs (replaces existing tags) */
      tagIds?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
