/** Versioned IANA/CLDR search metadata snapshot generated from Node 24 ICU on 2026-08-10. */
export const TIMEZONE_INDEX_VERSION = '2026-08-10-node-24-icu' as const;

/** Stable searchable metadata for one canonical IANA timezone. */
export interface TimezoneIndexRecord {
  readonly id: string;
  readonly city: string;
  readonly commonName: string;
  readonly abbreviations: readonly string[];
}

/** Checked-in IANA/CLDR search catalog; runtime formatting supplies only current offset and code. */
export const TIMEZONE_INDEX: readonly TimezoneIndexRecord[] = [
  {
    id: 'UTC',
    city: 'UTC',
    commonName: 'Coordinated Universal Time',
    abbreviations: ['UTC'],
  },
  {
    id: 'Africa/Abidjan',
    city: 'Abidjan',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Accra',
    city: 'Accra',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Addis_Ababa',
    city: 'Addis Ababa',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Africa/Algiers',
    city: 'Algiers',
    commonName: 'Central European Standard Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Asmera',
    city: 'Asmera',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Africa/Bamako',
    city: 'Bamako',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Bangui',
    city: 'Bangui',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Banjul',
    city: 'Banjul',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Bissau',
    city: 'Bissau',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Blantyre',
    city: 'Blantyre',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Brazzaville',
    city: 'Brazzaville',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Bujumbura',
    city: 'Bujumbura',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Cairo',
    city: 'Cairo',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Africa/Casablanca',
    city: 'Casablanca',
    commonName: 'Morocco Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Ceuta',
    city: 'Ceuta',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Africa/Conakry',
    city: 'Conakry',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Dakar',
    city: 'Dakar',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Dar_es_Salaam',
    city: 'Dar es Salaam',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Africa/Djibouti',
    city: 'Djibouti',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Africa/Douala',
    city: 'Douala',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/El_Aaiun',
    city: 'El Aaiun',
    commonName: 'Western Sahara Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Freetown',
    city: 'Freetown',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Gaborone',
    city: 'Gaborone',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Harare',
    city: 'Harare',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Johannesburg',
    city: 'Johannesburg',
    commonName: 'South Africa Standard Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Juba',
    city: 'Juba',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Kampala',
    city: 'Kampala',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Africa/Khartoum',
    city: 'Khartoum',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Kigali',
    city: 'Kigali',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Kinshasa',
    city: 'Kinshasa',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Lagos',
    city: 'Lagos',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Libreville',
    city: 'Libreville',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Lome',
    city: 'Lome',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Luanda',
    city: 'Luanda',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Lubumbashi',
    city: 'Lubumbashi',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Lusaka',
    city: 'Lusaka',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Malabo',
    city: 'Malabo',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Maputo',
    city: 'Maputo',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Maseru',
    city: 'Maseru',
    commonName: 'South Africa Standard Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Mbabane',
    city: 'Mbabane',
    commonName: 'South Africa Standard Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Mogadishu',
    city: 'Mogadishu',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Africa/Monrovia',
    city: 'Monrovia',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Nairobi',
    city: 'Nairobi',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Africa/Ndjamena',
    city: 'Ndjamena',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Niamey',
    city: 'Niamey',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Nouakchott',
    city: 'Nouakchott',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Ouagadougou',
    city: 'Ouagadougou',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Porto-Novo',
    city: 'Porto-Novo',
    commonName: 'West Africa Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Sao_Tome',
    city: 'Sao Tome',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Africa/Tripoli',
    city: 'Tripoli',
    commonName: 'Eastern European Standard Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Africa/Tunis',
    city: 'Tunis',
    commonName: 'Central European Standard Time',
    abbreviations: ['GMT+1'],
  },
  {
    id: 'Africa/Windhoek',
    city: 'Windhoek',
    commonName: 'Central Africa Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'America/Adak',
    city: 'Adak',
    commonName: 'Hawaii-Aleutian Time',
    abbreviations: ['HAST', 'HADT'],
  },
  {
    id: 'America/Anchorage',
    city: 'Anchorage',
    commonName: 'Alaska Time',
    abbreviations: ['AKST', 'AKDT'],
  },
  {
    id: 'America/Anguilla',
    city: 'Anguilla',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Antigua',
    city: 'Antigua',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Araguaina',
    city: 'Araguaina',
    commonName: 'Brasilia Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Argentina/La_Rioja',
    city: 'La Rioja',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Argentina/Rio_Gallegos',
    city: 'Rio Gallegos',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Argentina/Salta',
    city: 'Salta',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Argentina/San_Juan',
    city: 'San Juan',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Argentina/San_Luis',
    city: 'San Luis',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Argentina/Tucuman',
    city: 'Tucuman',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Argentina/Ushuaia',
    city: 'Ushuaia',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Aruba',
    city: 'Aruba',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Asuncion',
    city: 'Asuncion',
    commonName: 'Paraguay Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Bahia',
    city: 'Bahia',
    commonName: 'Brasilia Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Bahia_Banderas',
    city: 'Bahia Banderas',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Barbados',
    city: 'Barbados',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Belem',
    city: 'Belem',
    commonName: 'Brasilia Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Belize',
    city: 'Belize',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Blanc-Sablon',
    city: 'Blanc-Sablon',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Boa_Vista',
    city: 'Boa Vista',
    commonName: 'Amazon Standard Time',
    abbreviations: ['GMT-4'],
  },
  {
    id: 'America/Bogota',
    city: 'Bogota',
    commonName: 'Colombia Standard Time',
    abbreviations: ['GMT-5'],
  },
  {
    id: 'America/Boise',
    city: 'Boise',
    commonName: 'Mountain Time',
    abbreviations: ['MST', 'MDT'],
  },
  {
    id: 'America/Buenos_Aires',
    city: 'Buenos Aires',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Cambridge_Bay',
    city: 'Cambridge Bay',
    commonName: 'Mountain Time',
    abbreviations: ['MST', 'MDT'],
  },
  {
    id: 'America/Campo_Grande',
    city: 'Campo Grande',
    commonName: 'Amazon Standard Time',
    abbreviations: ['GMT-4'],
  },
  {
    id: 'America/Cancun',
    city: 'Cancun',
    commonName: 'Eastern Standard Time',
    abbreviations: ['EST'],
  },
  {
    id: 'America/Caracas',
    city: 'Caracas',
    commonName: 'Venezuela Time',
    abbreviations: ['GMT-4'],
  },
  {
    id: 'America/Catamarca',
    city: 'Catamarca',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Cayenne',
    city: 'Cayenne',
    commonName: 'French Guiana Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Cayman',
    city: 'Cayman',
    commonName: 'Eastern Standard Time',
    abbreviations: ['EST'],
  },
  {
    id: 'America/Chicago',
    city: 'Chicago',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT', 'Central Time'],
  },
  {
    id: 'America/Chihuahua',
    city: 'Chihuahua',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Ciudad_Juarez',
    city: 'Ciudad Juarez',
    commonName: 'Mountain Time',
    abbreviations: ['MST', 'MDT'],
  },
  {
    id: 'America/Coral_Harbour',
    city: 'Coral Harbour',
    commonName: 'Eastern Standard Time',
    abbreviations: ['EST'],
  },
  {
    id: 'America/Cordoba',
    city: 'Cordoba',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Costa_Rica',
    city: 'Costa Rica',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Coyhaique',
    city: 'Coyhaique',
    commonName: 'Coyhaique Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Creston',
    city: 'Creston',
    commonName: 'Mountain Standard Time',
    abbreviations: ['MST'],
  },
  {
    id: 'America/Cuiaba',
    city: 'Cuiaba',
    commonName: 'Amazon Standard Time',
    abbreviations: ['GMT-4'],
  },
  {
    id: 'America/Curacao',
    city: 'Curacao',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Danmarkshavn',
    city: 'Danmarkshavn',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'America/Dawson',
    city: 'Dawson',
    commonName: 'Yukon Time',
    abbreviations: ['GMT-7'],
  },
  {
    id: 'America/Dawson_Creek',
    city: 'Dawson Creek',
    commonName: 'Mountain Standard Time',
    abbreviations: ['MST'],
  },
  {
    id: 'America/Denver',
    city: 'Denver',
    commonName: 'Mountain Time',
    abbreviations: ['MST', 'MDT', 'Mountain Time'],
  },
  {
    id: 'America/Detroit',
    city: 'Detroit',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Dominica',
    city: 'Dominica',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Edmonton',
    city: 'Edmonton',
    commonName: 'Mountain Time',
    abbreviations: ['MST', 'MDT'],
  },
  {
    id: 'America/Eirunepe',
    city: 'Eirunepe',
    commonName: 'Acre Standard Time',
    abbreviations: ['GMT-5'],
  },
  {
    id: 'America/El_Salvador',
    city: 'El Salvador',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Fort_Nelson',
    city: 'Fort Nelson',
    commonName: 'Mountain Standard Time',
    abbreviations: ['MST'],
  },
  {
    id: 'America/Fortaleza',
    city: 'Fortaleza',
    commonName: 'Brasilia Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Glace_Bay',
    city: 'Glace Bay',
    commonName: 'Atlantic Time',
    abbreviations: ['AST', 'ADT'],
  },
  {
    id: 'America/Godthab',
    city: 'Godthab',
    commonName: 'Greenland Time',
    abbreviations: ['GMT-2', 'GMT-1'],
  },
  {
    id: 'America/Goose_Bay',
    city: 'Goose Bay',
    commonName: 'Atlantic Time',
    abbreviations: ['AST', 'ADT'],
  },
  {
    id: 'America/Grand_Turk',
    city: 'Grand Turk',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Grenada',
    city: 'Grenada',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Guadeloupe',
    city: 'Guadeloupe',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Guatemala',
    city: 'Guatemala',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Guayaquil',
    city: 'Guayaquil',
    commonName: 'Ecuador Time',
    abbreviations: ['GMT-5'],
  },
  {
    id: 'America/Guyana',
    city: 'Guyana',
    commonName: 'Guyana Time',
    abbreviations: ['GMT-4'],
  },
  {
    id: 'America/Halifax',
    city: 'Halifax',
    commonName: 'Atlantic Time',
    abbreviations: ['AST', 'ADT'],
  },
  {
    id: 'America/Havana',
    city: 'Havana',
    commonName: 'Cuba Time',
    abbreviations: ['GMT-5', 'GMT-4'],
  },
  {
    id: 'America/Hermosillo',
    city: 'Hermosillo',
    commonName: 'Mexican Pacific Standard Time',
    abbreviations: ['GMT-7'],
  },
  {
    id: 'America/Indiana/Knox',
    city: 'Knox',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/Indiana/Marengo',
    city: 'Marengo',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Indiana/Petersburg',
    city: 'Petersburg',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Indiana/Tell_City',
    city: 'Tell City',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/Indiana/Vevay',
    city: 'Vevay',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Indiana/Vincennes',
    city: 'Vincennes',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Indiana/Winamac',
    city: 'Winamac',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Indianapolis',
    city: 'Indianapolis',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Inuvik',
    city: 'Inuvik',
    commonName: 'Mountain Time',
    abbreviations: ['MST', 'MDT'],
  },
  {
    id: 'America/Iqaluit',
    city: 'Iqaluit',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Jamaica',
    city: 'Jamaica',
    commonName: 'Eastern Standard Time',
    abbreviations: ['EST'],
  },
  {
    id: 'America/Jujuy',
    city: 'Jujuy',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Juneau',
    city: 'Juneau',
    commonName: 'Alaska Time',
    abbreviations: ['AKST', 'AKDT'],
  },
  {
    id: 'America/Kentucky/Monticello',
    city: 'Monticello',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Kralendijk',
    city: 'Kralendijk',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/La_Paz',
    city: 'La Paz',
    commonName: 'Bolivia Time',
    abbreviations: ['GMT-4'],
  },
  {
    id: 'America/Lima',
    city: 'Lima',
    commonName: 'Peru Standard Time',
    abbreviations: ['GMT-5'],
  },
  {
    id: 'America/Los_Angeles',
    city: 'Los Angeles',
    commonName: 'Pacific Time',
    abbreviations: ['PST', 'PDT', 'Pacific Time'],
  },
  {
    id: 'America/Louisville',
    city: 'Louisville',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Lower_Princes',
    city: 'Lower Princes',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Maceio',
    city: 'Maceio',
    commonName: 'Brasilia Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Managua',
    city: 'Managua',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Manaus',
    city: 'Manaus',
    commonName: 'Amazon Standard Time',
    abbreviations: ['GMT-4'],
  },
  {
    id: 'America/Marigot',
    city: 'Marigot',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Martinique',
    city: 'Martinique',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Matamoros',
    city: 'Matamoros',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/Mazatlan',
    city: 'Mazatlan',
    commonName: 'Mexican Pacific Standard Time',
    abbreviations: ['GMT-7'],
  },
  {
    id: 'America/Mendoza',
    city: 'Mendoza',
    commonName: 'Argentina Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Menominee',
    city: 'Menominee',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/Merida',
    city: 'Merida',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Metlakatla',
    city: 'Metlakatla',
    commonName: 'Alaska Time',
    abbreviations: ['AKST', 'AKDT'],
  },
  {
    id: 'America/Mexico_City',
    city: 'Mexico City',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Miquelon',
    city: 'Miquelon',
    commonName: 'St. Pierre & Miquelon Time',
    abbreviations: ['GMT-3', 'GMT-2'],
  },
  {
    id: 'America/Moncton',
    city: 'Moncton',
    commonName: 'Atlantic Time',
    abbreviations: ['AST', 'ADT'],
  },
  {
    id: 'America/Monterrey',
    city: 'Monterrey',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Montevideo',
    city: 'Montevideo',
    commonName: 'Uruguay Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Montserrat',
    city: 'Montserrat',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Nassau',
    city: 'Nassau',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/New_York',
    city: 'New York',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT', 'Eastern Time'],
  },
  {
    id: 'America/Nome',
    city: 'Nome',
    commonName: 'Alaska Time',
    abbreviations: ['AKST', 'AKDT'],
  },
  {
    id: 'America/Noronha',
    city: 'Noronha',
    commonName: 'Fernando de Noronha Standard Time',
    abbreviations: ['GMT-2'],
  },
  {
    id: 'America/North_Dakota/Beulah',
    city: 'Beulah',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/North_Dakota/Center',
    city: 'Center',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/North_Dakota/New_Salem',
    city: 'New Salem',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/Ojinaga',
    city: 'Ojinaga',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/Panama',
    city: 'Panama',
    commonName: 'Eastern Standard Time',
    abbreviations: ['EST'],
  },
  {
    id: 'America/Paramaribo',
    city: 'Paramaribo',
    commonName: 'Suriname Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Phoenix',
    city: 'Phoenix',
    commonName: 'Mountain Standard Time',
    abbreviations: ['MST'],
  },
  {
    id: 'America/Port-au-Prince',
    city: 'Port-au-Prince',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Port_of_Spain',
    city: 'Port of Spain',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Porto_Velho',
    city: 'Porto Velho',
    commonName: 'Amazon Standard Time',
    abbreviations: ['GMT-4'],
  },
  {
    id: 'America/Puerto_Rico',
    city: 'Puerto Rico',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Punta_Arenas',
    city: 'Punta Arenas',
    commonName: 'Punta Arenas Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Rankin_Inlet',
    city: 'Rankin Inlet',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/Recife',
    city: 'Recife',
    commonName: 'Brasilia Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Regina',
    city: 'Regina',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Resolute',
    city: 'Resolute',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/Rio_Branco',
    city: 'Rio Branco',
    commonName: 'Acre Standard Time',
    abbreviations: ['GMT-5'],
  },
  {
    id: 'America/Santarem',
    city: 'Santarem',
    commonName: 'Brasilia Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Santiago',
    city: 'Santiago',
    commonName: 'Chile Time',
    abbreviations: ['GMT-3', 'GMT-4'],
  },
  {
    id: 'America/Santo_Domingo',
    city: 'Santo Domingo',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Sao_Paulo',
    city: 'Sao Paulo',
    commonName: 'Brasilia Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'America/Scoresbysund',
    city: 'Scoresbysund',
    commonName: 'Greenland Time',
    abbreviations: ['GMT-2', 'GMT-1'],
  },
  {
    id: 'America/Sitka',
    city: 'Sitka',
    commonName: 'Alaska Time',
    abbreviations: ['AKST', 'AKDT'],
  },
  {
    id: 'America/St_Barthelemy',
    city: 'St Barthelemy',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/St_Johns',
    city: 'St Johns',
    commonName: 'Newfoundland Time',
    abbreviations: ['GMT-3:30', 'GMT-2:30'],
  },
  {
    id: 'America/St_Kitts',
    city: 'St Kitts',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/St_Lucia',
    city: 'St Lucia',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/St_Thomas',
    city: 'St Thomas',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/St_Vincent',
    city: 'St Vincent',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Swift_Current',
    city: 'Swift Current',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Tegucigalpa',
    city: 'Tegucigalpa',
    commonName: 'Central Standard Time',
    abbreviations: ['CST'],
  },
  {
    id: 'America/Thule',
    city: 'Thule',
    commonName: 'Atlantic Time',
    abbreviations: ['AST', 'ADT'],
  },
  {
    id: 'America/Tijuana',
    city: 'Tijuana',
    commonName: 'Pacific Time',
    abbreviations: ['PST', 'PDT'],
  },
  {
    id: 'America/Toronto',
    city: 'Toronto',
    commonName: 'Eastern Time',
    abbreviations: ['EST', 'EDT'],
  },
  {
    id: 'America/Tortola',
    city: 'Tortola',
    commonName: 'Atlantic Standard Time',
    abbreviations: ['AST'],
  },
  {
    id: 'America/Vancouver',
    city: 'Vancouver',
    commonName: 'Pacific Time',
    abbreviations: ['PST', 'PDT', 'Pacific Time'],
  },
  {
    id: 'America/Whitehorse',
    city: 'Whitehorse',
    commonName: 'Yukon Time',
    abbreviations: ['GMT-7'],
  },
  {
    id: 'America/Winnipeg',
    city: 'Winnipeg',
    commonName: 'Central Time',
    abbreviations: ['CST', 'CDT'],
  },
  {
    id: 'America/Yakutat',
    city: 'Yakutat',
    commonName: 'Alaska Time',
    abbreviations: ['AKST', 'AKDT'],
  },
  {
    id: 'Antarctica/Casey',
    city: 'Casey',
    commonName: 'Australian Western Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Antarctica/Davis',
    city: 'Davis',
    commonName: 'Davis Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Antarctica/DumontDUrville',
    city: 'DumontDUrville',
    commonName: 'Dumont d’Urville Time',
    abbreviations: ['GMT+10'],
  },
  {
    id: 'Antarctica/Macquarie',
    city: 'Macquarie',
    commonName: 'Australian Eastern Time',
    abbreviations: ['GMT+11', 'GMT+10'],
  },
  {
    id: 'Antarctica/Mawson',
    city: 'Mawson',
    commonName: 'Mawson Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Antarctica/McMurdo',
    city: 'McMurdo',
    commonName: 'New Zealand Time',
    abbreviations: ['GMT+13', 'GMT+12'],
  },
  {
    id: 'Antarctica/Palmer',
    city: 'Palmer',
    commonName: 'Palmer Land Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'Antarctica/Rothera',
    city: 'Rothera',
    commonName: 'Rothera Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'Antarctica/Syowa',
    city: 'Syowa',
    commonName: 'Syowa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Antarctica/Troll',
    city: 'Troll',
    commonName: 'Troll Station Time',
    abbreviations: ['GMT', 'GMT+2'],
  },
  {
    id: 'Antarctica/Vostok',
    city: 'Vostok',
    commonName: 'Vostok Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Arctic/Longyearbyen',
    city: 'Longyearbyen',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Asia/Aden',
    city: 'Aden',
    commonName: 'Arabian Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Asia/Almaty',
    city: 'Almaty',
    commonName: 'Kazakhstan Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Amman',
    city: 'Amman',
    commonName: 'Jordan Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Asia/Anadyr',
    city: 'Anadyr',
    commonName: 'Kamchatka Standard Time',
    abbreviations: ['GMT+12'],
  },
  {
    id: 'Asia/Aqtau',
    city: 'Aqtau',
    commonName: 'Kazakhstan Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Aqtobe',
    city: 'Aqtobe',
    commonName: 'Kazakhstan Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Ashgabat',
    city: 'Ashgabat',
    commonName: 'Turkmenistan Standard Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Atyrau',
    city: 'Atyrau',
    commonName: 'Kazakhstan Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Baghdad',
    city: 'Baghdad',
    commonName: 'Arabian Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Asia/Bahrain',
    city: 'Bahrain',
    commonName: 'Arabian Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Asia/Baku',
    city: 'Baku',
    commonName: 'Azerbaijan Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Asia/Bangkok',
    city: 'Bangkok',
    commonName: 'Indochina Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Barnaul',
    city: 'Barnaul',
    commonName: 'Krasnoyarsk Standard Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Beirut',
    city: 'Beirut',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Asia/Bishkek',
    city: 'Bishkek',
    commonName: 'Kyrgyzstan Time',
    abbreviations: ['GMT+6'],
  },
  {
    id: 'Asia/Brunei',
    city: 'Brunei',
    commonName: 'Brunei Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Calcutta',
    city: 'Calcutta',
    commonName: 'India Standard Time',
    abbreviations: ['GMT+5:30'],
  },
  {
    id: 'Asia/Chita',
    city: 'Chita',
    commonName: 'Yakutsk Standard Time',
    abbreviations: ['GMT+9'],
  },
  {
    id: 'Asia/Colombo',
    city: 'Colombo',
    commonName: 'India Standard Time',
    abbreviations: ['GMT+5:30'],
  },
  {
    id: 'Asia/Damascus',
    city: 'Damascus',
    commonName: 'Syria Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Asia/Dhaka',
    city: 'Dhaka',
    commonName: 'Bangladesh Standard Time',
    abbreviations: ['GMT+6'],
  },
  {
    id: 'Asia/Dili',
    city: 'Dili',
    commonName: 'Timor-Leste Time',
    abbreviations: ['GMT+9'],
  },
  {
    id: 'Asia/Dubai',
    city: 'Dubai',
    commonName: 'Gulf Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Asia/Dushanbe',
    city: 'Dushanbe',
    commonName: 'Tajikistan Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Famagusta',
    city: 'Famagusta',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Asia/Gaza',
    city: 'Gaza',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Asia/Hebron',
    city: 'Hebron',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Asia/Hong_Kong',
    city: 'Hong Kong',
    commonName: 'Hong Kong Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Hovd',
    city: 'Hovd',
    commonName: 'Khovd Standard Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Irkutsk',
    city: 'Irkutsk',
    commonName: 'Irkutsk Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Jakarta',
    city: 'Jakarta',
    commonName: 'Western Indonesia Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Jayapura',
    city: 'Jayapura',
    commonName: 'Eastern Indonesia Time',
    abbreviations: ['GMT+9'],
  },
  {
    id: 'Asia/Jerusalem',
    city: 'Jerusalem',
    commonName: 'Israel Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Asia/Kabul',
    city: 'Kabul',
    commonName: 'Afghanistan Time',
    abbreviations: ['GMT+4:30'],
  },
  {
    id: 'Asia/Kamchatka',
    city: 'Kamchatka',
    commonName: 'Kamchatka Standard Time',
    abbreviations: ['GMT+12'],
  },
  {
    id: 'Asia/Karachi',
    city: 'Karachi',
    commonName: 'Pakistan Standard Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Katmandu',
    city: 'Katmandu',
    commonName: 'Nepal Time',
    abbreviations: ['GMT+5:45'],
  },
  {
    id: 'Asia/Khandyga',
    city: 'Khandyga',
    commonName: 'Yakutsk Standard Time',
    abbreviations: ['GMT+9'],
  },
  {
    id: 'Asia/Krasnoyarsk',
    city: 'Krasnoyarsk',
    commonName: 'Krasnoyarsk Standard Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Kuala_Lumpur',
    city: 'Kuala Lumpur',
    commonName: 'Malaysia Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Kuching',
    city: 'Kuching',
    commonName: 'Malaysia Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Kuwait',
    city: 'Kuwait',
    commonName: 'Arabian Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Asia/Macau',
    city: 'Macau',
    commonName: 'China Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Magadan',
    city: 'Magadan',
    commonName: 'Magadan Standard Time',
    abbreviations: ['GMT+11'],
  },
  {
    id: 'Asia/Makassar',
    city: 'Makassar',
    commonName: 'Central Indonesia Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Manila',
    city: 'Manila',
    commonName: 'Philippine Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Muscat',
    city: 'Muscat',
    commonName: 'Gulf Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Asia/Nicosia',
    city: 'Nicosia',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Asia/Novokuznetsk',
    city: 'Novokuznetsk',
    commonName: 'Krasnoyarsk Standard Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Novosibirsk',
    city: 'Novosibirsk',
    commonName: 'Krasnoyarsk Standard Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Omsk',
    city: 'Omsk',
    commonName: 'Omsk Standard Time',
    abbreviations: ['GMT+6'],
  },
  {
    id: 'Asia/Oral',
    city: 'Oral',
    commonName: 'Kazakhstan Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Phnom_Penh',
    city: 'Phnom Penh',
    commonName: 'Indochina Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Pontianak',
    city: 'Pontianak',
    commonName: 'Western Indonesia Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Pyongyang',
    city: 'Pyongyang',
    commonName: 'Korean Standard Time',
    abbreviations: ['GMT+9'],
  },
  {
    id: 'Asia/Qatar',
    city: 'Qatar',
    commonName: 'Arabian Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Asia/Qostanay',
    city: 'Qostanay',
    commonName: 'Kazakhstan Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Qyzylorda',
    city: 'Qyzylorda',
    commonName: 'Kazakhstan Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Rangoon',
    city: 'Rangoon',
    commonName: 'Myanmar Time',
    abbreviations: ['GMT+6:30'],
  },
  {
    id: 'Asia/Riyadh',
    city: 'Riyadh',
    commonName: 'Arabian Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Asia/Saigon',
    city: 'Saigon',
    commonName: 'Indochina Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Sakhalin',
    city: 'Sakhalin',
    commonName: 'Magadan Standard Time',
    abbreviations: ['GMT+11'],
  },
  {
    id: 'Asia/Samarkand',
    city: 'Samarkand',
    commonName: 'Uzbekistan Standard Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Seoul',
    city: 'Seoul',
    commonName: 'Korean Standard Time',
    abbreviations: ['GMT+9'],
  },
  {
    id: 'Asia/Shanghai',
    city: 'Shanghai',
    commonName: 'China Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Singapore',
    city: 'Singapore',
    commonName: 'Singapore Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Srednekolymsk',
    city: 'Srednekolymsk',
    commonName: 'Magadan Standard Time',
    abbreviations: ['GMT+11'],
  },
  {
    id: 'Asia/Taipei',
    city: 'Taipei',
    commonName: 'Taiwan Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Tashkent',
    city: 'Tashkent',
    commonName: 'Uzbekistan Standard Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Tbilisi',
    city: 'Tbilisi',
    commonName: 'Georgia Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Asia/Tehran',
    city: 'Tehran',
    commonName: 'Iran Standard Time',
    abbreviations: ['GMT+3:30'],
  },
  {
    id: 'Asia/Thimphu',
    city: 'Thimphu',
    commonName: 'Bhutan Time',
    abbreviations: ['GMT+6'],
  },
  {
    id: 'Asia/Tokyo',
    city: 'Tokyo',
    commonName: 'Japan Standard Time',
    abbreviations: ['GMT+9'],
  },
  {
    id: 'Asia/Tomsk',
    city: 'Tomsk',
    commonName: 'Krasnoyarsk Standard Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Ulaanbaatar',
    city: 'Ulaanbaatar',
    commonName: 'Ulaanbaatar Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Asia/Urumqi',
    city: 'Urumqi',
    commonName: 'Ürümqi Time',
    abbreviations: ['GMT+6'],
  },
  {
    id: 'Asia/Ust-Nera',
    city: 'Ust-Nera',
    commonName: 'Vladivostok Standard Time',
    abbreviations: ['GMT+10'],
  },
  {
    id: 'Asia/Vientiane',
    city: 'Vientiane',
    commonName: 'Indochina Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Asia/Vladivostok',
    city: 'Vladivostok',
    commonName: 'Vladivostok Standard Time',
    abbreviations: ['GMT+10'],
  },
  {
    id: 'Asia/Yakutsk',
    city: 'Yakutsk',
    commonName: 'Yakutsk Standard Time',
    abbreviations: ['GMT+9'],
  },
  {
    id: 'Asia/Yekaterinburg',
    city: 'Yekaterinburg',
    commonName: 'Yekaterinburg Standard Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Asia/Yerevan',
    city: 'Yerevan',
    commonName: 'Armenia Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Atlantic/Azores',
    city: 'Azores',
    commonName: 'Azores Time',
    abbreviations: ['GMT-1', 'GMT+0'],
  },
  {
    id: 'Atlantic/Bermuda',
    city: 'Bermuda',
    commonName: 'Atlantic Time',
    abbreviations: ['AST', 'ADT'],
  },
  {
    id: 'Atlantic/Canary',
    city: 'Canary',
    commonName: 'Western European Time',
    abbreviations: ['GMT+0', 'GMT+1'],
  },
  {
    id: 'Atlantic/Cape_Verde',
    city: 'Cape Verde',
    commonName: 'Cape Verde Standard Time',
    abbreviations: ['GMT-1'],
  },
  {
    id: 'Atlantic/Faeroe',
    city: 'Faeroe',
    commonName: 'Western European Time',
    abbreviations: ['GMT+0', 'GMT+1'],
  },
  {
    id: 'Atlantic/Madeira',
    city: 'Madeira',
    commonName: 'Western European Time',
    abbreviations: ['GMT+0', 'GMT+1'],
  },
  {
    id: 'Atlantic/Reykjavik',
    city: 'Reykjavik',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Atlantic/South_Georgia',
    city: 'South Georgia',
    commonName: 'South Georgia Time',
    abbreviations: ['GMT-2'],
  },
  {
    id: 'Atlantic/St_Helena',
    city: 'St Helena',
    commonName: 'Greenwich Mean Time',
    abbreviations: ['GMT'],
  },
  {
    id: 'Atlantic/Stanley',
    city: 'Stanley',
    commonName: 'Falkland Islands Standard Time',
    abbreviations: ['GMT-3'],
  },
  {
    id: 'Australia/Adelaide',
    city: 'Adelaide',
    commonName: 'Australian Central Time',
    abbreviations: ['GMT+10:30', 'GMT+9:30'],
  },
  {
    id: 'Australia/Brisbane',
    city: 'Brisbane',
    commonName: 'Australian Eastern Standard Time',
    abbreviations: ['GMT+10'],
  },
  {
    id: 'Australia/Broken_Hill',
    city: 'Broken Hill',
    commonName: 'Australian Central Time',
    abbreviations: ['GMT+10:30', 'GMT+9:30'],
  },
  {
    id: 'Australia/Darwin',
    city: 'Darwin',
    commonName: 'Australian Central Standard Time',
    abbreviations: ['GMT+9:30'],
  },
  {
    id: 'Australia/Eucla',
    city: 'Eucla',
    commonName: 'Australian Central Western Standard Time',
    abbreviations: ['GMT+8:45'],
  },
  {
    id: 'Australia/Hobart',
    city: 'Hobart',
    commonName: 'Australian Eastern Time',
    abbreviations: ['GMT+11', 'GMT+10'],
  },
  {
    id: 'Australia/Lindeman',
    city: 'Lindeman',
    commonName: 'Australian Eastern Standard Time',
    abbreviations: ['GMT+10'],
  },
  {
    id: 'Australia/Lord_Howe',
    city: 'Lord Howe',
    commonName: 'Lord Howe Time',
    abbreviations: ['GMT+11', 'GMT+10:30'],
  },
  {
    id: 'Australia/Melbourne',
    city: 'Melbourne',
    commonName: 'Australian Eastern Time',
    abbreviations: ['GMT+11', 'GMT+10'],
  },
  {
    id: 'Australia/Perth',
    city: 'Perth',
    commonName: 'Australian Western Standard Time',
    abbreviations: ['GMT+8'],
  },
  {
    id: 'Australia/Sydney',
    city: 'Sydney',
    commonName: 'Australian Eastern Time',
    abbreviations: ['GMT+11', 'GMT+10'],
  },
  {
    id: 'Europe/Amsterdam',
    city: 'Amsterdam',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Andorra',
    city: 'Andorra',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Astrakhan',
    city: 'Astrakhan',
    commonName: 'Samara Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Europe/Athens',
    city: 'Athens',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Belgrade',
    city: 'Belgrade',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Berlin',
    city: 'Berlin',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Bratislava',
    city: 'Bratislava',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Brussels',
    city: 'Brussels',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Bucharest',
    city: 'Bucharest',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Budapest',
    city: 'Budapest',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Busingen',
    city: 'Busingen',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Chisinau',
    city: 'Chisinau',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Copenhagen',
    city: 'Copenhagen',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Dublin',
    city: 'Dublin',
    commonName: 'Ireland Time',
    abbreviations: ['GMT', 'GMT+1'],
  },
  {
    id: 'Europe/Gibraltar',
    city: 'Gibraltar',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Guernsey',
    city: 'Guernsey',
    commonName: 'Guernsey Time',
    abbreviations: ['GMT', 'GMT+1'],
  },
  {
    id: 'Europe/Helsinki',
    city: 'Helsinki',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Isle_of_Man',
    city: 'Isle of Man',
    commonName: 'Isle of Man Time',
    abbreviations: ['GMT', 'GMT+1'],
  },
  {
    id: 'Europe/Istanbul',
    city: 'Istanbul',
    commonName: 'Türkiye Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Europe/Jersey',
    city: 'Jersey',
    commonName: 'Jersey Time',
    abbreviations: ['GMT', 'GMT+1'],
  },
  {
    id: 'Europe/Kaliningrad',
    city: 'Kaliningrad',
    commonName: 'Eastern European Standard Time',
    abbreviations: ['GMT+2'],
  },
  {
    id: 'Europe/Kiev',
    city: 'Kiev',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Kirov',
    city: 'Kirov',
    commonName: 'Moscow Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Europe/Lisbon',
    city: 'Lisbon',
    commonName: 'Western European Time',
    abbreviations: ['GMT+0', 'GMT+1'],
  },
  {
    id: 'Europe/Ljubljana',
    city: 'Ljubljana',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/London',
    city: 'London',
    commonName: 'United Kingdom Time',
    abbreviations: ['GMT', 'GMT+1'],
  },
  {
    id: 'Europe/Luxembourg',
    city: 'Luxembourg',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Madrid',
    city: 'Madrid',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Malta',
    city: 'Malta',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Mariehamn',
    city: 'Mariehamn',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Minsk',
    city: 'Minsk',
    commonName: 'Moscow Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Europe/Monaco',
    city: 'Monaco',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Moscow',
    city: 'Moscow',
    commonName: 'Moscow Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Europe/Oslo',
    city: 'Oslo',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Paris',
    city: 'Paris',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Podgorica',
    city: 'Podgorica',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Prague',
    city: 'Prague',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Riga',
    city: 'Riga',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Rome',
    city: 'Rome',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Samara',
    city: 'Samara',
    commonName: 'Samara Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Europe/San_Marino',
    city: 'San Marino',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Sarajevo',
    city: 'Sarajevo',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Saratov',
    city: 'Saratov',
    commonName: 'Samara Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Europe/Simferopol',
    city: 'Simferopol',
    commonName: 'Moscow Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Europe/Skopje',
    city: 'Skopje',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Sofia',
    city: 'Sofia',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Stockholm',
    city: 'Stockholm',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Tallinn',
    city: 'Tallinn',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Tirane',
    city: 'Tirane',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Ulyanovsk',
    city: 'Ulyanovsk',
    commonName: 'Samara Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Europe/Vaduz',
    city: 'Vaduz',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Vatican',
    city: 'Vatican',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Vienna',
    city: 'Vienna',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Vilnius',
    city: 'Vilnius',
    commonName: 'Eastern European Time',
    abbreviations: ['GMT+2', 'GMT+3'],
  },
  {
    id: 'Europe/Volgograd',
    city: 'Volgograd',
    commonName: 'Moscow Standard Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Europe/Warsaw',
    city: 'Warsaw',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Zagreb',
    city: 'Zagreb',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Europe/Zurich',
    city: 'Zurich',
    commonName: 'Central European Time',
    abbreviations: ['GMT+1', 'GMT+2'],
  },
  {
    id: 'Indian/Antananarivo',
    city: 'Antananarivo',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Indian/Chagos',
    city: 'Chagos',
    commonName: 'Indian Ocean Time',
    abbreviations: ['GMT+6'],
  },
  {
    id: 'Indian/Christmas',
    city: 'Christmas',
    commonName: 'Christmas Island Time',
    abbreviations: ['GMT+7'],
  },
  {
    id: 'Indian/Cocos',
    city: 'Cocos',
    commonName: 'Cocos Islands Time',
    abbreviations: ['GMT+6:30'],
  },
  {
    id: 'Indian/Comoro',
    city: 'Comoro',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Indian/Kerguelen',
    city: 'Kerguelen',
    commonName: 'French Southern & Antarctic Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Indian/Mahe',
    city: 'Mahe',
    commonName: 'Seychelles Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Indian/Maldives',
    city: 'Maldives',
    commonName: 'Maldives Time',
    abbreviations: ['GMT+5'],
  },
  {
    id: 'Indian/Mauritius',
    city: 'Mauritius',
    commonName: 'Mauritius Standard Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Indian/Mayotte',
    city: 'Mayotte',
    commonName: 'East Africa Time',
    abbreviations: ['GMT+3'],
  },
  {
    id: 'Indian/Reunion',
    city: 'Reunion',
    commonName: 'Réunion Time',
    abbreviations: ['GMT+4'],
  },
  {
    id: 'Pacific/Apia',
    city: 'Apia',
    commonName: 'Samoa Standard Time',
    abbreviations: ['GMT+13'],
  },
  {
    id: 'Pacific/Auckland',
    city: 'Auckland',
    commonName: 'New Zealand Time',
    abbreviations: ['GMT+13', 'GMT+12'],
  },
  {
    id: 'Pacific/Bougainville',
    city: 'Bougainville',
    commonName: 'Bougainville Time',
    abbreviations: ['GMT+11'],
  },
  {
    id: 'Pacific/Chatham',
    city: 'Chatham',
    commonName: 'Chatham Time',
    abbreviations: ['GMT+13:45', 'GMT+12:45'],
  },
  {
    id: 'Pacific/Easter',
    city: 'Easter',
    commonName: 'Easter Island Time',
    abbreviations: ['GMT-5', 'GMT-6'],
  },
  {
    id: 'Pacific/Efate',
    city: 'Efate',
    commonName: 'Vanuatu Standard Time',
    abbreviations: ['GMT+11'],
  },
  {
    id: 'Pacific/Enderbury',
    city: 'Enderbury',
    commonName: 'Phoenix Islands Time',
    abbreviations: ['GMT+13'],
  },
  {
    id: 'Pacific/Fakaofo',
    city: 'Fakaofo',
    commonName: 'Tokelau Time',
    abbreviations: ['GMT+13'],
  },
  {
    id: 'Pacific/Fiji',
    city: 'Fiji',
    commonName: 'Fiji Standard Time',
    abbreviations: ['GMT+12'],
  },
  {
    id: 'Pacific/Funafuti',
    city: 'Funafuti',
    commonName: 'Tuvalu Time',
    abbreviations: ['GMT+12'],
  },
  {
    id: 'Pacific/Galapagos',
    city: 'Galapagos',
    commonName: 'Galapagos Time',
    abbreviations: ['GMT-6'],
  },
  {
    id: 'Pacific/Gambier',
    city: 'Gambier',
    commonName: 'Gambier Time',
    abbreviations: ['GMT-9'],
  },
  {
    id: 'Pacific/Guadalcanal',
    city: 'Guadalcanal',
    commonName: 'Solomon Islands Time',
    abbreviations: ['GMT+11'],
  },
  {
    id: 'Pacific/Guam',
    city: 'Guam',
    commonName: 'Chamorro Standard Time',
    abbreviations: ['GMT+10'],
  },
  {
    id: 'Pacific/Honolulu',
    city: 'Honolulu',
    commonName: 'Hawaii-Aleutian Standard Time',
    abbreviations: ['HST'],
  },
  {
    id: 'Pacific/Kiritimati',
    city: 'Kiritimati',
    commonName: 'Line Islands Time',
    abbreviations: ['GMT+14'],
  },
  {
    id: 'Pacific/Kosrae',
    city: 'Kosrae',
    commonName: 'Kosrae Time',
    abbreviations: ['GMT+11'],
  },
  {
    id: 'Pacific/Kwajalein',
    city: 'Kwajalein',
    commonName: 'Marshall Islands Time',
    abbreviations: ['GMT+12'],
  },
  {
    id: 'Pacific/Majuro',
    city: 'Majuro',
    commonName: 'Marshall Islands Time',
    abbreviations: ['GMT+12'],
  },
  {
    id: 'Pacific/Marquesas',
    city: 'Marquesas',
    commonName: 'Marquesas Time',
    abbreviations: ['GMT-9:30'],
  },
  {
    id: 'Pacific/Midway',
    city: 'Midway',
    commonName: 'American Samoa Standard Time',
    abbreviations: ['GMT-11'],
  },
  {
    id: 'Pacific/Nauru',
    city: 'Nauru',
    commonName: 'Nauru Time',
    abbreviations: ['GMT+12'],
  },
  {
    id: 'Pacific/Niue',
    city: 'Niue',
    commonName: 'Niue Time',
    abbreviations: ['GMT-11'],
  },
  {
    id: 'Pacific/Norfolk',
    city: 'Norfolk',
    commonName: 'Norfolk Island Time',
    abbreviations: ['GMT+12', 'GMT+11'],
  },
  {
    id: 'Pacific/Noumea',
    city: 'Noumea',
    commonName: 'New Caledonia Standard Time',
    abbreviations: ['GMT+11'],
  },
  {
    id: 'Pacific/Pago_Pago',
    city: 'Pago Pago',
    commonName: 'American Samoa Standard Time',
    abbreviations: ['GMT-11'],
  },
  {
    id: 'Pacific/Palau',
    city: 'Palau',
    commonName: 'Palau Time',
    abbreviations: ['GMT+9'],
  },
  {
    id: 'Pacific/Pitcairn',
    city: 'Pitcairn',
    commonName: 'Pitcairn Time',
    abbreviations: ['GMT-8', 'PST', 'Pitcairn Time'],
  },
  {
    id: 'Pacific/Ponape',
    city: 'Ponape',
    commonName: 'Pohnpei Time',
    abbreviations: ['GMT+11'],
  },
  {
    id: 'Pacific/Port_Moresby',
    city: 'Port Moresby',
    commonName: 'Papua New Guinea Time',
    abbreviations: ['GMT+10'],
  },
  {
    id: 'Pacific/Rarotonga',
    city: 'Rarotonga',
    commonName: 'Cook Islands Standard Time',
    abbreviations: ['GMT-10'],
  },
  {
    id: 'Pacific/Saipan',
    city: 'Saipan',
    commonName: 'Chamorro Standard Time',
    abbreviations: ['GMT+10'],
  },
  {
    id: 'Pacific/Tahiti',
    city: 'Tahiti',
    commonName: 'Tahiti Time',
    abbreviations: ['GMT-10'],
  },
  {
    id: 'Pacific/Tarawa',
    city: 'Tarawa',
    commonName: 'Gilbert Islands Time',
    abbreviations: ['GMT+12'],
  },
  {
    id: 'Pacific/Tongatapu',
    city: 'Tongatapu',
    commonName: 'Tonga Standard Time',
    abbreviations: ['GMT+13'],
  },
  {
    id: 'Pacific/Truk',
    city: 'Truk',
    commonName: 'Chuuk Time',
    abbreviations: ['GMT+10'],
  },
  {
    id: 'Pacific/Wake',
    city: 'Wake',
    commonName: 'Wake Island Time',
    abbreviations: ['GMT+12'],
  },
  {
    id: 'Pacific/Wallis',
    city: 'Wallis',
    commonName: 'Wallis & Futuna Time',
    abbreviations: ['GMT+12'],
  },
];
