import { and, eq } from 'drizzle-orm';
import { beforeAll, describe, expect, it } from 'vitest';

import type * as DbModule from '@docket/db';
import {
  MockMcpConnector,
  SUNSAMA_FIXTURE_DAYS,
  SUNSAMA_FIXTURE_HOST,
  SUNSAMA_MIGRATION_FIXTURE_SERVER,
  SUNSAMA_FIXTURE_URL,
  SUNSAMA_ROUTING,
  groupSunsamaImportedItemsByWorkspace,
  readSunsamaAccount,
  sunsamaAccountToImportedItems,
  validateSunsamaRouting,
  verifySunsamaRouting,
} from '@docket/integrations';

import type * as ReconcileModule from '../../src/routes/integration-reconcile';
import { getDb, one, seedBaseOrg } from '../support/routes-harness';

/**
 * WIL-01 / WIL-02 / WIL-04 / MISS-08 — the end-to-end proof that the Sunsama → Docket pipeline
 * (read via MCP → normalize → route → map → `sunsama-connector.ts` → `reconcileTasks`) produces
 * real, traceable, idempotent Docket task rows on the committed fixture account.
 *
 * @remarks
 * Deliberately calls `reconcileTasks` directly against the pglite harness — exactly the pattern
 * `integration-reconcile-orchestration.test.ts` (worker 1's Notion/gtasks sibling) already uses —
 * rather than going through `scripts/import-sunsama.ts`'s CLI entrypoint, so this proof runs in
 * every `pnpm test` without a live database or the dev stack. The CLI itself is exercised
 * separately by actually running `pnpm sunsama:import --source=fixture --apply` against the local
 * dev database (see `docs/migration/sunsama-run.json`, regenerated by that real run).
 *
 * `SUNSAMA_ROUTING` is imported from `@docket/integrations` (not redeclared here) so this test
 * proves the ACTUAL production routing declaration `scripts/import-sunsama.ts` also uses, not a
 * stand-in approximation.
 */

let schema!: typeof DbModule;
let db!: typeof DbModule.db;
let reconcileTasks!: typeof ReconcileModule.reconcileTasks;

beforeAll(async () => {
  schema = await getDb();
  db = schema.db;
  reconcileTasks = (await import('../../src/routes/integration-reconcile')).reconcileTasks;
});

/** Seed a `sunsama` migration-pattern integration row, mirroring what the CLI creates. */
async function seedSunsamaIntegration(
  orgId: string,
  actorId: string,
): Promise<typeof schema.integration.$inferSelect> {
  return one(
    await db
      .insert(schema.integration)
      .values({
        organizationId: orgId,
        provider: 'sunsama',
        pattern: 'migration',
        roles: ['work'],
        syncMode: 'import',
        syncCadenceMinutes: null,
        createdBy: actorId,
      })
      .returning(),
  );
}

/** Read the committed fixture account through the same MCP-only path the CLI uses. */
async function readFixtureAccount() {
  const connector = new MockMcpConnector({
    servers: { [SUNSAMA_FIXTURE_HOST]: SUNSAMA_MIGRATION_FIXTURE_SERVER },
  });
  const session = await connector.open({ url: SUNSAMA_FIXTURE_URL });
  return readSunsamaAccount(session, { days: SUNSAMA_FIXTURE_DAYS, includeArchived: true });
}

describe('Sunsama → Docket, end to end on the fixture', () => {
  it('reads every active fixture task, routes it per the declared mapping, and reconciles it into a real, traceable Docket task', async () => {
    const { orgId, teamId, humanActorId } = await seedBaseOrg(db, schema);
    const integration = await seedSunsamaIntegration(orgId, humanActorId);

    const routingProblems = validateSunsamaRouting(SUNSAMA_ROUTING);
    expect(routingProblems).toEqual([]);

    const account = await readFixtureAccount();
    // WIL-01: nothing is left behind — every active fixture task was read.
    expect(account.tasks).toHaveLength(7);

    const routingReport = verifySunsamaRouting(account.tasks, SUNSAMA_ROUTING);
    // MISS-08: the fallback count matches what was declared BEFORE this run, and nothing is
    // unrouted.
    expect(routingReport.matchesDeclaration).toBe(true);
    expect(routingReport.unroutedCount).toBe(0);

    const importedAt = '2026-08-02T00:00:00.000Z';
    const mapped = sunsamaAccountToImportedItems(account.tasks, SUNSAMA_ROUTING, importedAt);
    const items = mapped.map((m) => m.item);
    expect(items).toHaveLength(7);

    // This test reconciles every routed task into ONE (org, team) — proving the reconcile step
    // itself (provenance + idempotency); resolving each destination workspace name to its own
    // real org is the CLI's job, exercised separately by an actual `--apply` run (see
    // docs/migration/sunsama-run.json).
    const tally = await reconcileTasks(orgId, humanActorId, integration, teamId, items, {
      assigneeId: null,
      writable: null,
    });
    expect(tally).toEqual({
      inserted: 7,
      pulled: 0,
      pushed: 0,
      deleted: 0,
      archived: 0,
      created: 0,
      conflicts: 0,
    });

    const rows = await db
      .select()
      .from(schema.task)
      .where(
        and(
          eq(schema.task.organizationId, orgId),
          eq(schema.task.sourceIntegrationId, integration.id),
        ),
      );
    expect(rows).toHaveLength(7);

    // WIL-01's reconciliation acceptance, computed for real: every Sunsama task id maps to
    // exactly one Docket task id, and the unmatched list on both sides is empty.
    const sunsamaIds = new Set(account.tasks.map((t) => t.id));
    const docketExternalIds = new Set(
      rows.map((row) => row.externalId).filter((id): id is string => id !== null),
    );
    expect(docketExternalIds.size).toBe(rows.length); // one Docket row per Sunsama id, never fewer
    const unmatchedSunsamaIds = [...sunsamaIds].filter((id) => !docketExternalIds.has(id));
    const unmatchedDocketIds = rows.filter(
      (row) => row.externalId === null || !sunsamaIds.has(row.externalId),
    );
    expect(unmatchedSunsamaIds).toEqual([]);
    expect(unmatchedDocketIds).toEqual([]);

    for (const row of rows) {
      expect(row.source).toBe('linked');
      expect(row.sourceIntegrationId).toBe(integration.id);
    }
  });

  it('a second run against the unchanged fixture creates zero duplicates and mutates zero pre-existing rows', async () => {
    const { orgId, teamId, humanActorId } = await seedBaseOrg(db, schema);
    const integration = await seedSunsamaIntegration(orgId, humanActorId);
    const account = await readFixtureAccount();
    const importedAt = '2026-08-02T00:00:00.000Z';
    const items = sunsamaAccountToImportedItems(account.tasks, SUNSAMA_ROUTING, importedAt).map(
      (m) => m.item,
    );

    const first = await reconcileTasks(orgId, humanActorId, integration, teamId, items, {
      assigneeId: null,
      writable: null,
    });
    expect(first.inserted).toBe(7);

    const afterFirst = await db
      .select()
      .from(schema.task)
      .where(eq(schema.task.sourceIntegrationId, integration.id));
    expect(afterFirst).toHaveLength(7);
    const updatedAtById = new Map(afterFirst.map((row) => [row.id, row.updatedAt.toISOString()]));

    // Re-read + re-map + reconcile again, exactly as a second `pnpm sunsama:import` invocation
    // would — the fixture and the routing declaration are both unchanged.
    const secondAccount = await readFixtureAccount();
    const secondItems = sunsamaAccountToImportedItems(
      secondAccount.tasks,
      SUNSAMA_ROUTING,
      importedAt,
    ).map((m) => m.item);
    const second = await reconcileTasks(orgId, humanActorId, integration, teamId, secondItems, {
      assigneeId: null,
      writable: null,
    });

    // Every task is already present and unchanged: nothing inserted, pulled, pushed, or archived.
    expect(second).toEqual({
      inserted: 0,
      pulled: 0,
      pushed: 0,
      deleted: 0,
      archived: 0,
      created: 0,
      conflicts: 0,
    });

    const afterSecond = await db
      .select()
      .from(schema.task)
      .where(eq(schema.task.sourceIntegrationId, integration.id));
    expect(afterSecond).toHaveLength(7); // zero duplicates
    for (const row of afterSecond) {
      // zero pre-existing rows mutated: same row id, same updatedAt as after the first run.
      expect(updatedAtById.get(row.id)).toBe(row.updatedAt.toISOString());
    }
  });

  it('groups mapped tasks by destination workspace, matching the routing report’s per-workspace tallies', async () => {
    const account = await readFixtureAccount();
    const routingReport = verifySunsamaRouting(account.tasks, SUNSAMA_ROUTING);
    const mapped = sunsamaAccountToImportedItems(
      account.tasks,
      SUNSAMA_ROUTING,
      '2026-08-02T00:00:00.000Z',
    );
    const groups = groupSunsamaImportedItemsByWorkspace(mapped);

    const counts: Record<string, number> = {};
    for (const [workspace, groupedItems] of groups) counts[workspace] = groupedItems.length;
    expect(counts).toEqual(routingReport.perWorkspace);
  });
});
