/**
 * Athena's provider-neutral, one-turn runtime boundary.
 *
 * The host owns the durable loop: persistence, tool execution, approvals, and resume. This
 * boundary owns exactly one model turn, so every delivery runtime can exchange the same appendable
 * transcript message and event stream.
 */
import type { TurnContentBlock, TurnMessage } from '../turn-protocol';
import { bindJournalingPlanTurns } from './internal/journaling-plan-script';

export type { TurnContentBlock, TurnMessage };

/** One tool the model may call during this turn. */
export interface TurnToolDef {
  /** The stable tool name exposed to the model. */
  readonly name: string;
  /** A human-readable description of what the tool does. */
  readonly description: string;
  /** The JSON Schema for the tool input. */
  readonly inputSchema: Record<string, unknown>;
}

/** Why the provider stopped generating the turn. */
export type TurnStopReason = 'end_turn' | 'tool_use' | 'refusal' | 'max_tokens';

/** A completed event emitted while one model turn is running. */
export type TurnEvent =
  | {
      /** A completed reasoning block. */
      readonly type: 'thinking';
      /** The completed reasoning text. */
      readonly text: string;
    }
  | {
      /** A completed visible text block. */
      readonly type: 'text';
      /** The completed visible text. */
      readonly text: string;
    }
  | {
      /** A completed tool invocation request. */
      readonly type: 'tool_use';
      /** The provider block id. */
      readonly id: string;
      /** The stable tool name. */
      readonly name: string;
      /** Parsed tool input. */
      readonly input: unknown;
    }
  | {
      /** The terminal event every turn emits. */
      readonly type: 'turn_end';
      /** Why generation stopped. */
      readonly stopReason: TurnStopReason;
      /** The complete assistant message ready to append to the transcript. */
      readonly message: TurnMessage;
      /**
       * What the turn cost at the provider, when the provider reports it.
       *
       * @remarks
       * Absent rather than zeroed when unreported, because a runtime that does not account for
       * tokens has not told us the turn was free — it has told us nothing. A Lattice-executed turn
       * runs on someone else's compute and returns no counts at all, so the two cases have to stay
       * distinguishable all the way to the operator console.
       */
      readonly usage?: TurnUsage | undefined;
    };

/**
 * What one turn consumed at the provider.
 *
 * @remarks
 * Cache reads and cache writes are separate fields because they are priced differently and an
 * operator reading a bill needs to see which one moved. Every count is for the single turn that
 * emitted it; accumulating across a session is the caller's job.
 */
export interface TurnUsage {
  /** Fresh input tokens, excluding anything served from or written to the cache. */
  readonly inputTokens: number;
  /** Tokens generated by the model. */
  readonly outputTokens: number;
  /** Input tokens served from the prompt cache. */
  readonly cacheReadTokens: number;
  /** Input tokens written into the prompt cache. */
  readonly cacheCreationTokens: number;
  /** The model that actually served the turn, as the provider names it. */
  readonly model: string;
}

/** Input to one model turn: durable context plus the tools it may use. */
export interface TurnInput {
  /** The system prompt for the turn. */
  readonly system: string;
  /** The full durable conversation so far. */
  readonly messages: readonly TurnMessage[];
  /** The tools available during this turn. */
  readonly tools: readonly TurnToolDef[];
  /**
   * The task this work is about, when the session has one: the task the person asked from, or the
   * task the work was filed as.
   *
   * @remarks
   * Model-backed runtimes ignore this field. {@link MockAgentTurnRuntime} aims its default script
   * at it, so a locally dispatched job proposes a change to a task that exists.
   */
  readonly subjectTask?: TurnSubjectTask | undefined;
}

/** A task a turn's work is about, with the workspace that holds it. */
export interface TurnSubjectTask {
  /** The task id. */
  readonly id: string;
  /** The workspace the task belongs to. */
  readonly organizationId: string;
}

/** Provider-neutral port for streaming one model turn. */
export interface AgentTurnRuntime {
  /** Stream a model turn for the supplied context. */
  streamTurn(input: TurnInput): AsyncIterable<TurnEvent>;
}

/** One deterministic turn: the assistant message to replay and why it ends. */
export interface ScriptedTurn {
  /** The complete assistant message for this turn. */
  readonly message: TurnMessage;
  /** The stop reason the terminal event reports. */
  readonly stopReason: TurnStopReason;
}

/**
 * The placeholder task id in {@link SCRIPTED_TURNS}. No real task can match it; a turn with a
 * subject task replays the script aimed at that task instead.
 */
export const SCRIPTED_TASK_ID = '01HZ0000000000000000LN0001';

/** The one tool call the default script proposes. */
interface ScriptedToolCall {
  /** The tool name. */
  readonly name: string;
  /** The tool input. */
  readonly input: Readonly<Record<string, unknown>>;
}

/**
 * Move one task to In Progress through the `update` tool, the way a model would.
 *
 * @param subject - The task to move.
 * @returns the `update` call scoped to exactly that task.
 */
function startTaskCall(subject: TurnSubjectTask): ScriptedToolCall {
  return {
    name: 'update',
    input: {
      orgId: subject.organizationId,
      entity: 'task',
      scope: { ids: [subject.id] },
      set: { state: 'in_progress' },
    },
  };
}

/**
 * The default script around one tool call.
 *
 * @param call - The call the first turn proposes.
 * @returns the two scripted turns: propose the change, then report it.
 */
function defaultScriptTurns(call: ScriptedToolCall): readonly ScriptedTurn[] {
  return [
    {
      message: {
        role: 'assistant',
        content: [
          {
            type: 'thinking',
            thinking: 'Reviewing the task and the current board state.',
            signature: 'mock-sig-turn-0',
          },
          {
            type: 'tool_use',
            id: 'toolu_mock_0001',
            name: call.name,
            input: call.input,
          },
        ],
      },
      stopReason: 'tool_use',
    },
    {
      message: {
        role: 'assistant',
        content: [
          {
            type: 'text',
            text: 'Moved the task to In Progress and verified the board reflects it.',
          },
        ],
      },
      stopReason: 'end_turn',
    },
  ];
}

/**
 * The default script {@link MockAgentTurnRuntime} replays in deterministic tests.
 *
 * @remarks
 * Its `update_task` call names a tool Docket's toolbox does not serve and a task id no task can
 * have, so approving it changes nothing. A turn with a subject task replays the same script as a
 * real `update` of that task.
 */
export const SCRIPTED_TURNS: readonly ScriptedTurn[] = defaultScriptTurns({
  name: 'update_task',
  input: { taskId: SCRIPTED_TASK_ID, state: 'in_progress' },
});

/** The Sunsama-import script used by onboarding and firehose tests. */
export const SUNSAMA_IMPORT_TURNS: readonly ScriptedTurn[] = [
  {
    message: {
      role: 'assistant',
      content: [
        {
          type: 'thinking',
          thinking: 'Reading the full Sunsama backlog before proposing any structure.',
          signature: 'mock-sig-sunsama-0',
        },
        {
          type: 'tool_use',
          id: 'toolu_mock_su01',
          name: 'sunsama__get_backlog_tasks',
          input: {},
        },
      ],
    },
    stopReason: 'tool_use',
  },
  {
    message: {
      role: 'assistant',
      content: [
        {
          type: 'text',
          text: 'I read 3 backlog tasks. Proposing them as Docket tasks in one batch.',
        },
        {
          type: 'tool_use',
          id: 'toolu_mock_su02',
          name: 'create_task',
          input: { title: 'Send the contractor agreement' },
        },
        {
          type: 'tool_use',
          id: 'toolu_mock_su03',
          name: 'create_task',
          input: { title: 'Book the venue for the offsite' },
        },
        {
          type: 'tool_use',
          id: 'toolu_mock_su04',
          name: 'create_task',
          input: { title: 'Reply to the partnership email' },
        },
      ],
    },
    stopReason: 'tool_use',
  },
  {
    message: {
      role: 'assistant',
      content: [
        {
          type: 'text',
          text: 'Imported 3 tasks from your Sunsama backlog. All are in your triage lane.',
        },
      ],
    },
    stopReason: 'end_turn',
  },
];

/**
 * The planning script, unbound.
 *
 * @remarks
 * Its ids are sentinels until `bindJournalingPlanTurns` resolves them against the conversation's
 * own tool results, which is what {@link MockAgentTurnRuntime} replays. Exported for tests that
 * check the script's shape against the plan tools' schemas.
 */
export { JOURNALING_PLAN_TURNS } from './internal/journaling-plan-script';

/** Construction options for {@link MockAgentTurnRuntime}. */
export interface MockAgentTurnRuntimeOptions {
  /** Optional override for the script to replay. */
  readonly script?: readonly ScriptedTurn[];
}

/** The phrase that picks the journaling planning script over the default one. */
const PLANNING_TRIGGER = /\bplan\b.*\bjournaling\b/i;

/** The first thing the person said, before any tool result came back. */
function firstUserText(messages: readonly TurnMessage[]): string {
  for (const message of messages) {
    if (message.role !== 'user') continue;
    for (const block of message.content) {
      if (block.type === 'text') return block.text;
    }
  }
  return '';
}

/** Deterministic runtime that replays one scripted turn per call. */
export class MockAgentTurnRuntime implements AgentTurnRuntime {
  private readonly injected: readonly ScriptedTurn[] | undefined;

  /** Create the runtime with its default or injected script. */
  constructor(options: MockAgentTurnRuntimeOptions = {}) {
    this.injected = options.script;
  }

  /**
   * The script this conversation replays.
   *
   * @remarks
   * An injected script always wins, so every test that hands one in keeps its exact turns. With no
   * injection, a conversation asking to plan a journaling launch runs the journaling planning
   * script and everything else runs the default one, aimed at the turn's subject task when it has
   * one.
   */
  private scriptFor(input: TurnInput): readonly ScriptedTurn[] {
    if (this.injected) return this.injected;
    if (PLANNING_TRIGGER.test(firstUserText(input.messages))) {
      return bindJournalingPlanTurns(input.messages);
    }
    if (input.subjectTask) return defaultScriptTurns(startTaskCall(input.subjectTask));
    return SCRIPTED_TURNS;
  }

  /** Replay the turn matching the number of persisted assistant messages. */
  async *streamTurn(input: TurnInput): AsyncIterable<TurnEvent> {
    const script = this.scriptFor(input);
    const turnIndex = input.messages.filter((message) => message.role === 'assistant').length;
    const turn = script[turnIndex];
    if (!turn) {
      throw new Error(
        `MockAgentTurnRuntime: conversation has ${turnIndex} assistant turns but the script ` +
          `has only ${script.length}; the hosting loop ran past the end of the script.`,
      );
    }

    for (const block of turn.message.content) {
      if (block.type === 'thinking') {
        yield { type: 'thinking', text: block.thinking };
      } else if (block.type === 'text') {
        yield { type: 'text', text: block.text };
      } else if (block.type === 'tool_use') {
        yield { type: 'tool_use', id: block.id, name: block.name, input: block.input };
      }
    }

    yield { type: 'turn_end', stopReason: turn.stopReason, message: turn.message };
  }
}
