/** `@docket/api` — recurrence series, occurrence, and one-call repeating-task routes. */
import { db } from '@docket/db';
import {
  CalendarProcessBindingCreate,
  CalendarProcessBindingOut,
  MaterializeSeriesOccurrence,
  GeneratedWorkRecurrenceOut,
  pageOf,
  RecurringTaskCreate,
  RecurringTaskCreated,
  RecurrenceSeriesCreate,
  RecurrenceSeriesDetailOut,
  RecurrenceSeriesLifecycle,
  RecurrenceSeriesOut,
  SeriesEdit,
} from '@docket/types';
import { Hono } from 'hono';
import { z } from 'zod';

import type { AppEnv } from '../context';
import { AuthError } from '../error';
import { ok } from '../lib/ok';
import { apiDoc } from '../lib/openapi-route';
import { createScheduledProcess } from '../lib/recurrence/authoring';
import { bindProcessToCalendarItem } from '../lib/recurrence/calendar-binding';
import { createRecurringTask } from '../lib/recurrence/recurring-task';
import {
  editRecurrenceSeries,
  listRecurrenceSeries,
  loadGeneratedWorkRecurrence,
  loadRecurrenceSeriesDetail,
  materializeSeriesOccurrence,
  transitionRecurrenceSeries,
  utcCalendarDate,
} from '../lib/recurrence/series';
import { materializeRecurrenceSeriesWindow } from '../lib/recurrence/sweep';
import { zJson, zParam } from '../lib/validate';
import { capabilityGuard } from '../permissions/capability-guard';
import { enqueueSearchDelete } from '../search/write-through';

const idParam = z.object({ id: z.string() });
const taskParam = z.object({ taskId: z.string() });
const projectParam = z.object({ projectId: z.string() });

/** Org-scoped schedule, lifecycle, history, and occurrence operations. */
const recurrenceSeriesRoutes = new Hono<AppEnv>()
  .get(
    '/',
    apiDoc({
      tag: 'Recurrence',
      summary: 'List recurrence series',
      response: pageOf(RecurrenceSeriesOut),
      description:
        'List active, paused, and ended recurrence series in this workspace with each latest trigger revision reconstructed as a named discriminated union.',
    }),
    async (c) => {
      const { orgId } = c.get('actorCtx');
      const items = await listRecurrenceSeries(db, orgId);
      return ok(c, pageOf(RecurrenceSeriesOut), { items });
    },
  )
  .post(
    '/',
    capabilityGuard('contribute'),
    apiDoc({
      tag: 'Recurrence',
      summary: 'Create a recurrence series',
      capability: 'contribute',
      response: RecurrenceSeriesOut,
      description:
        'Create a calendar, completion-anchored, manual, or event-driven series over the current published revision of a reusable process.',
    }),
    zJson(RecurrenceSeriesCreate),
    async (c) => {
      const { orgId, actorId } = c.get('actorCtx');
      const body = c.req.valid('json');
      const detail = await createScheduledProcess(db, {
        organizationId: orgId,
        actorId,
        series: body,
      });
      return ok(c, RecurrenceSeriesOut, detail);
    },
  )
  .post(
    '/calendar-bindings',
    capabilityGuard('contribute'),
    apiDoc({
      tag: 'Recurrence',
      summary: 'Add process work for a calendar event',
      capability: 'contribute',
      response: CalendarProcessBindingOut,
      description:
        'Bind a user-owned calendar event or provider event series to a reusable workspace process. The selected event is materialized immediately and future synced occurrences use the same recurrence series.',
    }),
    zJson(CalendarProcessBindingCreate),
    async (c) => {
      const session = c.get('session');
      if (!session) throw new AuthError();
      const { orgId, actorId } = c.get('actorCtx');
      const selected = c.req.valid('json');
      const binding = await bindProcessToCalendarItem(db, {
        organizationId: orgId,
        actorId,
        userId: session.user.id,
        calendarItemId: selected.calendarItemId,
        processDefinitionId: selected.processDefinitionId,
      });
      return ok(c, CalendarProcessBindingOut, binding);
    },
  )
  .get(
    '/for-task/:taskId',
    apiDoc({
      tag: 'Recurrence',
      summary: 'Get a generated task recurrence backlink',
      response: GeneratedWorkRecurrenceOut.nullable(),
      description:
        'Return the process occurrence and recurrence series that generated one ordinary task, or null when the task was not generated by repeating work.',
    }),
    zParam(taskParam),
    async (c) => {
      const { orgId } = c.get('actorCtx');
      const context = await loadGeneratedWorkRecurrence(db, {
        kind: 'task',
        organizationId: orgId,
        taskId: c.req.valid('param').taskId,
      });
      return ok(c, GeneratedWorkRecurrenceOut.nullable(), context);
    },
  )
  .get(
    '/for-project/:projectId',
    apiDoc({
      tag: 'Recurrence',
      summary: 'Get a generated project recurrence backlink',
      response: GeneratedWorkRecurrenceOut.nullable(),
      description:
        'Return the process occurrence and recurrence series that generated one ordinary project, or null when the project was not generated by repeating work.',
    }),
    zParam(projectParam),
    async (c) => {
      const { orgId } = c.get('actorCtx');
      const context = await loadGeneratedWorkRecurrence(db, {
        kind: 'project',
        organizationId: orgId,
        projectId: c.req.valid('param').projectId,
      });
      return ok(c, GeneratedWorkRecurrenceOut.nullable(), context);
    },
  )
  .get(
    '/:id',
    apiDoc({
      tag: 'Recurrence',
      summary: 'Get recurrence series',
      response: RecurrenceSeriesDetailOut,
      description:
        'Get one workspace-scoped series, its current trigger, and durable expected, materialized, skipped, canceled, and completed occurrence history.',
    }),
    zParam(idParam),
    async (c) => {
      const { orgId } = c.get('actorCtx');
      const detail = await loadRecurrenceSeriesDetail(db, orgId, c.req.valid('param').id);
      return ok(c, RecurrenceSeriesDetailOut, detail);
    },
  )
  .post(
    '/:id/lifecycle',
    capabilityGuard('contribute'),
    apiDoc({
      tag: 'Recurrence',
      summary: 'Change recurrence lifecycle',
      capability: 'contribute',
      response: RecurrenceSeriesOut,
      description:
        'Pause, resume, or permanently end a recurrence series. The transition is idempotent and never deletes historical occurrences or generated work.',
    }),
    zParam(idParam),
    zJson(RecurrenceSeriesLifecycle),
    async (c) => {
      const { orgId } = c.get('actorCtx');
      const series = await transitionRecurrenceSeries(
        db,
        orgId,
        c.req.valid('param').id,
        c.req.valid('json'),
      );
      return ok(c, RecurrenceSeriesOut, series);
    },
  )
  .post(
    '/:id/materialize',
    capabilityGuard('contribute'),
    apiDoc({
      tag: 'Recurrence',
      summary: 'Materialize a series occurrence',
      capability: 'contribute',
      response: RecurrenceSeriesDetailOut,
      description:
        'Idempotently materialize one manual or explicitly dated occurrence through the process engine, creating ordinary Docket work and retaining source mappings.',
    }),
    zParam(idParam),
    zJson(MaterializeSeriesOccurrence),
    async (c) => {
      const { orgId, actorId } = c.get('actorCtx');
      const { id } = c.req.valid('param');
      const body = c.req.valid('json');
      await materializeSeriesOccurrence(db, {
        organizationId: orgId,
        actorId,
        seriesId: id,
        scheduledFor: body.scheduledFor ?? utcCalendarDate(),
        occurrenceKey: body.occurrenceKey,
      });
      const detail = await loadRecurrenceSeriesDetail(db, orgId, id);
      return ok(c, RecurrenceSeriesDetailOut, detail);
    },
  )
  .post(
    '/:id/edits',
    capabilityGuard('contribute'),
    apiDoc({
      tag: 'Recurrence',
      summary: 'Edit recurrence scope',
      capability: 'contribute',
      response: RecurrenceSeriesDetailOut,
      description:
        'Resolve, skip, cancel, or reschedule one occurrence, or append a trigger revision effective from a future date. Past process instances remain immutable.',
    }),
    zParam(idParam),
    zJson(SeriesEdit),
    async (c) => {
      const { orgId, actorId } = c.get('actorCtx');
      let detail = await editRecurrenceSeries(db, {
        organizationId: orgId,
        actorId,
        seriesId: c.req.valid('param').id,
        edit: c.req.valid('json'),
        onRetired: async (work) => {
          await Promise.all([
            ...work.taskIds.map((id) => enqueueSearchDelete(orgId, 'task', id)),
            ...work.projectIds.map((id) => enqueueSearchDelete(orgId, 'project', id)),
          ]);
        },
      });
      const edit = c.req.valid('json');
      if (edit.scope === 'future') {
        await materializeRecurrenceSeriesWindow(db, {
          organizationId: orgId,
          seriesId: c.req.valid('param').id,
          actorId,
          asOf: utcCalendarDate(),
        });
        detail = await loadRecurrenceSeriesDetail(db, orgId, c.req.valid('param').id);
      }
      return ok(c, RecurrenceSeriesDetailOut, detail);
    },
  );

/** One-call ordinary-task composer endpoint backed by the general process and series model. */
export const recurringTaskRoutes = new Hono<AppEnv>().post(
  '/',
  capabilityGuard('contribute'),
  apiDoc({
    tag: 'Recurrence',
    summary: 'Create a recurring task',
    capability: 'contribute',
    response: RecurringTaskCreated,
    description:
      'Create a repeating ordinary task in one call. Docket authors a one-step process, creates a series, and materializes its rolling calendar window or first completion-anchored task.',
  }),
  zJson(RecurringTaskCreate),
  async (c) => {
    const { orgId, actorId } = c.get('actorCtx');
    const created = await createRecurringTask(db, {
      organizationId: orgId,
      actorId,
      recurringTask: c.req.valid('json'),
    });
    return ok(c, RecurringTaskCreated, created);
  },
);

export default recurrenceSeriesRoutes;
