/**
 * `@docket/types` — account end-of-life DTOs (export + deletion).
 *
 * @remarks
 * User-scoped surface backing the personal-workspace **Export data** and **Danger zone**
 * settings. Deletion is a recoverable 14-day grace flow (`pending_deletion`), mirroring the
 * org data-lifecycle on the account layer; export is asynchronous (a request is queued and
 * a download link is emailed when the archive is ready). Absent values are modelled as
 * `.nullable()` (never `.optional()`), so every field is always present in the wire shape.
 */
import { z } from 'zod';

/** Account end-of-life state (the account-level mirror of the org lifecycle). */
export const AccountDeletionState = z
  .enum(['active', 'pending_deletion'])
  .describe(
    "The account's end-of-life state. `active` is the normal state; `pending_deletion` means deletion has been scheduled and the 14-day grace window is counting down (recoverable until the cron purge runs at `deleteAfterAt`).",
  );
/** Account-deletion-state value. */
export type AccountDeletionState = z.infer<typeof AccountDeletionState>;

/** Status of one asynchronous personal-data export job. */
export const AccountExportStatus = z
  .enum(['pending', 'ready', 'failed', 'expired'])
  .describe(
    'Where a personal-data export job is in its lifecycle: `pending` (queued, archive being generated by the cron sweep), `ready` (archive built and downloadable — `downloadUrl`/`readyAt`/`expiresAt` populated), `failed` (generation errored, request a new one), `expired` (the download window closed; the blob may be swept).',
  );
/** Account-export-status value. */
export type AccountExportStatus = z.infer<typeof AccountExportStatus>;

/** A top-level category a person may include in a personal-data archive. */
export const AccountExportCategory = z
  .enum(['account', 'personal', 'workspaces'])
  .describe(
    'A selectable personal-data export category: account identity and connected apps, cross-workspace personal data, or selected Docket workspaces.',
  );
/** Account-export-category value. */
export type AccountExportCategory = z.infer<typeof AccountExportCategory>;

/** Why an archive was requested. */
export const AccountExportOrigin = z
  .enum(['manual', 'account_deletion'])
  .describe(
    'Whether the person created the archive from Export data or Docket created a complete archive while account deletion was scheduled.',
  );
/** Account-export-origin value. */
export type AccountExportOrigin = z.infer<typeof AccountExportOrigin>;

/** One workspace included in a persisted archive scope. */
export const AccountExportWorkspace = z
  .object({
    /** Stable workspace id, validated as one the caller belonged to when the export was requested. */
    id: z.string().describe('Stable workspace id.'),
    /** Workspace name snapshot, retained so export history stays understandable after a rename. */
    name: z.string().describe('Workspace name when the export was requested.'),
  })
  .meta({ id: 'AccountExportWorkspace', description: 'A workspace selected for one archive.' });
/** Account-export-workspace value. */
export type AccountExportWorkspace = z.infer<typeof AccountExportWorkspace>;

/** The persisted, human-readable scope of one personal-data archive. */
export const AccountExportScope = z
  .object({
    /** Categories included in the archive. */
    categories: z
      .array(AccountExportCategory)
      .min(1)
      .describe('Selected top-level categories, never empty.'),
    /** Named workspace snapshot for a selective workspace export. */
    workspaces: z
      .array(AccountExportWorkspace)
      .describe('Workspaces selected for this archive; empty when workspace data is excluded.'),
    /** True only for legacy/full deletion exports whose workspaces were not snapshotted. */
    allWorkspaces: z
      .boolean()
      .describe('Whether all workspaces available while the archive is generated are included.'),
  })
  .superRefine((scope, ctx) => {
    const includesWorkspaces = scope.categories.includes('workspaces');
    if (includesWorkspaces && !scope.allWorkspaces && scope.workspaces.length === 0) {
      ctx.addIssue({
        code: 'custom',
        path: ['workspaces'],
        message: 'Select at least one workspace when exporting workspace data.',
      });
    }
    if (!includesWorkspaces && (scope.allWorkspaces || scope.workspaces.length > 0)) {
      ctx.addIssue({
        code: 'custom',
        path: ['workspaces'],
        message: 'Workspace selections require the workspaces category.',
      });
    }
  })
  .meta({ id: 'AccountExportScope', description: 'The persisted scope of one data archive.' });
/** Account-export-scope value. */
export type AccountExportScope = z.infer<typeof AccountExportScope>;

/** The client request for a selective personal-data archive. */
export const AccountExportRequest = z
  .object({
    /** Categories the person wants in the archive. */
    categories: z.array(AccountExportCategory).min(1),
    /** Workspace ids, required only when the workspaces category is selected. */
    workspaceIds: z.array(z.string()),
  })
  .superRefine((request, ctx) => {
    const includesWorkspaces = request.categories.includes('workspaces');
    if (includesWorkspaces && request.workspaceIds.length === 0) {
      ctx.addIssue({
        code: 'custom',
        path: ['workspaceIds'],
        message: 'Select at least one workspace when exporting workspace data.',
      });
    }
    if (!includesWorkspaces && request.workspaceIds.length > 0) {
      ctx.addIssue({
        code: 'custom',
        path: ['workspaceIds'],
        message: 'Workspace selections require the workspaces category.',
      });
    }
  })
  .meta({
    id: 'AccountExportRequest',
    description: 'Requested categories and workspaces for a new archive.',
  });
/** Account-export-request value. */
export type AccountExportRequest = z.infer<typeof AccountExportRequest>;

/** Selectable archive settings and the caller's current workspace choices. */
export const AccountExportOptionsOut = z
  .object({
    /** Address that receives the ready-to-download notification. */
    deliveryEmail: z.email().describe('Email address used for archive-ready notifications.'),
    /** Current workspaces the caller can choose for a selective archive. */
    workspaces: z.array(AccountExportWorkspace).describe('Current selectable workspaces.'),
  })
  .meta({ id: 'AccountExportOptionsOut', description: 'Selectable data-export options.' });
/** Account-export-options value. */
export type AccountExportOptionsOut = z.infer<typeof AccountExportOptionsOut>;

/**
 * A shared organization the user must resolve before deleting their account.
 *
 * @remarks
 * The user is the *only* active owner of this shared (non-personal) org, so deleting their
 * account would orphan it. The UI guides them to transfer ownership or delete the org first;
 * the deletion endpoint refuses to schedule while any blocker remains.
 */
export const OwnershipBlocker = z
  .object({
    /** The blocking organization's id. */
    organizationId: z.string().describe('The id of the shared org that blocks account deletion.'),
    /** The organization's display name. */
    name: z
      .string()
      .describe(
        "The blocking organization's display name, shown so the user knows which org to resolve.",
      ),
    /** How many members the organization has (always > 1 — a shared org). */
    memberCount: z
      .number()
      .int()
      .describe(
        'How many members the org has — always greater than 1 (a shared org the caller solely owns; a personal/solo org would not block).',
      )
      .meta({ example: 4 }),
  })
  .meta({
    id: 'OwnershipBlocker',
    description: 'A shared org the user solely owns and must resolve before account deletion.',
  });
/** Ownership-blocker value. */
export type OwnershipBlocker = z.infer<typeof OwnershipBlocker>;

/**
 * The latest personal-data export's status (null when the user has never requested one).
 *
 * @remarks
 * `downloadUrl`/`readyAt`/`expiresAt` are populated only once `status === 'ready'`; they are
 * null while the export is `pending`, `failed`, or `expired`. The link stops being offered
 * after `expiresAt`.
 */
export const AccountExportOut = z
  .object({
    /** The export's stable id (its addressable resource id). */
    id: z
      .string()
      .describe(
        "The export job's stable id — its addressable resource id, used in `GET /me/account/exports/:id` and the `/file` download path.",
      ),
    /** Where the export is in its lifecycle. */
    status: AccountExportStatus.describe(
      "The export job's current lifecycle status (see AccountExportStatus).",
    ),
    /** Why the archive was requested. */
    origin: AccountExportOrigin.describe('Whether this is a manual or deletion-triggered archive.'),
    /** The data categories and workspaces this archive contains. */
    scope: AccountExportScope.describe('The persisted scope of this archive.'),
    /** ISO-8601 instant the export was requested. */
    requestedAt: z.string().describe('ISO-8601 instant the export was requested (queued).'),
    /** ISO-8601 instant the archive became downloadable, when ready; else null. */
    readyAt: z
      .string()
      .nullable()
      .describe(
        'ISO-8601 instant the archive became downloadable. Populated only when `status === ready`; null while pending/failed/expired.',
      ),
    /** ISO-8601 instant the download link stops being offered, when ready; else null. */
    expiresAt: z
      .string()
      .nullable()
      .describe(
        'ISO-8601 instant the download link stops being offered (after which `status` becomes `expired`). Populated only when ready; else null.',
      ),
    /** A fetchable URL for the generated archive, when ready; else null. */
    downloadUrl: z
      .string()
      .nullable()
      .describe(
        'A same-origin URL to the generated ZIP archive (the `/file` binary sub-resource), populated only when `status === ready`; null otherwise.',
      ),
  })
  .meta({ id: 'AccountExportOut', description: "The user's latest personal-data export status." });
/** Account-export value. */
export type AccountExportOut = z.infer<typeof AccountExportOut>;

/** The user's personal-data exports, newest first. */
export const AccountExportListOut = z
  .object({
    items: z
      .array(AccountExportOut)
      .describe(
        "The caller's export jobs ordered newest-first by `requestedAt`. Empty when they have never requested an export.",
      ),
  })
  .meta({
    id: 'AccountExportListOut',
    description: "The user's personal-data exports, newest first.",
  });
/** Account-export-list value. */
export type AccountExportListOut = z.infer<typeof AccountExportListOut>;

/**
 * The user's recovery-code (backup-code) status for the Security settings surface.
 *
 * @remarks
 * Derived server-side from the `twoFactor` plugin: `enabled` is whether recovery codes have been
 * generated, `remaining` is how many unused codes are left (codes are consumed one-per-recovery),
 * and `generatedAt` is when they were last (re)generated. The codes themselves are NEVER returned
 * here — only shown once at generation time. `remaining` is 0 and `generatedAt` is null whenever
 * `enabled` is false.
 */
export const RecoveryCodesStatusOut = z
  .object({
    /** Whether the user has generated recovery codes. */
    enabled: z
      .boolean()
      .describe(
        'Whether the user has a generated set of recovery codes. False before they have ever generated any.',
      ),
    /** How many unused recovery codes remain (0 when not enabled). */
    remaining: z
      .number()
      .int()
      .describe(
        'How many unused recovery codes remain (codes are consumed one per recovery). 0 when `enabled` is false.',
      )
      .meta({ example: 8 }),
    /** ISO-8601 instant the codes were last (re)generated, or null when not enabled. */
    generatedAt: z
      .string()
      .nullable()
      .describe(
        'ISO-8601 instant the codes were last (re)generated, or null when `enabled` is false.',
      ),
  })
  .meta({
    id: 'RecoveryCodesStatusOut',
    description: "The user's account-recovery (backup) code status.",
  });
/** Recovery-codes-status value. */
export type RecoveryCodesStatusOut = z.infer<typeof RecoveryCodesStatusOut>;

/**
 * Freshly generated recovery codes, returned exactly once by `POST /v1/me/recovery-codes`.
 *
 * @remarks
 * This is the ONLY response that ever carries the plaintext codes — they are shown to the user
 * once at generation and are never retrievable again (the status read returns only a count).
 * Generating replaces any previous set.
 */
export const RecoveryCodesOut = z
  .object({
    /** The plaintext recovery codes, to display/save once. */
    codes: z
      .array(z.string())
      .describe(
        'The freshly generated plaintext recovery (backup) codes, returned exactly once. Display them for the user to save — they are never retrievable again, and generating replaces any prior set.',
      )
      .meta({ example: ['a1b2-c3d4', 'e5f6-g7h8'] }),
  })
  .meta({ id: 'RecoveryCodesOut', description: 'Freshly generated recovery codes (shown once).' });
/** Recovery-codes value. */
export type RecoveryCodesOut = z.infer<typeof RecoveryCodesOut>;

/**
 * The account end-of-life status powering the Danger zone + Export surfaces in one read.
 */
export const AccountStatusOut = z
  .object({
    /** Whether the account is `active` or scheduled for deletion (`pending_deletion`). */
    deletionState: AccountDeletionState.describe(
      'Whether the account is `active` or scheduled for deletion (`pending_deletion`).',
    ),
    /** ISO-8601 instant deletion was scheduled, when pending; else null. */
    deletionRequestedAt: z
      .string()
      .nullable()
      .describe(
        'ISO-8601 instant deletion was scheduled. Set while `pending_deletion`; null when `active`.',
      ),
    /** ISO-8601 instant the grace window closes and the purge runs, when pending; else null. */
    deleteAfterAt: z
      .string()
      .nullable()
      .describe(
        'ISO-8601 instant the 14-day grace window closes and the cron purge irreversibly deletes the account. Set while `pending_deletion`; null when `active`. The account can be recovered any time before this.',
      ),
    /** Shared orgs the user solely owns that block deletion until resolved (empty when none). */
    blockers: z
      .array(OwnershipBlocker)
      .describe(
        'Shared orgs the user is the sole active owner of, which must be transferred or deleted before deletion can be scheduled. Empty when there are none (deletion is allowed).',
      ),
    /** The latest export job, or null if the user has never requested one. */
    export: AccountExportOut.nullable().describe(
      "The user's most recent export job (status + download link when ready), or null when they have never requested one.",
    ),
  })
  .meta({ id: 'AccountStatusOut', description: "The user's account end-of-life status." });
/** Account-status value. */
export type AccountStatusOut = z.infer<typeof AccountStatusOut>;
