-- Re-seat every column stored with the `notion_person` representation.
--
-- That representation used to provision the column itself as a Notion `people` property. It now
-- provisions as `rich_text`, with the native people property added BESIDE it as a derived
-- companion column — because a `people` property cannot hold anyone outside the Notion workspace,
-- so substituting it dropped every person without a Notion account from the database.
--
-- Clearing the parent's `propertyId` alone would have been half a migration: the people property
-- already in the user's Notion database would be orphaned, and no companion binding exists to
-- claim it, because companions are only ever generated by a designer save. A workspace that chose
-- "Notion person" months ago would silently lose its @-mentionable column and get plain text.
--
-- So the property changes hands. The COMPANION adopts the parent's `propertyId` — it is the same
-- Notion people property, now correctly labelled — and the parent is unbound so the next
-- provisioning pass issues it a fresh rich-text property beside it. Orders are doubled to leave an
-- integer slot for each companion next to its parent (`order` is declared `.int()`).
--
-- Skipped for any column that already has a companion, which is a design saved since the code
-- change: re-running the hand-over there would unbind a healthy rich-text property.
UPDATE "notion_mirror_database" AS d
SET "property_map" = (
  SELECT jsonb_object_agg(entry.key, entry.value)
  FROM (
    SELECT
      b.key AS key,
      CASE
        WHEN b.value->>'representation' = 'notion_person'
             AND NOT d."property_map" ? (b.key || 'NotionPerson')
          THEN (b.value - 'propertyId')
               || jsonb_build_object('order', ((b.value->>'order')::int) * 2)
        ELSE b.value || jsonb_build_object('order', ((b.value->>'order')::int) * 2)
      END AS value
    FROM jsonb_each(d."property_map") AS b

    UNION ALL

    SELECT
      b.key || 'NotionPerson' AS key,
      -- `jsonb_strip_nulls` drops `propertyId` when the parent never had one (an unprovisioned
      -- design), which is exactly the shape a fresh companion has.
      jsonb_strip_nulls(jsonb_build_object(
        'field', b.key || 'NotionPerson',
        'title', (b.value->>'title') || ' (Notion)',
        'kind', 'people',
        'order', ((b.value->>'order')::int) * 2 + 1,
        'propertyId', b.value->'propertyId'
      )) AS value
    FROM jsonb_each(d."property_map") AS b
    WHERE b.value->>'representation' = 'notion_person'
      AND NOT d."property_map" ? (b.key || 'NotionPerson')
  ) AS entry
)
-- Only rows that actually need the hand-over. Without this guard the order-doubling would run on
-- every design in the table, and `jsonb_object_agg` over an empty map would return NULL.
WHERE EXISTS (
  SELECT 1
  FROM jsonb_each(d."property_map") AS b
  WHERE b.value->>'representation' = 'notion_person'
    AND NOT d."property_map" ? (b.key || 'NotionPerson')
);
