ALTER TABLE "entity_display" ADD COLUMN "glyph_kind" text;--> statement-breakpoint
ALTER TABLE "entity_display" ADD COLUMN "glyph_value" text;--> statement-breakpoint
UPDATE "entity_display" SET "glyph_kind" = 'symbol', "glyph_value" = CASE "icon_key"
  WHEN 'target' THEN 'track_changes' WHEN 'flag' THEN 'outlined_flag'
  WHEN 'layers' THEN 'layers' WHEN 'folder' THEN 'folder_open'
  WHEN 'workflow' THEN 'account_tree' WHEN 'globe' THEN 'public'
  WHEN 'users' THEN 'groups' WHEN 'sparkles' THEN 'auto_awesome'
  WHEN 'bus' THEN 'directions_bus' WHEN 'train' THEN 'train'
  WHEN 'subway' THEN 'subway' WHEN 'route' THEN 'route' WHEN 'map' THEN 'map'
  WHEN 'campaign' THEN 'campaign' WHEN 'school' THEN 'school' WHEN 'book' THEN 'menu_book'
  WHEN 'event' THEN 'event' WHEN 'handshake' THEN 'handshake'
  WHEN 'government' THEN 'account_balance' WHEN 'vote' THEN 'how_to_vote'
  WHEN 'community' THEN 'diversity_3' WHEN 'hub' THEN 'hub'
  WHEN 'psychology' THEN 'psychology' WHEN 'idea' THEN 'lightbulb'
  WHEN 'launch' THEN 'rocket_launch' WHEN 'language' THEN 'language' WHEN 'park' THEN 'park'
  WHEN 'building' THEN 'apartment' WHEN 'engineering' THEN 'engineering'
  WHEN 'construction' THEN 'construction' WHEN 'timeline' THEN 'timeline'
  WHEN 'analytics' THEN 'analytics' WHEN 'insights' THEN 'insights'
  WHEN 'growth' THEN 'trending_up' WHEN 'verified' THEN 'verified'
  WHEN 'security' THEN 'security' WHEN 'energy' THEN 'bolt' WHEN 'favorite' THEN 'favorite'
  WHEN 'star' THEN 'star' WHEN 'explore' THEN 'explore' WHEN 'travel' THEN 'travel_explore'
  WHEN 'award' THEN 'workspace_premium' WHEN 'volunteering' THEN 'volunteer_activism'
  WHEN 'forum' THEN 'forum' WHEN 'voice' THEN 'record_voice_over'
  WHEN 'podcast' THEN 'podcasts' WHEN 'article' THEN 'article' WHEN 'policy' THEN 'policy'
  WHEN 'justice' THEN 'gavel' WHEN 'library' THEN 'local_library'
  WHEN 'pedestrian' THEN 'emoji_people' WHEN 'mail' THEN 'mail' WHEN 'chat' THEN 'chat'
  WHEN 'phone' THEN 'phone' WHEN 'inbox' THEN 'inbox' WHEN 'send' THEN 'send'
  WHEN 'camera' THEN 'camera_alt' WHEN 'image' THEN 'image' WHEN 'video' THEN 'videocam'
  WHEN 'music' THEN 'music_note' WHEN 'film' THEN 'movie'
  WHEN 'wallet' THEN 'account_balance_wallet' WHEN 'payments' THEN 'payments'
  WHEN 'receipt' THEN 'receipt_long' WHEN 'bank' THEN 'account_balance'
  WHEN 'savings' THEN 'savings' WHEN 'science' THEN 'science' WHEN 'biotech' THEN 'biotech'
  WHEN 'experiment' THEN 'vaccines' WHEN 'atom' THEN 'bubble_chart'
  WHEN 'leaf' THEN 'energy_savings_leaf' WHEN 'tree' THEN 'forest'
  WHEN 'flower' THEN 'local_florist' WHEN 'water' THEN 'water_drop'
  WHEN 'mountain' THEN 'landscape' WHEN 'sun' THEN 'wb_sunny' WHEN 'cloud' THEN 'cloud'
  WHEN 'car' THEN 'directions_car' WHEN 'flight' THEN 'flight' WHEN 'rocket' THEN 'rocket'
  WHEN 'bike' THEN 'directions_bike' WHEN 'boat' THEN 'directions_boat'
  WHEN 'build' THEN 'build' WHEN 'wrench' THEN 'handyman' WHEN 'settings' THEN 'settings'
  WHEN 'tune' THEN 'tune' WHEN 'hammer' THEN 'hardware' WHEN 'person' THEN 'person'
  WHEN 'group' THEN 'group' WHEN 'contacts' THEN 'contacts' WHEN 'badge' THEN 'badge'
  WHEN 'note' THEN 'note' WHEN 'archive' THEN 'archive' WHEN 'clipboard' THEN 'content_paste'
  WHEN 'lock' THEN 'lock' WHEN 'shield' THEN 'shield' WHEN 'key' THEN 'key'
  WHEN 'fingerprint' THEN 'fingerprint' WHEN 'code' THEN 'code' WHEN 'terminal' THEN 'terminal'
  WHEN 'database' THEN 'storage' WHEN 'bug' THEN 'bug_report'
END;--> statement-breakpoint
ALTER TABLE "entity_display" ADD CONSTRAINT "entity_display_glyph_pair_check" CHECK (("entity_display"."glyph_kind" is null and "entity_display"."glyph_value" is null) or ("entity_display"."glyph_kind" is not null and "entity_display"."glyph_value" is not null));--> statement-breakpoint
ALTER TABLE "entity_display" ADD CONSTRAINT "entity_display_glyph_shape_check" CHECK ("entity_display"."glyph_kind" is null or ("entity_display"."glyph_kind" = 'symbol' and "entity_display"."glyph_value" ~ '^[a-z0-9]+(_[a-z0-9]+)*$') or ("entity_display"."glyph_kind" = 'emoji' and "entity_display"."glyph_value" ~ '^[0-9A-F]{2,6}(-[0-9A-F]{2,6})*$'));
