import { agentServer, mcpServer, stripeServer, voiceServer } from './slices';
import type { VarSpec } from './registry-types';

/** Stripe + MCP + agent + voice/telephony variable specs. */
export const SERVICE_VARS: readonly VarSpec[] = [
  // stripe
  {
    name: 'STRIPE_SECRET_KEY',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_SECRET_KEY,
    where: 'Stripe secret key (sk_...) — required when BILLING_ENABLED=true',
    sensitive: true,
  },
  {
    name: 'STRIPE_PUBLISHABLE_KEY',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_PUBLISHABLE_KEY,
    where: 'Stripe browser-safe publishable key (pk_...) exposed through GET /v1/config',
  },
  {
    name: 'STRIPE_WEBHOOK_SECRET',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_WEBHOOK_SECRET,
    where: 'Stripe webhook signing secret (whsec_...) from `stripe listen`',
    sensitive: true,
  },
  {
    name: 'DOCKET_PRICE_LOOKUP_DOCKET_PRO',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.DOCKET_PRICE_LOOKUP_DOCKET_PRO,
    where: 'Stripe price lookup_key for Docket Pro monthly billing',
  },
  {
    name: 'STRIPE_PRICE_DOCKET_PRO',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_PRICE_DOCKET_PRO,
    where: 'Stripe price id (price_...) for Docket Pro monthly billing',
  },
  {
    name: 'DOCKET_PRICE_LOOKUP_TEAM',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    // eslint-disable-next-line @typescript-eslint/no-deprecated -- the registry must document the one-release alias
    zod: stripeServer.DOCKET_PRICE_LOOKUP_TEAM,
    where: 'Legacy one-release alias for DOCKET_PRICE_LOOKUP_DOCKET_PRO',
  },
  {
    name: 'DOCKET_PRICE_LOOKUP_TEAM_ANNUAL',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    // eslint-disable-next-line @typescript-eslint/no-deprecated -- the registry must document the retired annual alias
    zod: stripeServer.DOCKET_PRICE_LOOKUP_TEAM_ANNUAL,
    where: 'Stripe price lookup_key for the annual Team plan',
  },
  {
    name: 'STRIPE_PRICE_TEAM',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    // eslint-disable-next-line @typescript-eslint/no-deprecated -- the registry must document the one-release alias
    zod: stripeServer.STRIPE_PRICE_TEAM,
    where: 'Legacy one-release alias for STRIPE_PRICE_DOCKET_PRO',
  },
  {
    name: 'STRIPE_BILLING_PORTAL_CONFIG_ID',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_BILLING_PORTAL_CONFIG_ID,
    where: 'Stripe billing portal configuration id',
  },
  {
    name: 'BILLING_ENABLED',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: stripeServer.BILLING_ENABLED,
    where: 'true|false — gate that requires the Stripe keys when on (default false)',
  },

  // mcp
  {
    name: 'MCP_ISSUER_URL',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.MCP_ISSUER_URL,
    where: 'OAuth issuer URL for the MCP server (defaults to API_URL)',
  },
  {
    name: 'MCP_RESOURCE_URL',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.MCP_RESOURCE_URL,
    where: 'Canonical MCP resource URL (defaults to ${API_URL}/mcp)',
  },
  {
    name: 'OIDC_LOGIN_PAGE_URL',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.OIDC_LOGIN_PAGE_URL,
    where: 'Login page URL the OIDC provider redirects to (defaults to ${WEB_URL}/sign-in)',
  },
  {
    name: 'MCP_TASKS_ENABLED',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: mcpServer.MCP_TASKS_ENABLED,
    where: 'true|false — enable the MCP Tasks utility (requires MCP_SESSION_STORE_URL)',
  },
  {
    name: 'MCP_SESSION_STORE_URL',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.MCP_SESSION_STORE_URL,
    where: 'Backing store URL for resumable MCP sessions',
  },

  // agent
  {
    name: 'ANTHROPIC_API_KEY',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.ANTHROPIC_API_KEY,
    where: 'Anthropic API key for the built-in Athena runtime',
    sensitive: true,
  },
  {
    name: 'CREDENTIALS_ENCRYPTION_KEY',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.CREDENTIALS_ENCRYPTION_KEY,
    where: 'Base64 32-byte key sealing org-held remote-MCP credentials (AES-256-GCM)',
    sensitive: true,
  },
  {
    name: 'AGENT_MAX_TURNS',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: agentServer.AGENT_MAX_TURNS,
    where: 'Per-session turn budget for the Athena agentic loop (e.g. 24)',
  },
  {
    name: 'ATHENA_MAX_CONCURRENT_RUNS',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.ATHENA_MAX_CONCURRENT_RUNS,
    where: 'Per-user Athena run limit (default 8, maximum 64)',
  },
  {
    name: 'ATHENA_ASYNC_RUNNER_ENABLED',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: agentServer.ATHENA_ASYNC_RUNNER_ENABLED,
    where:
      'true|false — dispatch personal Athena generations through Cloudflare Queues and Workflows',
  },
  {
    name: 'CLOUDFLARE_ATHENA_RUNNER_URL',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.CLOUDFLARE_ATHENA_RUNNER_URL,
    where: 'Cloudflare runner Worker origin; required when ATHENA_ASYNC_RUNNER_ENABLED=true',
  },
  {
    name: 'CLOUDFLARE_TO_DOCKET_HMAC_SECRET',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.CLOUDFLARE_TO_DOCKET_HMAC_SECRET,
    where: 'HMAC secret authenticating Cloudflare execution callbacks to Docket',
    sensitive: true,
  },
  {
    name: 'DOCKET_TO_CLOUDFLARE_HMAC_SECRET',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.DOCKET_TO_CLOUDFLARE_HMAC_SECRET,
    where: 'Distinct HMAC secret authenticating Docket execution dispatches to Cloudflare',
    sensitive: true,
  },

  // voice + telephony
  {
    name: 'OPENAI_API_KEY',
    slice: 'voice',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: voiceServer.OPENAI_API_KEY,
    where: 'Realtime speech credential for Athena voice mode; absent runs the fixture double',
    sensitive: true,
  },
  {
    name: 'VOICE_REALTIME_MODEL',
    slice: 'voice',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: voiceServer.VOICE_REALTIME_MODEL,
    where: 'Realtime model id for Athena voice mode',
  },
  {
    name: 'VOICE_REALTIME_VOICE',
    slice: 'voice',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: voiceServer.VOICE_REALTIME_VOICE,
    where: 'Synthesized voice id for Athena voice mode',
  },
  {
    name: 'TWILIO_ACCOUNT_SID',
    slice: 'voice',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: voiceServer.TWILIO_ACCOUNT_SID,
    where: 'Twilio account that owns the Athena phone number',
  },
  {
    name: 'TWILIO_AUTH_TOKEN',
    slice: 'voice',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: voiceServer.TWILIO_AUTH_TOKEN,
    where: 'Twilio auth token; every inbound call webhook signature is verified against it',
    sensitive: true,
  },
  {
    name: 'TWILIO_PHONE_NUMBER',
    slice: 'voice',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: voiceServer.TWILIO_PHONE_NUMBER,
    where: 'The E.164 number people call to reach Athena',
  },
] as const;
