import { clientShared, connectorServer, hostsServer, opsServer } from './slices';
import { APP, type VarSpec } from './registry-types';

/** Ops + connector + client variable specs. */
export const INFRA_VARS: readonly VarSpec[] = [
  // ops
  {
    name: 'CRON_SECRET',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: opsServer.CRON_SECRET,
    where: 'Shared secret guarding the cron endpoints',
    sensitive: true,
    generate: 'openssl rand -hex 24',
  },
  {
    name: 'SENTRY_DSN',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SENTRY_DSN,
    where: 'Sentry DSN (absent → error reporting disabled)',
  },
  {
    name: 'BLOB_READ_WRITE_TOKEN',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.BLOB_READ_WRITE_TOKEN,
    where: 'Vercel Blob read/write token for export artifacts',
    sensitive: true,
  },
  {
    name: 'EXPORT_BUCKET_URL',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.EXPORT_BUCKET_URL,
    where: 'S3-compatible bucket URL for exports (paired with token)',
  },
  {
    name: 'EXPORT_BUCKET_TOKEN',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.EXPORT_BUCKET_TOKEN,
    where: 'Bucket access token for exports',
    sensitive: true,
  },
  {
    name: 'RESEND_API_KEY',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.RESEND_API_KEY,
    where:
      'Resend API key — production transactional email over HTTPS, and reading inbound message bodies.',
    sensitive: true,
  },
  {
    name: 'RESEND_INBOUND_WEBHOOK_SECRET',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.RESEND_INBOUND_WEBHOOK_SECRET,
    where:
      "Svix signing secret (whsec_…) for Athena's inbound-mail webhook. Required in production with RESEND_API_KEY; absent ⇒ the offline fixture receiver.",
    sensitive: true,
  },
  {
    name: 'RESEND_RECEIVING_API_BASE',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.RESEND_RECEIVING_API_BASE,
    where:
      "Inbound receiving-API base. Absent ⇒ Resend's own https://api.resend.com/emails/receiving.",
  },
  {
    name: 'SMTP_HOST',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_HOST,
    where:
      'SMTP relay host for transactional email. Local: localhost (Mailpit). Absent → mock CaptureMailer.',
  },
  {
    name: 'SMTP_PORT',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_PORT,
    where: 'SMTP port (587 STARTTLS, 465 implicit TLS, 1025 Mailpit). Defaults to 587 when absent.',
  },
  {
    name: 'SMTP_SECURE',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_SECURE,
    where: 'true|false — implicit TLS from connect. Defaults to true only on port 465.',
  },
  {
    name: 'SMTP_USER',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_USER,
    where: 'SMTP auth username (omit for unauthenticated relays such as Mailpit).',
  },
  {
    name: 'SMTP_PASS',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_PASS,
    where: 'SMTP auth password (omit for unauthenticated relays such as Mailpit).',
    sensitive: true,
  },
  {
    name: 'MAIL_FROM',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.MAIL_FROM,
    where:
      'From-address for transactional email, e.g. "Athena <no-reply@$ATHENA_INBOUND_MAIL_HOST>". ' +
      'Must be a Docket/Athena-owned mail domain with SPF, DKIM, and DMARC published (GEN-28).',
  },
  {
    name: 'SMS_ENDPOINT',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMS_ENDPOINT,
    where: 'HTTP SMS provider send endpoint. Absent → mock CaptureSmsSender.',
  },
  {
    name: 'SMS_API_KEY',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMS_API_KEY,
    where: 'HTTP SMS provider API key/token.',
    sensitive: true,
  },
  {
    name: 'SMS_FROM',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMS_FROM,
    where: 'SMS sender number configured with the provider.',
  },
  {
    name: 'PUSH_ENDPOINT',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.PUSH_ENDPOINT,
    where: 'HTTP push provider send endpoint. Absent → mock CapturePushSender.',
  },
  {
    name: 'PUSH_API_KEY',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.PUSH_API_KEY,
    where: 'HTTP push provider API key/token.',
    sensitive: true,
  },
  {
    name: 'PUSH_APP_ID',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.PUSH_APP_ID,
    where: 'Push provider application id/bundle id.',
  },
  {
    name: 'STAFF_BOOTSTRAP_EMAILS',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.STAFF_BOOTSTRAP_EMAILS,
    where:
      'Dev-only operator allowlist: comma-separated email[:role] (default superadmin). Ignored in production.',
  },

  // connector (per-provider API-base overrides; the OAuth token is per-connection, not env)
  {
    name: 'GITHUB_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.GITHUB_API_BASE,
    where:
      'GitHub REST API base override for self-hosted/Enterprise (e.g. https://ghe.example.com/api/v3). Absent ⇒ https://api.github.com',
  },
  {
    name: 'LINEAR_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.LINEAR_API_BASE,
    where: 'Linear GraphQL API base override. Absent ⇒ https://api.linear.app',
  },
  {
    name: 'GOOGLE_GMAIL_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.GOOGLE_GMAIL_API_BASE,
    where: 'Gmail REST API base override. Absent ⇒ https://gmail.googleapis.com/gmail/v1',
  },
  {
    name: 'GOOGLE_CALENDAR_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.GOOGLE_CALENDAR_API_BASE,
    where:
      'Google Calendar REST API base override. Absent ⇒ https://www.googleapis.com/calendar/v3',
  },
  {
    name: 'GOOGLE_TASKS_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.GOOGLE_TASKS_API_BASE,
    where: 'Google Tasks REST API base override. Absent ⇒ https://tasks.googleapis.com/tasks/v1',
  },

  // hosts — the user-facing domain contract (`packages/env/src/hosts.ts` resolves these)
  {
    name: 'PUBLIC_ROOT_DOMAIN',
    slice: 'hosts',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: hostsServer.PUBLIC_ROOT_DOMAIN,
    where:
      'The apex Docket owns, e.g. docket.place. Every other host derives from it. Absent ⇒ derived from WEB_URL.',
  },
  {
    name: 'ADMIN_URL',
    slice: 'hosts',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: hostsServer.ADMIN_URL,
    where: 'Operator back-office origin. Absent ⇒ https://admin.<PUBLIC_ROOT_DOMAIN>',
  },
  {
    name: 'PUBLIC_BRIEF_HOST',
    slice: 'hosts',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: hostsServer.PUBLIC_BRIEF_HOST,
    where: 'Host serving slug-based published briefs. Absent ⇒ briefs.<PUBLIC_ROOT_DOMAIN>',
  },
  {
    name: 'ATHENA_INBOUND_MAIL_HOST',
    slice: 'hosts',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: hostsServer.ATHENA_INBOUND_MAIL_HOST,
    where:
      'Domain Athena receives mail on (needs MX at a verified provider). Never derived — absent ⇒ the inbox is unconfigured.',
  },
  {
    name: 'CUSTOM_DOMAIN_CNAME_TARGET',
    slice: 'hosts',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: hostsServer.CUSTOM_DOMAIN_CNAME_TARGET,
    where: "Host a workspace's verified custom domain CNAMEs to. Absent ⇒ the brief host.",
  },
  {
    name: 'SUPPORT_EMAIL',
    slice: 'hosts',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: hostsServer.SUPPORT_EMAIL,
    where: 'Support address the legal pages publish. Absent ⇒ support@<PUBLIC_ROOT_DOMAIN>',
  },

  // client
  {
    name: 'NEXT_PUBLIC_API_URL',
    slice: 'client',
    scope: 'client',
    targets: APP,
    required: true,
    zod: clientShared.NEXT_PUBLIC_API_URL,
    where: 'Public API base URL exposed to the browser',
  },
  {
    name: 'NEXT_PUBLIC_APP_URL',
    slice: 'client',
    scope: 'client',
    targets: APP,
    required: true,
    zod: clientShared.NEXT_PUBLIC_APP_URL,
    where: 'Public web app base URL exposed to the browser',
  },
  {
    name: 'NEXT_PUBLIC_PASSKEY_RP_ID',
    slice: 'client',
    scope: 'client',
    targets: ['web', 'admin'],
    required: true,
    zod: clientShared.NEXT_PUBLIC_PASSKEY_RP_ID,
    where: 'Browser-visible mirror of BETTER_AUTH_PASSKEY_RP_ID',
  },
  {
    name: 'NEXT_PUBLIC_ROOT_DOMAIN',
    slice: 'client',
    scope: 'client',
    targets: APP,
    required: false,
    zod: clientShared.NEXT_PUBLIC_ROOT_DOMAIN,
    where:
      'Browser-visible mirror of PUBLIC_ROOT_DOMAIN. Absent ⇒ derived from NEXT_PUBLIC_APP_URL.',
  },
  {
    name: 'NEXT_PUBLIC_BRIEF_HOST',
    slice: 'client',
    scope: 'client',
    targets: APP,
    required: false,
    zod: clientShared.NEXT_PUBLIC_BRIEF_HOST,
    where: 'Browser-visible mirror of PUBLIC_BRIEF_HOST, for links to a published brief.',
  },
  {
    name: 'NEXT_PUBLIC_SUPPORT_EMAIL',
    slice: 'client',
    scope: 'client',
    targets: APP,
    required: false,
    zod: clientShared.NEXT_PUBLIC_SUPPORT_EMAIL,
    where: 'Support address printed on the privacy and terms pages. Absent ⇒ support@<apex>.',
  },
] as const;
