import { authServer, dbServer, sharedServer } from './slices';
import { ALL, type VarSpec } from './registry-types';

/** Shared + database + auth variable specs. */
export const CORE_VARS: readonly VarSpec[] = [
  // shared
  {
    name: 'NODE_ENV',
    slice: 'shared',
    scope: 'server',
    targets: ALL,
    required: false,
    zod: sharedServer.NODE_ENV,
    where: 'development | test | production',
  },
  {
    name: 'APP_MODE',
    slice: 'shared',
    scope: 'server',
    targets: ALL,
    required: true,
    zod: sharedServer.APP_MODE,
    where: 'local | test | production — local/test force the mock boundary adapters',
  },
  {
    name: 'API_URL',
    slice: 'shared',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: sharedServer.API_URL,
    where: 'Public base URL of the Hono API',
  },
  {
    name: 'PORT',
    slice: 'shared',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: sharedServer.PORT,
    where: 'API listen port (default 3000)',
  },

  // db
  {
    name: 'DATABASE_URL',
    slice: 'db',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: dbServer.DATABASE_URL,
    where:
      'Postgres pooled URL. Local zero-account build: a pglite path e.g. pglite://.data/docket. Prod: Neon pooled URL.',
    sensitive: true,
  },
  {
    name: 'DATABASE_URL_UNPOOLED',
    slice: 'db',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: dbServer.DATABASE_URL_UNPOOLED,
    where: 'Unpooled URL used for migrations (falls back to DATABASE_URL).',
    sensitive: true,
  },

  // auth
  {
    name: 'BETTER_AUTH_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_SECRET,
    where: 'openssl rand -base64 32 (≥32 chars)',
    sensitive: true,
    generate: 'openssl rand -base64 32',
  },
  {
    name: 'BETTER_AUTH_URL',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_URL,
    where: 'Base URL Better Auth issues cookies/redirects for',
  },
  {
    name: 'BETTER_AUTH_TRUSTED_ORIGINS',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.BETTER_AUTH_TRUSTED_ORIGINS,
    where: 'CSV of trusted browser origins for CORS + cookies',
  },
  {
    name: 'BETTER_AUTH_ALLOWED_HOSTS',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.BETTER_AUTH_ALLOWED_HOSTS,
    where:
      'CSV of host patterns Better Auth issues cookies/redirects for (wildcards ok, e.g. *.vercel.app); enables dynamic base URL when set',
  },
  {
    name: 'BETTER_AUTH_PASSKEY_RP_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_PASSKEY_RP_ID,
    where: 'WebAuthn relying-party id (the registrable domain; localhost in dev)',
  },
  {
    name: 'BETTER_AUTH_PASSKEY_RP_NAME',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_PASSKEY_RP_NAME,
    where: "WebAuthn relying-party display name (default 'Docket')",
  },
  {
    name: 'GOOGLE_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GOOGLE_CLIENT_ID,
    where: 'Google Cloud OAuth client id (absent → provider hidden)',
  },
  {
    name: 'GOOGLE_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GOOGLE_CLIENT_SECRET,
    where: 'Google Cloud OAuth client secret',
    sensitive: true,
  },
  {
    name: 'GITHUB_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_CLIENT_ID,
    where: 'GitHub OAuth app client id (absent → provider hidden)',
  },
  {
    name: 'GITHUB_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_CLIENT_SECRET,
    where: 'GitHub OAuth app client secret',
    sensitive: true,
  },
  {
    name: 'LINEAR_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_CLIENT_ID,
    where: 'Linear OAuth2 application client id (genericOAuth)',
  },
  {
    name: 'LINEAR_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_CLIENT_SECRET,
    where: 'Linear OAuth2 application client secret',
    sensitive: true,
  },
] as const;
