import { clientShared, connectorServer, opsServer } from './slices';
import { APP, type VarSpec } from './registry-types';

/** Ops + connector + client variable specs. */
export const INFRA_VARS: readonly VarSpec[] = [
  // ops
  {
    name: 'CRON_SECRET',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: opsServer.CRON_SECRET,
    where: 'Shared secret guarding the cron endpoints',
    sensitive: true,
    generate: 'openssl rand -hex 24',
  },
  {
    name: 'SENTRY_DSN',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SENTRY_DSN,
    where: 'Sentry DSN (absent → error reporting disabled)',
  },
  {
    name: 'BLOB_READ_WRITE_TOKEN',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.BLOB_READ_WRITE_TOKEN,
    where: 'Vercel Blob read/write token for export artifacts',
    sensitive: true,
  },
  {
    name: 'EXPORT_BUCKET_URL',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.EXPORT_BUCKET_URL,
    where: 'S3-compatible bucket URL for exports (paired with token)',
  },
  {
    name: 'EXPORT_BUCKET_TOKEN',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.EXPORT_BUCKET_TOKEN,
    where: 'Bucket access token for exports',
    sensitive: true,
  },
  {
    name: 'SMTP_HOST',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_HOST,
    where:
      'SMTP relay host for transactional email. Local: localhost (Mailpit). Absent → mock CaptureMailer.',
  },
  {
    name: 'SMTP_PORT',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_PORT,
    where: 'SMTP port (587 STARTTLS, 465 implicit TLS, 1025 Mailpit). Defaults to 587 when absent.',
  },
  {
    name: 'SMTP_SECURE',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_SECURE,
    where: 'true|false — implicit TLS from connect. Defaults to true only on port 465.',
  },
  {
    name: 'SMTP_USER',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_USER,
    where: 'SMTP auth username (omit for unauthenticated relays such as Mailpit).',
  },
  {
    name: 'SMTP_PASS',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.SMTP_PASS,
    where: 'SMTP auth password (omit for unauthenticated relays such as Mailpit).',
    sensitive: true,
  },
  {
    name: 'MAIL_FROM',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.MAIL_FROM,
    where: 'From-address for transactional email, e.g. "Docket <no-reply@docket.dev>".',
  },
  {
    name: 'STAFF_BOOTSTRAP_EMAILS',
    slice: 'ops',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: opsServer.STAFF_BOOTSTRAP_EMAILS,
    where:
      'Dev-only operator allowlist: comma-separated email[:role] (default superadmin). Ignored in production.',
  },

  // connector (per-provider API-base overrides; the OAuth token is per-connection, not env)
  {
    name: 'GITHUB_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.GITHUB_API_BASE,
    where:
      'GitHub REST API base override for self-hosted/Enterprise (e.g. https://ghe.example.com/api/v3). Absent ⇒ https://api.github.com',
  },
  {
    name: 'LINEAR_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.LINEAR_API_BASE,
    where: 'Linear GraphQL API base override. Absent ⇒ https://api.linear.app',
  },
  {
    name: 'GOOGLE_DRIVE_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.GOOGLE_DRIVE_API_BASE,
    where: 'Google Drive REST API base override. Absent ⇒ https://www.googleapis.com/drive/v3',
  },
  {
    name: 'GOOGLE_GMAIL_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.GOOGLE_GMAIL_API_BASE,
    where: 'Gmail REST API base override. Absent ⇒ https://gmail.googleapis.com/gmail/v1',
  },
  {
    name: 'GOOGLE_CALENDAR_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.GOOGLE_CALENDAR_API_BASE,
    where:
      'Google Calendar REST API base override. Absent ⇒ https://www.googleapis.com/calendar/v3',
  },
  {
    name: 'GOOGLE_TASKS_API_BASE',
    slice: 'connector',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: connectorServer.GOOGLE_TASKS_API_BASE,
    where: 'Google Tasks REST API base override. Absent ⇒ https://tasks.googleapis.com/tasks/v1',
  },

  // client
  {
    name: 'NEXT_PUBLIC_API_URL',
    slice: 'client',
    scope: 'client',
    targets: APP,
    required: true,
    zod: clientShared.NEXT_PUBLIC_API_URL,
    where: 'Public API base URL exposed to the browser',
  },
  {
    name: 'NEXT_PUBLIC_APP_URL',
    slice: 'client',
    scope: 'client',
    targets: APP,
    required: true,
    zod: clientShared.NEXT_PUBLIC_APP_URL,
    where: 'Public web app base URL exposed to the browser',
  },
  {
    name: 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY',
    slice: 'client',
    scope: 'client',
    targets: APP,
    required: false,
    zod: clientShared.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    where: 'Stripe publishable key (pk_...) for embedded Checkout',
  },
] as const;
