import { authServer, dbServer, sharedServer } from './slices';
import { ALL, type VarSpec } from './registry-types';

/** Shared + database + auth variable specs. */
export const CORE_VARS: readonly VarSpec[] = [
  // shared
  {
    name: 'NODE_ENV',
    slice: 'shared',
    scope: 'server',
    targets: ALL,
    required: false,
    zod: sharedServer.NODE_ENV,
    where: 'development | test | production',
  },
  {
    name: 'APP_MODE',
    slice: 'shared',
    scope: 'server',
    targets: ALL,
    required: true,
    zod: sharedServer.APP_MODE,
    where: 'local | test | production — local/test force the mock boundary adapters',
  },
  {
    name: 'API_URL',
    slice: 'shared',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: sharedServer.API_URL,
    where: 'Public base URL of the Hono API',
  },
  {
    name: 'WEB_URL',
    slice: 'shared',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: sharedServer.WEB_URL,
    where:
      'Public origin of the product web app (sign-in/consent pages; MCP OAuth derives from it)',
  },
  {
    name: 'PORT',
    slice: 'shared',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: sharedServer.PORT,
    where: 'API listen port (default 3000)',
  },

  // db
  {
    name: 'DATABASE_URL',
    slice: 'db',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: dbServer.DATABASE_URL,
    where:
      'Postgres pooled URL. Local zero-account build: a pglite path e.g. pglite://.data/docket. Prod: Neon pooled URL.',
    sensitive: true,
  },
  {
    name: 'DATABASE_URL_UNPOOLED',
    slice: 'db',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: dbServer.DATABASE_URL_UNPOOLED,
    where: 'Unpooled URL used for migrations (falls back to DATABASE_URL).',
    sensitive: true,
  },

  // auth
  {
    name: 'BETTER_AUTH_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_SECRET,
    where: 'openssl rand -base64 32 (≥32 chars)',
    sensitive: true,
    generate: 'openssl rand -base64 32',
  },
  {
    name: 'BETTER_AUTH_URL',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_URL,
    where: 'Base URL Better Auth issues cookies/redirects for',
  },
  {
    name: 'BETTER_AUTH_TRUSTED_ORIGINS',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.BETTER_AUTH_TRUSTED_ORIGINS,
    where: 'CSV of trusted browser origins for CORS + cookies',
  },
  {
    name: 'BETTER_AUTH_ALLOWED_HOSTS',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.BETTER_AUTH_ALLOWED_HOSTS,
    where:
      'CSV of host patterns Better Auth issues cookies/redirects for (wildcards ok, e.g. *.vercel.app); enables dynamic base URL when set',
  },
  {
    name: 'BETTER_AUTH_COOKIE_DOMAIN',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.BETTER_AUTH_COOKIE_DOMAIN,
    where:
      'Parent domain to scope session cookies to (e.g. docket.localhost) so sibling subdomains share the session — required for the local oAuthProxy relay; unset ⇒ host-only cookies',
  },
  {
    name: 'BETTER_AUTH_PASSKEY_RP_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_PASSKEY_RP_ID,
    where: 'WebAuthn relying-party id (the registrable domain; localhost in dev)',
  },
  {
    name: 'BETTER_AUTH_PASSKEY_RP_NAME',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_PASSKEY_RP_NAME,
    where: "WebAuthn relying-party display name (default 'Docket')",
  },
  {
    name: 'GOOGLE_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GOOGLE_CLIENT_ID,
    where: 'Google Cloud OAuth client id (absent → provider hidden)',
  },
  {
    name: 'GOOGLE_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GOOGLE_CLIENT_SECRET,
    where: 'Google Cloud OAuth client secret',
    sensitive: true,
  },
  {
    name: 'GOOGLE_CALENDAR_WEBHOOK_URL',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GOOGLE_CALENDAR_WEBHOOK_URL,
    where:
      'Public HTTPS URL for POST /webhooks/calendar/google (absent ⇒ push hints disabled, scheduled sweep still polls)',
  },
  {
    name: 'GITHUB_APP_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_ID,
    where:
      'GitHub App id (Settings → Developer settings → GitHub Apps → App ID). Absent → GitHub connector uses the mock.',
  },
  {
    name: 'GITHUB_APP_SLUG',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_SLUG,
    where:
      'GitHub App URL slug (from its public page github.com/apps/<slug>) — builds the install URL',
  },
  {
    name: 'GITHUB_APP_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_CLIENT_ID,
    where: 'GitHub App OAuth client id (user-to-server: sign-in + "my issues" pull + identity)',
  },
  {
    name: 'GITHUB_APP_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_CLIENT_SECRET,
    where: 'GitHub App OAuth client secret (Generate a new client secret on the App page)',
    sensitive: true,
  },
  {
    name: 'GITHUB_APP_PRIVATE_KEY',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_PRIVATE_KEY,
    where: 'Path to the .pem you downloaded (or paste the PEM) — base64-encoded for you',
    sensitive: true,
  },
  {
    name: 'GITHUB_APP_WEBHOOK_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_WEBHOOK_SECRET,
    where: 'GitHub App webhook secret — verifies the firehose at POST /internal/ingest/github',
    sensitive: true,
    generate: 'openssl rand -hex 24',
  },
  {
    name: 'LINEAR_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_CLIENT_ID,
    where: 'Linear OAuth2 application client id (genericOAuth)',
  },
  {
    name: 'LINEAR_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_CLIENT_SECRET,
    where: 'Linear OAuth2 application client secret',
    sensitive: true,
  },
  {
    name: 'DISCORD_PUBLIC_KEY',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.DISCORD_PUBLIC_KEY,
    where:
      'Discord app Public Key (developer portal → General Information) — verifies POST /internal/ingest/discord',
  },
  {
    name: 'DISCORD_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.DISCORD_CLIENT_ID,
    where:
      'Discord OAuth2 application client id (developer portal → OAuth2) — powers Connect Discord',
  },
  {
    name: 'DISCORD_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.DISCORD_CLIENT_SECRET,
    where: 'Discord OAuth2 application client secret',
    sensitive: true,
  },
  {
    name: 'APPLE_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.APPLE_CLIENT_ID,
    where:
      'Apple Services ID e.g. com.docket.web (Sign in with Apple → the OAuth client_id). Needs all four APPLE_* vars; absent → provider hidden.',
  },
  {
    name: 'APPLE_TEAM_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.APPLE_TEAM_ID,
    where: 'Apple 10-char Team ID (Membership → Team ID) — the iss of the client-secret JWT',
  },
  {
    name: 'APPLE_KEY_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.APPLE_KEY_ID,
    where: 'Apple Sign-in key id (Keys → your Sign in with Apple key → Key ID)',
  },
  {
    name: 'APPLE_PRIVATE_KEY',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.APPLE_PRIVATE_KEY,
    where:
      'The downloaded .p8 PKCS#8 PEM (escaped \\n or one line) — signs the ES256 client-secret JWT',
    sensitive: true,
  },
  {
    name: 'MICROSOFT_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.MICROSOFT_CLIENT_ID,
    where: 'Microsoft Entra app client id (Outlook sign-in/link + Graph mail connector)',
  },
  {
    name: 'MICROSOFT_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.MICROSOFT_CLIENT_SECRET,
    where: 'Microsoft Entra app client secret',
    sensitive: true,
  },
  {
    name: 'MICROSOFT_TENANT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.MICROSOFT_TENANT_ID,
    where: "Entra tenant ('common' for multi-tenant; a tenant id to restrict to one directory)",
  },
  {
    name: 'OAUTH_PROXY_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.OAUTH_PROXY_SECRET,
    where: 'Shared oAuthProxy secret (SAME on prod + previews) — routes preview OAuth through prod',
    sensitive: true,
    generate: 'openssl rand -hex 24',
  },
  {
    name: 'OAUTH_PROXY_PRODUCTION_URL',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.OAUTH_PROXY_PRODUCTION_URL,
    where: 'Production product origin oAuthProxy routes through (e.g. https://app.docket.app)',
  },
] as const;
