import { authServer, dbServer, sharedServer } from './slices';
import { ALL, type VarSpec } from './registry-types';

/** Shared + database + auth variable specs. */
export const CORE_VARS: readonly VarSpec[] = [
  // shared
  {
    name: 'NODE_ENV',
    slice: 'shared',
    scope: 'server',
    targets: ALL,
    required: false,
    zod: sharedServer.NODE_ENV,
    where: 'development | test | production',
  },
  {
    name: 'APP_MODE',
    slice: 'shared',
    scope: 'server',
    targets: ALL,
    required: true,
    zod: sharedServer.APP_MODE,
    where: 'local | test | production — local/test force the mock boundary adapters',
  },
  {
    name: 'API_URL',
    slice: 'shared',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: sharedServer.API_URL,
    where: 'Public base URL of the Hono API',
  },
  {
    name: 'WEB_URL',
    slice: 'shared',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: sharedServer.WEB_URL,
    where:
      'Public origin of the product web app (sign-in/consent pages; MCP OAuth derives from it)',
  },
  {
    name: 'PORT',
    slice: 'shared',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: sharedServer.PORT,
    where: 'API listen port (default 3000)',
  },

  // db
  {
    name: 'DATABASE_URL',
    slice: 'db',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: dbServer.DATABASE_URL,
    where:
      'Postgres pooled URL. Local zero-account build: a pglite path e.g. pglite://.data/docket. Prod: Neon pooled URL.',
    sensitive: true,
  },
  {
    name: 'DATABASE_URL_UNPOOLED',
    slice: 'db',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: dbServer.DATABASE_URL_UNPOOLED,
    where: 'Unpooled URL used for migrations (falls back to DATABASE_URL).',
    sensitive: true,
  },

  // auth
  {
    name: 'BETTER_AUTH_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_SECRET,
    where: 'openssl rand -base64 32 (≥32 chars)',
    sensitive: true,
    generate: 'openssl rand -base64 32',
  },
  {
    name: 'BETTER_AUTH_URL',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_URL,
    where: 'Base URL Better Auth issues cookies/redirects for',
  },
  {
    name: 'BETTER_AUTH_TRUSTED_ORIGINS',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.BETTER_AUTH_TRUSTED_ORIGINS,
    where: 'CSV of trusted browser origins for CORS + cookies',
  },
  {
    name: 'BETTER_AUTH_ALLOWED_HOSTS',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.BETTER_AUTH_ALLOWED_HOSTS,
    where:
      'CSV of host patterns Better Auth issues cookies/redirects for (wildcards ok, e.g. *.vercel.app); enables dynamic base URL when set',
  },
  {
    name: 'BETTER_AUTH_COOKIE_DOMAIN',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.BETTER_AUTH_COOKIE_DOMAIN,
    where:
      'Parent domain to scope session cookies to (e.g. docket.localhost) so sibling subdomains share the session — required for the local oAuthProxy relay; unset ⇒ host-only cookies',
  },
  {
    name: 'BETTER_AUTH_PASSKEY_RP_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_PASSKEY_RP_ID,
    where: 'WebAuthn relying-party id (the registrable domain; localhost in dev)',
  },
  {
    name: 'BETTER_AUTH_PASSKEY_RP_NAME',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.BETTER_AUTH_PASSKEY_RP_NAME,
    where: "WebAuthn relying-party display name (default 'Docket')",
  },
  {
    name: 'BETTER_AUTH_PASSKEY_NATIVE_ORIGINS',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.BETTER_AUTH_PASSKEY_NATIVE_ORIGINS,
    where:
      'CSV of associated Android application origins accepted by the passkey verifier; unset keeps browser-only origin resolution',
    sensitive: false,
  },
  {
    name: 'GOOGLE_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GOOGLE_CLIENT_ID,
    where: 'Google Cloud OAuth client id (absent → provider hidden)',
  },
  {
    name: 'GOOGLE_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GOOGLE_CLIENT_SECRET,
    where: 'Google Cloud OAuth client secret',
    sensitive: true,
  },
  {
    name: 'GOOGLE_OAUTH_PUBLIC',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.GOOGLE_OAUTH_PUBLIC,
    where: 'true only after Google public OAuth verification is approved',
  },
  {
    name: 'GOOGLE_OAUTH_TEST_EMAILS',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GOOGLE_OAUTH_TEST_EMAILS,
    where: 'CSV of Docket user emails allowed during Google OAuth testing',
  },
  {
    name: 'GOOGLE_CALENDAR_WEBHOOK_URL',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GOOGLE_CALENDAR_WEBHOOK_URL,
    where:
      'Public HTTPS URL for POST /webhooks/calendar/google (absent ⇒ push hints disabled, scheduled sweep still polls)',
  },
  {
    name: 'WORK_LOCATION_PROJECTION_ENABLED',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.WORK_LOCATION_PROJECTION_ENABLED,
    where:
      'true enables outbound provider projection; false keeps canonical reads, edits, and inbound bootstrap active',
  },
  {
    name: 'GITHUB_APP_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_ID,
    where:
      'GitHub App id (Settings → Developer settings → GitHub Apps → App ID). Absent → GitHub connector uses the mock.',
  },
  {
    name: 'GITHUB_APP_SLUG',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_SLUG,
    where:
      'GitHub App URL slug (from its public page github.com/apps/<slug>) — builds the install URL',
  },
  {
    name: 'GITHUB_APP_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_CLIENT_ID,
    where: 'GitHub App OAuth client id (user-to-server: sign-in + "my issues" pull + identity)',
  },
  {
    name: 'GITHUB_APP_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_CLIENT_SECRET,
    where: 'GitHub App OAuth client secret (Generate a new client secret on the App page)',
    sensitive: true,
  },
  {
    name: 'GITHUB_APP_PRIVATE_KEY',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_PRIVATE_KEY,
    where: 'Path to the .pem you downloaded (or paste the PEM) — base64-encoded for you',
    sensitive: true,
  },
  {
    name: 'GITHUB_APP_WEBHOOK_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.GITHUB_APP_WEBHOOK_SECRET,
    where: 'GitHub App webhook secret — verifies the firehose at POST /internal/ingest/github',
    sensitive: true,
    generate: 'openssl rand -hex 24',
  },
  {
    name: 'LINEAR_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_CLIENT_ID,
    where: 'Linear OAuth application client id (native Better Auth social provider)',
  },
  {
    name: 'LINEAR_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_CLIENT_SECRET,
    where: 'Linear OAuth2 application client secret',
    sensitive: true,
  },
  {
    name: 'LATTICE_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LATTICE_CLIENT_ID,
    where:
      'Lovelace OAuth app client id (developer.uselovelace.com) — lets a person authorize Athena to run model turns on their own Lattice devices. Absent → the Lattice settings section is unavailable.',
  },
  {
    name: 'LATTICE_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LATTICE_CLIENT_SECRET,
    where: 'Lovelace OAuth app client secret — paired with LATTICE_CLIENT_ID',
    sensitive: true,
  },
  {
    name: 'LATTICE_ACCOUNTS_ISSUER',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LATTICE_ACCOUNTS_ISSUER,
    where:
      'Lovelace accounts issuer origin; defaults to https://auth.uselovelace.com. Set only to target a staging Lovelace.',
  },
  {
    name: 'LATTICE_GATEWAY_URL',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LATTICE_GATEWAY_URL,
    where:
      'Lattice gateway origin; defaults to https://lattice.uselovelace.com. Set only to target a staging or local gateway.',
  },
  {
    name: 'NOTION_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.NOTION_CLIENT_ID,
    where: "Connection's Configuration tab — Client ID (not a secret, shown in the OAuth URL too).",
  },
  {
    name: 'NOTION_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.NOTION_CLIENT_SECRET,
    where: "Connection's Configuration tab — Client secret (click the eye icon to reveal).",
    sensitive: true,
  },
  {
    name: 'NOTION_WEBHOOK_TOKEN',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.NOTION_WEBHOOK_TOKEN,
    where:
      'Webhooks tab, after creating a subscription — the one-time verification token from its first delivery. Optional: leave blank and the mirror polls instead.',
    sensitive: true,
  },
  {
    name: 'LINEAR_WEBHOOK_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_WEBHOOK_SECRET,
    where: 'Linear application webhook signing secret — verifies POST /internal/ingest/linear',
    sensitive: true,
  },
  {
    name: 'LINEAR_AGENT_ENABLED',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: authServer.LINEAR_AGENT_ENABLED,
    where:
      'Explicit Linear Agent release gate. Keep false until the current provider contract and sandbox round trip pass.',
  },
  {
    name: 'LINEAR_AGENT_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_AGENT_CLIENT_ID,
    where:
      'Linear Agent platform OAuth app client id (Settings → API → Agents) — a distinct, workspace-level `actor=app` install, separate from LINEAR_CLIENT_ID. Absent → the agent install is unavailable.',
  },
  {
    name: 'LINEAR_AGENT_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_AGENT_CLIENT_SECRET,
    where: 'Linear Agent platform OAuth app client secret',
    sensitive: true,
  },
  {
    name: 'LINEAR_AGENT_WEBHOOK_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.LINEAR_AGENT_WEBHOOK_SECRET,
    where:
      'Linear Agent platform webhook signing secret — verifies inbound AgentSessionEvent deliveries (distinct from LINEAR_WEBHOOK_SECRET)',
    sensitive: true,
  },
  {
    name: 'SLACK_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.SLACK_CLIENT_ID,
    where: 'Shared Slack app OAuth client id for the dormant user-token connect flow',
  },
  {
    name: 'SLACK_CLIENT_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.SLACK_CLIENT_SECRET,
    where: 'Shared Slack app OAuth client secret for the dormant user-token connect flow',
    sensitive: true,
  },
  {
    name: 'APPLE_CLIENT_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.APPLE_CLIENT_ID,
    where:
      'Apple Services ID e.g. com.docket.web (Sign in with Apple → the OAuth client_id). Needs all four APPLE_* vars; absent → provider hidden.',
  },
  {
    name: 'APPLE_TEAM_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.APPLE_TEAM_ID,
    where: 'Apple 10-char Team ID (Membership → Team ID) — the iss of the client-secret JWT',
  },
  {
    name: 'APPLE_KEY_ID',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.APPLE_KEY_ID,
    where: 'Apple Sign-in key id (Keys → your Sign in with Apple key → Key ID)',
  },
  {
    name: 'APPLE_PRIVATE_KEY',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.APPLE_PRIVATE_KEY,
    where:
      'The downloaded .p8 PKCS#8 PEM (escaped \\n or one line) — signs the ES256 client-secret JWT',
    sensitive: true,
  },
  {
    name: 'OAUTH_PROXY_SECRET',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.OAUTH_PROXY_SECRET,
    where: 'Shared oAuthProxy secret (SAME on prod + previews) — routes preview OAuth through prod',
    sensitive: true,
    generate: 'openssl rand -hex 24',
  },
  {
    name: 'OAUTH_PROXY_PRODUCTION_URL',
    slice: 'auth',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: authServer.OAUTH_PROXY_PRODUCTION_URL,
    where: 'Production product origin oAuthProxy routes through (e.g. https://app.docket.app)',
  },
] as const;
