import { agentServer, mcpServer, stripeServer } from './slices';
import type { VarSpec } from './registry-types';

/** Stripe + MCP + agent variable specs. */
export const SERVICE_VARS: readonly VarSpec[] = [
  // stripe
  {
    name: 'STRIPE_SECRET_KEY',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_SECRET_KEY,
    where: 'Stripe secret key (sk_...) — required when BILLING_ENABLED=true',
    sensitive: true,
  },
  {
    name: 'STRIPE_PUBLISHABLE_KEY',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_PUBLISHABLE_KEY,
    where: 'Stripe browser-safe publishable key (pk_...) exposed through GET /v1/config',
  },
  {
    name: 'STRIPE_WEBHOOK_SECRET',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_WEBHOOK_SECRET,
    where: 'Stripe webhook signing secret (whsec_...) from `stripe listen`',
    sensitive: true,
  },
  {
    name: 'DOCKET_PRICE_LOOKUP_TEAM',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.DOCKET_PRICE_LOOKUP_TEAM,
    where: 'Stripe price lookup_key for the Team plan',
  },
  {
    name: 'DOCKET_PRICE_LOOKUP_TEAM_ANNUAL',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.DOCKET_PRICE_LOOKUP_TEAM_ANNUAL,
    where: 'Stripe price lookup_key for the annual Team plan',
  },
  {
    name: 'STRIPE_PRICE_TEAM',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_PRICE_TEAM,
    where: 'Stripe price id (price_...) — alternative to the lookup key',
  },
  {
    name: 'STRIPE_BILLING_PORTAL_CONFIG_ID',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: stripeServer.STRIPE_BILLING_PORTAL_CONFIG_ID,
    where: 'Stripe billing portal configuration id',
  },
  {
    name: 'BILLING_ENABLED',
    slice: 'stripe',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: stripeServer.BILLING_ENABLED,
    where: 'true|false — gate that requires the Stripe keys when on (default false)',
  },

  // mcp
  {
    name: 'MCP_ISSUER_URL',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.MCP_ISSUER_URL,
    where: 'OAuth issuer URL for the MCP server (defaults to API_URL)',
  },
  {
    name: 'MCP_RESOURCE_URL',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.MCP_RESOURCE_URL,
    where: 'Canonical MCP resource URL (defaults to ${API_URL}/mcp)',
  },
  {
    name: 'MCP_ALLOWED_ORIGINS',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.MCP_ALLOWED_ORIGINS,
    where:
      'CSV of allowed browser Origins for /mcp (DNS-rebinding guard) — a security allowlist, never derived',
  },
  {
    name: 'OIDC_LOGIN_PAGE_URL',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.OIDC_LOGIN_PAGE_URL,
    where: 'Login page URL the OIDC provider redirects to (defaults to ${WEB_URL}/sign-in)',
  },
  {
    name: 'MCP_TASKS_ENABLED',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: mcpServer.MCP_TASKS_ENABLED,
    where: 'true|false — enable the MCP Tasks utility (requires MCP_SESSION_STORE_URL)',
  },
  {
    name: 'MCP_CIMD_TRUST_ALLOWLIST',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.MCP_CIMD_TRUST_ALLOWLIST,
    where: 'CSV of trusted client-id metadata document origins',
  },
  {
    name: 'MCP_CIMD_STRICT',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: mcpServer.MCP_CIMD_STRICT,
    where: 'true|false — strict CIMD validation (default true)',
  },
  {
    name: 'MCP_SESSION_STORE_URL',
    slice: 'mcp',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: mcpServer.MCP_SESSION_STORE_URL,
    where: 'Backing store URL for resumable MCP sessions',
  },

  // agent
  {
    name: 'ANTHROPIC_API_KEY',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.ANTHROPIC_API_KEY,
    where: 'Anthropic API key for the built-in Athena runtime',
    sensitive: true,
  },
  {
    name: 'CREDENTIALS_ENCRYPTION_KEY',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.CREDENTIALS_ENCRYPTION_KEY,
    where: 'Base64 32-byte key sealing org-held remote-MCP credentials (AES-256-GCM)',
    sensitive: true,
  },
  {
    name: 'AGENT_MAX_TURNS',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: agentServer.AGENT_MAX_TURNS,
    where: 'Per-session turn budget for the Athena agentic loop (e.g. 24)',
  },
  {
    name: 'ATHENA_MAX_CONCURRENT_RUNS',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.ATHENA_MAX_CONCURRENT_RUNS,
    where: 'Per-user Athena run limit (default 8, maximum 64)',
  },
  {
    name: 'ATHENA_ASYNC_RUNNER_ENABLED',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: true,
    zod: agentServer.ATHENA_ASYNC_RUNNER_ENABLED,
    where:
      'true|false — dispatch personal Athena generations through Cloudflare Queues and Workflows',
  },
  {
    name: 'CLOUDFLARE_ATHENA_RUNNER_URL',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.CLOUDFLARE_ATHENA_RUNNER_URL,
    where: 'Cloudflare runner Worker origin; required when ATHENA_ASYNC_RUNNER_ENABLED=true',
  },
  {
    name: 'CLOUDFLARE_TO_DOCKET_HMAC_SECRET',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.CLOUDFLARE_TO_DOCKET_HMAC_SECRET,
    where: 'HMAC secret authenticating Cloudflare execution callbacks to Docket',
    sensitive: true,
  },
  {
    name: 'DOCKET_TO_CLOUDFLARE_HMAC_SECRET',
    slice: 'agent',
    scope: 'server',
    targets: ['api'],
    required: false,
    zod: agentServer.DOCKET_TO_CLOUDFLARE_HMAC_SECRET,
    where: 'Distinct HMAC secret authenticating Docket execution dispatches to Cloudflare',
    sensitive: true,
  },
] as const;
