/**
 * Validate the Cloud Run environment a deploy is about to apply, before it applies it.
 *
 * @remarks
 * `deploy.yml` builds `docket-api-env.yaml` by interpolating `vars.*` into a heredoc and hands it
 * straight to `deploy-cloudrun`. Nothing read it in between, so an unset repository variable became
 * an empty string, the container refused to boot, and Cloud Run reported that as a failed rollout
 * rather than as a configuration error. That has happened three times; the workflow's own comments
 * record two of them and patch those instances with hand-applied `|| 'false'` defaults.
 *
 * This is the general guard those patches were standing in for. It reconstructs the environment the
 * container will actually see — the manifest plus the Secret Manager bindings mounted alongside it —
 * and checks it against `VAR_REGISTRY` through {@link checkEnvForTarget}, using the same zod schemas
 * the API boots against. A missing or malformed value fails here, named, with the hint that explains
 * it.
 *
 * Usage: `tsx scripts/verify-env-manifest.ts <manifest.yaml>`, with the bindings on
 * `API_SECRET_BINDINGS` and `LINEAR_AGENT_ENABLED` matching what the deploy passes to Cloud Run.
 */
import { readFileSync } from 'node:fs';
import process from 'node:process';

import { checkEnvForTarget, type EnvIssue } from '../packages/env/src/registry';

import { parseSecretBindings } from './production-secrets';

/**
 * Variables Cloud Run injects, so the manifest never declares them.
 *
 * @remarks
 * A property of this deploy surface, not of the variable: `PORT` is an ordinary required var
 * locally. Treated like a Secret Manager mount rather than relaxed in the registry, which would
 * stop it being required anywhere.
 */
const PLATFORM_INJECTED: readonly string[] = ['PORT'];

/**
 * Read the flat `KEY: value` manifest `deploy.yml` writes.
 *
 * @remarks
 * Deliberately not a YAML dependency: the file is generated by a heredoc in this repository and is
 * always one unnested `KEY: value` per line, so the whole grammar is a colon and optional quotes.
 * `scripts/env-file.ts` sets the same precedent for `.env` parsing.
 *
 * @param source - The manifest's contents.
 * @returns every declared key and its value, with surrounding quotes removed.
 */
export function parseEnvManifest(source: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const line of source.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const separator = trimmed.indexOf(':');
    if (separator === -1) continue;
    const name = trimmed.slice(0, separator).trim();
    const raw = trimmed.slice(separator + 1).trim();
    const unquoted =
      (raw.startsWith('"') && raw.endsWith('"') && raw.length >= 2) ||
      (raw.startsWith("'") && raw.endsWith("'") && raw.length >= 2)
        ? raw.slice(1, -1)
        : raw;
    env[name] = unquoted;
  }
  return env;
}

/**
 * The issues a deploy of this manifest would hit, or none.
 *
 * @remarks
 * The manifest carries only non-secret values; the rest arrive as Secret Manager mounts on the same
 * revision. Checking the manifest alone would therefore report every secret-backed variable as
 * missing, so a variable satisfied by a mount is not reported absent. Secret values are never read
 * here — `production-secrets.ts` already proves those resolve — only their names. The same applies
 * to {@link PLATFORM_INJECTED} values that Cloud Run sets on the container itself.
 *
 * @param manifest - The parsed manifest.
 * @param secretBindings - The raw `API_SECRET_BINDINGS` value the deploy mounts.
 * @returns every problem, so one run reports all of them rather than the first.
 */
export function verifyEnvManifest(
  manifest: Readonly<Record<string, string>>,
  secretBindings: string,
): EnvIssue[] {
  const supplied = new Set([
    ...parseSecretBindings(secretBindings).map((binding) => binding.envName),
    ...PLATFORM_INJECTED,
  ]);

  return checkEnvForTarget('api', manifest, { rejectUnknown: true }).filter((issue) => {
    // A secret-backed variable is absent from the manifest by design, and its value is unknowable
    // here — substituting a stand-in would only fail the schema's own length and format rules. Its
    // presence is satisfied by the mount, and `production-secrets.ts` already proves the payload
    // resolves and is not a placeholder. Only its absence from BOTH is a problem.
    if (issue.reason !== 'missing (required)') return true;
    return !supplied.has(issue.name);
  });
}

function main(): void {
  const [path] = process.argv.slice(2);
  if (!path) {
    console.error('usage: tsx scripts/verify-env-manifest.ts <manifest.yaml>');
    process.exit(2);
  }

  const issues = verifyEnvManifest(
    parseEnvManifest(readFileSync(path, 'utf8')),
    process.env['API_SECRET_BINDINGS'] ?? '',
  );

  if (issues.length === 0) {
    console.log('✓ env manifest — every variable the API requires is present and valid.');
    return;
  }

  console.error(`✗ env manifest — ${issues.length} problem(s) would break this deploy:\n`);
  for (const issue of issues) {
    console.error(`  ${issue.name}: ${issue.reason}`);
    console.error(`    where: ${issue.where}`);
  }
  console.error('\nThe API refuses to boot on this, which Cloud Run reports as a failed rollout.');
  process.exit(1);
}

if (process.argv[1]?.endsWith('verify-env-manifest.ts')) main();
