'use client';

/**
 * The task's Overview tab: the description, then the work around it, then the conversation.
 *
 * @remarks
 * Ordered the way a person reads an issue. The description leads, directly under the masthead;
 * the repeating-work backlink, when the task was generated by a series, follows it; the subtasks
 * and dependencies that break the work down come next; the activity history and the comment
 * composer close the page, where a reply belongs.
 */
import type { TaskDetail } from '@docket/work/task-model';
import type { QueryKey } from '@tanstack/react-query';
import type { JSX } from 'react';

import { TaskRepeatingWorkBacklink } from '@/components/recurrence/repeating-work-backlink';
import { useAppRouter } from '@/lib/interactions/navigation';
import { useRenameTask } from '@/lib/use-rename-task';
import type { TaskMutations } from '@/lib/use-task-mutations';

import { Dependencies } from './Dependencies';
import { Subtasks } from './Subtasks';
import { TaskActivityFeed } from './task-activity-feed';
import { TaskDetails } from './task-details';
import type { DescriptionExpansion } from './use-description-expansion';

/** The writes the Overview tab makes: the description, subtasks, and comments. */
export type TaskOverviewMutations = Pick<
  TaskMutations,
  'patchTask' | 'addSubtask' | 'toggleSubtask' | 'addComment'
>;

/** Props for {@link TaskOverviewPanel}. */
export interface TaskOverviewPanelProps {
  readonly orgId: string;
  readonly task: TaskDetail;
  readonly currentActorId: string | null;
  readonly canEdit: boolean;
  readonly canComment: boolean;
  /** The name to show for a project id. */
  readonly projectName: (projectId: string) => string;
  readonly projectLabel: string;
  readonly mutations: TaskOverviewMutations;
  /** The task's detail cache key, which a subtask rename re-reads. */
  readonly detailKey: QueryKey;
  readonly expansion: DescriptionExpansion;
}

/**
 * Render the Overview tab's content.
 *
 * @param props - See {@link TaskOverviewPanelProps}.
 * @returns the ordered overview sections.
 */
export function TaskOverviewPanel({
  orgId,
  task,
  currentActorId,
  canEdit,
  canComment,
  projectName,
  projectLabel,
  mutations,
  detailKey,
  expansion,
}: TaskOverviewPanelProps): JSX.Element {
  const router = useAppRouter();
  // Rename any subtask or dependency in place (an arbitrary task by id), then re-read this task's
  // detail so the refreshed titles flow back in.
  const onRenameTask = useRenameTask(orgId, [detailKey]);
  const onOpenTask = (id: string): void => {
    router.push(`/orgs/${orgId}/tasks/${id}`);
  };
  const taskId = task.id;
  return (
    <div className="flex min-w-0 flex-col gap-4 @2xl:gap-5">
      <TaskDetails
        orgId={orgId}
        task={task}
        currentActorId={currentActorId}
        canEdit={canEdit}
        onSave={(description) => {
          mutations.patchTask({ description: description ?? '' });
        }}
        expansion={expansion}
      />
      <TaskRepeatingWorkBacklink orgId={orgId} entityId={taskId} />
      <Subtasks
        organizationId={orgId}
        parentTaskId={taskId}
        subtasks={task.subtasks}
        onAdd={mutations.addSubtask}
        onToggle={(subtask, done) => mutations.toggleSubtask(subtask.id, done)}
        onOpen={onOpenTask}
        onRename={onRenameTask}
        canEdit={canEdit}
      />
      <Dependencies
        blocking={task.blocking}
        blockedBy={task.blockedBy}
        projectName={projectName}
        projectLabel={projectLabel}
        onOpen={onOpenTask}
        canEdit={canEdit}
        onRename={onRenameTask}
      />
      <TaskActivityFeed
        orgId={orgId}
        taskId={taskId}
        onComment={mutations.addComment}
        canComment={canComment}
      />
    </div>
  );
}
