'use client';

/**
 * The task's Overview tab: the description, then the work around it, then the conversation.
 *
 * @remarks
 * Ordered the way a person reads an issue. The description leads, directly under the masthead;
 * the repeating-work backlink, when the task was generated by a series, follows it; the subtasks
 * that break the work down and the tasks it is linked to come next; the activity history and the
 * comment composer close the page, where a reply belongs. Every section is flat and spans the body
 * column, 32px apart (`docs/design/references/detail-page-layout.md`).
 */
import type { TaskDetail } from '@docket/work/task-model';
import type { JSX } from 'react';

import { TaskRepeatingWorkBacklink } from '@/components/recurrence/repeating-work-backlink';
import type { TaskMutations } from '@/lib/use-task-mutations';

import { Subtasks } from './Subtasks';
import { TaskActivityFeed } from './task-activity-feed';
import { TaskDetails } from './task-details';
import { TaskRelations } from './task-relations';
import type { DescriptionExpansion } from './use-description-expansion';

/** The writes the Overview tab makes: the description, subtasks, and comments. */
export type TaskOverviewMutations = Pick<
  TaskMutations,
  'patchTask' | 'addSubtask' | 'toggleSubtask' | 'addComment'
>;

/** Props for {@link TaskOverviewPanel}. */
export interface TaskOverviewPanelProps {
  readonly orgId: string;
  readonly task: TaskDetail;
  readonly currentActorId: string | null;
  readonly canEdit: boolean;
  readonly canComment: boolean;
  /** The name to show for a project id. */
  readonly projectName: (projectId: string) => string;
  readonly mutations: TaskOverviewMutations;
  readonly expansion: DescriptionExpansion;
}

/**
 * Render the Overview tab's content.
 *
 * @param props - See {@link TaskOverviewPanelProps}.
 * @returns the ordered overview sections.
 */
export function TaskOverviewPanel({
  orgId,
  task,
  currentActorId,
  canEdit,
  canComment,
  projectName,
  mutations,
  expansion,
}: TaskOverviewPanelProps): JSX.Element {
  const taskId = task.id;
  return (
    <div className="flex min-w-0 flex-col gap-8">
      <TaskDetails
        orgId={orgId}
        task={task}
        currentActorId={currentActorId}
        canEdit={canEdit}
        onSave={(description) => {
          mutations.patchTask({ description: description ?? '' });
        }}
        expansion={expansion}
      />
      <TaskRepeatingWorkBacklink orgId={orgId} entityId={taskId} />
      <Subtasks task={task} mutations={mutations} canEdit={canEdit} />
      <TaskRelations task={task} projectName={projectName} canEdit={canEdit} />
      <TaskActivityFeed
        orgId={orgId}
        taskId={taskId}
        onComment={mutations.addComment}
        canComment={canComment}
      />
    </div>
  );
}
