/**
 * Generated by `scripts/generate-offline-routes.ts` from `src/app/(app)`. Do not edit by hand.
 *
 * @remarks
 * Maps every authenticated route to the client component that renders it, so the app can render a
 * route without a server document for it. Regenerate with
 * `pnpm --filter @docket/web exec tsx scripts/generate-offline-routes.ts`; a policy test fails if
 * this file and the route tree disagree.
 *
 * Every `load` is a dynamic import, which is what keeps the route table out of the shell's own
 * bundle and gives the service worker a per-route chunk it can precache.
 */
import type { ComponentType } from 'react';

/** One route, and how to load the component that renders it. */
export interface OfflineRoute {
  /** The URL pattern in Next's `[param]` notation. */
  readonly pattern: string;
  /** Load the route's client component. */
  readonly load: () => Promise<ComponentType>;
}

/** Every authenticated route that has a client component to render. */
export const OFFLINE_ROUTES: readonly OfflineRoute[] = [
  {
    pattern: '/athena/mail/[id]',
    load: async () => (await import('@/app/(app)/athena/mail/[id]/page')).default,
  },
  {
    pattern: '/athena/mail',
    load: async () => (await import('@/app/(app)/athena/mail/page')).default,
  },
  {
    pattern: '/athena',
    load: async () => (await import('@/app/(app)/athena/page')).default,
  },
  {
    pattern: '/calendar',
    load: async () => (await import('@/app/(app)/calendar/calendar-client')).default,
  },
  {
    pattern: '/exports/[exportId]',
    load: async () => (await import('@/app/(app)/exports/[exportId]/page')).default,
  },
  {
    pattern: '/inbox',
    load: async () => (await import('@/app/(app)/inbox/inbox-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/[...unmatched]',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/[...unmatched]/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/cycles/[cycleId]',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/cycles/[cycleId]/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/cycles',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/cycles/cycles-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/graph',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/graph/graph-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/initiatives/[initiativeId]',
    load: async () =>
      (await import('@/app/(app)/orgs/[orgId]/initiatives/[initiativeId]/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/initiatives',
    load: async () =>
      (await import('@/app/(app)/orgs/[orgId]/initiatives/initiatives-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/my-work',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/my-work/my-work-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/people/[actorId]',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/people/[actorId]/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/people',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/people/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/programs/[programId]',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/programs/[programId]/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/programs',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/programs/programs-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/projects/[projectId]',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/projects/[projectId]/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/projects',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/projects/projects-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/search',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/search/org-search-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/sessions/[sessionId]',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/sessions/[sessionId]/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/automations',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/automations/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/calendar',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/calendar/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/connected-accounts',
    load: async () =>
      (await import('@/app/(app)/orgs/[orgId]/settings/connected-accounts/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/connected-apps',
    load: async () =>
      (await import('@/app/(app)/orgs/[orgId]/settings/connected-apps/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/connections/google-calendar',
    load: async () =>
      (await import('@/app/(app)/orgs/[orgId]/settings/connections/google-calendar/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/connections',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/connections/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/danger',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/danger/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/export',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/export/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/general',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/general/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/import',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/import/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/members',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/members/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/notifications',
    load: async () =>
      (await import('@/app/(app)/orgs/[orgId]/settings/notifications/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/publishing',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/publishing/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/security',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/settings/security/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/settings/work-structure',
    load: async () =>
      (await import('@/app/(app)/orgs/[orgId]/settings/work-structure/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/stream',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/stream/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/tasks/[taskId]',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/tasks/[taskId]/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/tasks',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/tasks/org-tasks-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/teams',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/teams/teams-client')).default,
  },
  {
    pattern: '/orgs/[orgId]/triage',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/triage/page')).default,
  },
  {
    pattern: '/orgs/[orgId]/views',
    load: async () => (await import('@/app/(app)/orgs/[orgId]/views/page')).default,
  },
  {
    pattern: '/plan',
    load: async () => (await import('@/app/(app)/plan/page')).default,
  },
  {
    pattern: '/portfolio',
    load: async () => (await import('@/app/(app)/portfolio/portfolio-client')).default,
  },
  {
    pattern: '/search',
    load: async () => (await import('@/app/(app)/search/hub-search-client')).default,
  },
  {
    pattern: '/settings/athena',
    load: async () => (await import('@/app/(app)/settings/athena/page')).default,
  },
  {
    pattern: '/settings/automations',
    load: async () => (await import('@/app/(app)/settings/automations/page')).default,
  },
  {
    pattern: '/settings/calendar',
    load: async () => (await import('@/app/(app)/settings/calendar/page')).default,
  },
  {
    pattern: '/settings/connected-apps',
    load: async () => (await import('@/app/(app)/settings/connected-apps/page')).default,
  },
  {
    pattern: '/settings/connections/google-calendar',
    load: async () =>
      (await import('@/app/(app)/settings/connections/google-calendar/page')).default,
  },
  {
    pattern: '/settings/connections',
    load: async () => (await import('@/app/(app)/settings/connections/page')).default,
  },
  {
    pattern: '/settings/data-privacy',
    load: async () =>
      (await import('@/app/(app)/settings/data-privacy/data-privacy-client')).default,
  },
  {
    pattern: '/settings/notifications',
    load: async () => (await import('@/app/(app)/settings/notifications/page')).default,
  },
  {
    pattern: '/settings/profile',
    load: async () => (await import('@/app/(app)/settings/profile/page')).default,
  },
  {
    pattern: '/settings/security',
    load: async () => (await import('@/app/(app)/settings/security/page')).default,
  },
  {
    pattern: '/settings/workspaces',
    load: async () => (await import('@/app/(app)/settings/workspaces/page')).default,
  },
  {
    pattern: '/stream',
    load: async () => (await import('@/app/(app)/stream/page')).default,
  },
  {
    pattern: '/tasks',
    load: async () => (await import('@/app/(app)/tasks/all-tasks-client')).default,
  },
  {
    pattern: '/time',
    load: async () => (await import('@/app/(app)/time/time-client')).default,
  },
  {
    pattern: '/today',
    load: async () => (await import('@/app/(app)/today/page')).default,
  },
  {
    pattern: '/workspaces/new',
    load: async () => (await import('@/app/(app)/workspaces/new/page')).default,
  },
];

/** Just the patterns, for matching a pathname without touching any route's component. */
export const ROUTE_PATTERNS: readonly string[] = OFFLINE_ROUTES.map((route) => route.pattern);
