/**
 * Live verification: prove that a model running on THIS machine answers Athena, through a Lattice
 * gateway, and that taking the machine away produces an explicit unavailable state rather than a
 * quiet cloud answer.
 *
 * @remarks
 * ## What is real here and what is not
 *
 * **Real:** Docket's Lattice OAuth client, its gateway client, and its `LatticeAgentTurnRuntime`,
 * unmodified — the same modules the API uses. Real HTTP on every hop. Real PKCE. And, most
 * importantly, **real inference**: the reply text is generated by a model served locally by LM
 * Studio (or Ollama) on this computer, not scripted anywhere in this file.
 *
 * **Not real:** Lovelace's hosted accounts issuer and the hosted Lattice gateway, because
 * `lattice.uselovelace.com` and `developer.uselovelace.com` do not resolve yet (verified: DNS
 * NXDOMAIN on 2026-08-02) and no Docket OAuth client is registered. They are stood in for by local
 * servers implementing the documented contract, and the relay leg the daemon would normally poll
 * for is collapsed into a direct forward, because the installed `lattice-daemon 0.1.0` has no
 * relay support compiled in (verified: no `LATTICE_ENABLE_RELAY` symbol in the binary).
 *
 * That boundary is stated in the report this script writes, so nobody reads it as more than it is.
 *
 * ## Running it
 *
 * ```bash
 * # with LM Studio or Ollama serving a model locally
 * pnpm --filter @docket/api exec tsx tests/lattice/verify-lattice-local.ts
 * ```
 */
import { readdir, readFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import type { AddressInfo } from 'node:net';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { LatticeAgentTurnRuntime } from '@docket/agent-runtime';
import {
  LatticeUnavailableError,
  beginLatticeAuthorization,
  completeLatticeAuthorization,
  listLatticeDevices,
  runLatticeChat,
  type LatticeGatewayContext,
  type LatticeOAuthClientConfig,
} from '@docket/integrations';

/** Where the recorded evidence is written. */
const REPORT_PATH = resolve(
  import.meta.dirname,
  '../../../../docs/engineering/evidence/lattice-local-device-run.md',
);

/** Local OpenAI-compatible model servers, in the order this script tries them. */
const LOCAL_MODEL_SERVERS: readonly { name: string; base: string }[] = [
  { name: 'LM Studio', base: 'http://localhost:1234/v1' },
  { name: 'Ollama', base: 'http://localhost:11434/v1' },
];

/** One hop recorded for the request trace. */
interface Hop {
  readonly at: string;
  readonly leg: 'docket→gateway' | 'gateway→device';
  readonly method: string;
  readonly path: string;
  readonly model?: string;
  readonly requestId: string;
  readonly auth?: string;
}

/** The mutable state the stand-ins share. */
interface Harness {
  readonly hops: Hop[];
  deviceOnline: boolean;
  readonly device: { name: string; base: string; model: string };
}

/** Read a request body as JSON or form-encoded. */
async function readBody(req: IncomingMessage): Promise<Record<string, unknown>> {
  const chunks: Buffer[] = [];
  for await (const chunk of req) chunks.push(chunk as Buffer);
  const raw = Buffer.concat(chunks).toString('utf8');
  if (raw === '') return {};
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    return Object.fromEntries(new URLSearchParams(raw));
  }
}

/** Read one field as a string; anything non-string reads as empty rather than `[object Object]`. */
function field(source: Record<string, unknown>, key: string): string {
  const value = source[key];
  return typeof value === 'string' ? value : '';
}

/** Send a JSON response. */
function send(res: ServerResponse, status: number, body: unknown): void {
  res.writeHead(status, { 'content-type': 'application/json' });
  res.end(JSON.stringify(body));
}

/** Start a server on an ephemeral port. */
async function listen(server: Server): Promise<string> {
  await new Promise<void>((done) => server.listen(0, '127.0.0.1', done));
  return `http://127.0.0.1:${String((server.address() as AddressInfo).port)}`;
}

/** Find a local model server that is actually serving something. */
async function findLocalModel(): Promise<{ name: string; base: string; model: string }> {
  for (const server of LOCAL_MODEL_SERVERS) {
    try {
      const response = await fetch(`${server.base}/models`, {
        signal: AbortSignal.timeout(4000),
      });
      if (!response.ok) continue;
      const body = (await response.json()) as { data?: { id: string }[] };
      // Prefer a small instruct model: this is a smoke test, not a benchmark, and a 35B model
      // makes the run take minutes for no extra proof.
      const ids = (body.data ?? []).map((entry) => entry.id);
      const preferred =
        ids.find((id) => id.includes('qwen2.5-0.5b')) ??
        ids.find((id) => /0\.5b|1b|3b|gemma-4-e4b/i.test(id)) ??
        ids[0];
      if (preferred) return { name: server.name, base: server.base, model: preferred };
    } catch {
      // Try the next candidate; a missing local server is an ordinary state here.
    }
  }
  throw new Error(
    'No local OpenAI-compatible model server answered on :1234 (LM Studio) or :11434 (Ollama).',
  );
}

/** The Lovelace accounts stand-in: authorize + token, with real PKCE verification. */
function accountsStub(): Server {
  let challenge = '';
  return createServer((req, res) => {
    void (async () => {
      const url = new URL(req.url ?? '/', 'http://localhost');
      if (url.pathname === '/oauth/authorize') {
        challenge = url.searchParams.get('code_challenge') ?? '';
        send(res, 200, { consent: 'granted' });
        return;
      }
      if (url.pathname === '/oauth/token') {
        const form = await readBody(req);
        const { createHash } = await import('node:crypto');
        const verifier = field(form, 'code_verifier');
        if (createHash('sha256').update(verifier).digest('base64url') !== challenge) {
          send(res, 400, { error: 'invalid_grant' });
          return;
        }
        send(res, 200, {
          access_token: `at_${randomUUID()}`,
          refresh_token: 'rt_live',
          expires_in: 3600,
          scope: 'lattice:compute:inference lattice:compute:catalog:read',
        });
        return;
      }
      send(res, 404, { error: 'not_found' });
    })();
  });
}

/** The Lattice gateway stand-in, relaying to the real local model server. */
function gatewayStub(harness: Harness): Server {
  return createServer((req, res) => {
    void (async () => {
      const url = new URL(req.url ?? '/', 'http://localhost');
      const requestId = `req_${randomUUID().slice(0, 12)}`;
      const auth = req.headers.authorization;

      if (url.pathname === '/v1/personal-runtimes') {
        harness.hops.push({
          at: new Date().toISOString(),
          leg: 'docket→gateway',
          method: 'GET',
          path: url.pathname,
          requestId,
          ...(auth ? { auth: `${auth.slice(0, 14)}…` } : {}),
        });
        send(res, 200, {
          runtimes: [
            {
              latticeId: 'lat_thismac',
              accountId: 'acct_local',
              displayName: `This Mac (${harness.device.name})`,
              executionBackend: 'local-model',
              status: harness.deviceOnline ? 'reachable' : 'offline',
              createdAt: '2026-08-02T00:00:00.000Z',
              updatedAt: new Date().toISOString(),
              lastSeenAt: new Date().toISOString(),
            },
          ],
        });
        return;
      }

      if (url.pathname === '/v1/chat/completions') {
        const body = await readBody(req);
        harness.hops.push({
          at: new Date().toISOString(),
          leg: 'docket→gateway',
          method: 'POST',
          path: url.pathname,
          model: field(body, 'model'),
          requestId,
          ...(auth ? { auth: `${auth.slice(0, 14)}…` } : {}),
        });
        if (!harness.deviceOnline) {
          send(res, 409, { error: 'runtime_unreachable', message: 'daemon is not polling' });
          return;
        }
        harness.hops.push({
          at: new Date().toISOString(),
          leg: 'gateway→device',
          method: 'POST',
          path: '/v1/chat/completions',
          model: harness.device.model,
          requestId,
        });
        const relayed = await fetch(`${harness.device.base}/chat/completions`, {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            model: harness.device.model,
            messages: body['messages'],
            max_tokens: body['max_tokens'] ?? 256,
          }),
          signal: AbortSignal.timeout(180_000),
        });
        send(res, relayed.status, await relayed.json());
        return;
      }

      send(res, 404, { error: 'not_found' });
    })();
  });
}

/**
 * Pull the device's own record of the inference out of LM Studio's server log.
 *
 * @remarks
 * This is the difference between "Docket says a local model answered" and "the machine says so".
 * The log lives outside anything this script controls, so it is independent corroboration.
 *
 * @param model - The model id to look for.
 * @returns The matching log lines, or an explanation of why none were found.
 */
async function deviceLogExcerpt(model: string): Promise<string> {
  const root = `${homedir()}/.lmstudio/server-logs`;
  try {
    const months = (await readdir(root)).sort();
    const latestMonth = months.at(-1);
    if (!latestMonth) return 'No LM Studio server-log directory was found.';
    const files = (await readdir(`${root}/${latestMonth}`)).sort();
    const latest = files.at(-1);
    if (!latest) return 'No LM Studio server log file was found.';
    const lines = (await readFile(`${root}/${latestMonth}/${latest}`, 'utf8')).split('\n');
    const matched = lines.filter(
      (line) =>
        line.includes(model) &&
        (line.includes('Running chat completion') ||
          line.includes('Loading model from') ||
          line.includes('Prompt processing progress')),
    );
    return matched.slice(-4).join('\n') || 'No matching lines were found in the LM Studio log.';
  } catch (error) {
    return `LM Studio log unavailable: ${error instanceof Error ? error.message : 'unknown'}`;
  }
}

/** The whole verification. */
async function main(): Promise<void> {
  const device = await findLocalModel();
  const harness: Harness = { hops: [], deviceOnline: true, device };

  const accounts = accountsStub();
  const accountsOrigin = await listen(accounts);
  const gateway = gatewayStub(harness);
  const gatewayOrigin = await listen(gateway);

  const oauth: LatticeOAuthClientConfig = {
    issuer: accountsOrigin,
    clientId: 'client_docket_local',
    clientSecret: 'secret_local',
    redirectUri: 'http://127.0.0.1/callback',
  };

  // 1. Real OAuth: build the consent URL, visit it, exchange the code with the PKCE verifier.
  const begun = beginLatticeAuthorization(oauth, 'state_local');
  await fetch(begun.authorizationUrl);
  const credential = await completeLatticeAuthorization(oauth, {
    authorizationCode: 'code_local',
    credential: begun.credential,
  });

  const context: LatticeGatewayContext = {
    accessToken: credential.accessToken,
    baseUrl: gatewayOrigin,
  };

  // 2. Discover the device through the gateway.
  const devices = await listLatticeDevices(context);

  // 3. Run a real turn through Docket's own turn runtime, on the local model.
  const runtime = new LatticeAgentTurnRuntime({
    maxTokens: 160,
    chat: {
      async runChat(request) {
        const completion = await runLatticeChat(context, {
          deviceId: 'lat_thismac',
          messages: request.messages,
          maxTokens: request.maxTokens,
        });
        const choice = completion.choices[0];
        return {
          text: choice?.message.content ?? '',
          ...(choice?.finish_reason === undefined ? {} : { finishReason: choice.finish_reason }),
          model: completion.model,
        };
      },
    },
  });

  const started = Date.now();
  const events = [];
  for await (const event of runtime.streamTurn({
    system: 'You are Athena, a concise chief of staff. Answer in one short sentence.',
    messages: [
      {
        role: 'user',
        content: [{ type: 'text', text: 'In one sentence: what is a docket?' }],
      },
    ],
    tools: [],
  })) {
    events.push(event);
  }
  const elapsedMs = Date.now() - started;
  const answer = events.find((event) => event.type === 'text');
  const replyText = answer?.text ?? '';

  // 4. Take the device away and confirm the failure is explicit, with nothing served from anywhere.
  harness.deviceOnline = false;
  const hopsBefore = harness.hops.filter((hop) => hop.leg === 'gateway→device').length;
  let offlineReason = 'NO ERROR RAISED — THIS IS A FAILURE';
  try {
    for await (const event of runtime.streamTurn({
      system: 'You are Athena.',
      messages: [{ role: 'user', content: [{ type: 'text', text: 'Still there?' }] }],
      tools: [],
    })) {
      offlineReason = `A TURN WAS SERVED WHILE OFFLINE (${event.type}) — THIS IS A FAILURE`;
    }
  } catch (error) {
    offlineReason =
      error instanceof LatticeUnavailableError ? error.reason : `unexpected: ${String(error)}`;
  }
  const hopsAfter = harness.hops.filter((hop) => hop.leg === 'gateway→device').length;

  // Give the log writer a moment: LM Studio flushes its server log asynchronously.
  await new Promise((done) => setTimeout(done, 1500));
  const deviceLog = await deviceLogExcerpt(device.model);

  const trace = harness.hops
    .map(
      (hop) =>
        `| ${hop.at} | ${hop.leg} | ${hop.method} ${hop.path} | ${hop.model ?? '—'} | ${hop.requestId} | ${hop.auth ?? '—'} |`,
    )
    .join('\n');

  const report = `# Evidence: an Athena turn answered by a model on this device

_Generated by \`apps/api/tests/lattice/verify-lattice-local.ts\` on ${new Date().toISOString()}._

## What is real in this run, and what is stood in for

| Hop | Real? | Notes |
| --- | --- | --- |
| Docket's OAuth client (PKCE, token exchange) | **real** | \`@docket/integrations\` \`lattice-oauth\`, unmodified |
| Docket's gateway client | **real** | \`@docket/integrations\` \`lattice-sdk\` / \`lattice-gateway\`, unmodified |
| Docket's turn runtime + tool protocol | **real** | \`@docket/agent-runtime\` \`LatticeAgentTurnRuntime\`, unmodified |
| Lovelace accounts issuer | stand-in | \`accounts.uselovelace.com\` OIDC discovery returns 500/404 and no Docket OAuth client is registered |
| Lattice hosted gateway | stand-in | \`lattice.uselovelace.com\` does not resolve (DNS NXDOMAIN, 2026-08-02) |
| Outbound relay + \`lattice-daemon\` | collapsed | installed \`lattice-daemon 0.1.0\` has no relay support compiled in (no \`LATTICE_ENABLE_RELAY\` symbol) |
| **The model inference itself** | **real** | ${device.name} serving \`${device.model}\` on this computer |

## The device Athena was pointed at

\`\`\`json
${JSON.stringify(devices, null, 2)}
\`\`\`

## The turn

- **Prompt:** \`In one sentence: what is a docket?\`
- **Served by:** ${device.name} → \`${device.model}\`, locally, in ${String(elapsedMs)} ms
- **Model selector on the wire:** \`lattice:personal:lat_thismac\`

**Reply generated on this machine:**

> ${replyText.trim().replace(/\n+/g, ' ')}

## The device's own record of the inference

Independent of anything Docket wrote — this is ${device.name}'s server log on this computer:

\`\`\`
${deviceLog}
\`\`\`

## Request trace

Athena called the **gateway host**; the gateway — not Docket — reached the device.

| at | leg | request | model | request id | authorization |
| --- | --- | --- | --- | --- | --- |
${trace}

## The device going offline

- Reason surfaced to Athena: **\`${offlineReason}\`**
- \`gateway→device\` hops before the offline attempt: **${String(hopsBefore)}**
- \`gateway→device\` hops after it: **${String(hopsAfter)}**

Equal counts mean the offline turn ran nowhere at all — not on the device, and not on a cloud
model. That is the invariant the feature exists to hold.
`;

  await mkdir(dirname(REPORT_PATH), { recursive: true });
  await writeFile(REPORT_PATH, report, 'utf8');

  accounts.close();
  gateway.close();

  process.stdout.write(`local model:   ${device.name} / ${device.model}\n`);
  process.stdout.write(`reply:         ${replyText.trim().slice(0, 120)}\n`);
  process.stdout.write(`offline reason:${offlineReason}\n`);
  process.stdout.write(`device hops:   ${String(hopsBefore)} -> ${String(hopsAfter)}\n`);
  process.stdout.write(`report:        ${REPORT_PATH}\n`);
}

await main();
